{ "year" : 1993, "plot" : "A botched mid-air heist results in suitcases full of cash being searched for by various groups throughout the Rocky Mountains.", "genres" : ["Action", "Adventure", "Thriller"], "title" : "Cliffhanger", "score" : 0.92509341239929199 }
{ "plot" : "The dying words of a thief spark a madcap cross-country rush to find some treasure.", "genres" : ["Action", "Adventure", "Comedy"], "title" : "It's a Mad, Mad, Mad, Mad World", "year" : 1963, "score" : 0.92273008823394775 }
{ "year" : 1991, "plot" : "A cat burglar is forced to steal Da Vinci works of art for a world domination plot.", "genres" : ["Action", "Adventure", "Comedy"], "title" : "Hudson Hawk", "score" : 0.9183650016784668 }
{ "plot" : "In 1997, when the US President crashes into Manhattan, now a giant maximum security prison, a convicted bank robber is sent in for a rescue.", "genres" : ["Action", "Sci-Fi"], "title" : "Escape from New York", "year" : 1981, "score" : 0.91609716415405273 }
{ "plot" : "Patrick and Tony are hired by the wealthy gambler to steal the priceless Romanov stones, Russian jewels. They do it, but almost lose their lives when he double-crosses them. They turn around and get revenge.", "genres" : ["Action", "Thriller"], "title" : "The Romanov Stones", "year" : 1993, "score" : 0.9152265191078186 }
{ "plot" : "An attempted robbery turns to be an unexpected recruitment when two unemployed men mistakenly break into a police office instead of a store.", "genres" : ["Action", "Comedy", "Adventure"], "title" : "Crime Busters", "year" : 1977, "score" : 0.91385889053344727 }
{ "plot" : "In the aftermath of the Persian Gulf War, 4 soldiers set out to steal gold that was stolen from Kuwait, but they discover people who desperately need their help.", "genres" : ["Action", "Adventure", "Comedy"], "title" : "Three Kings", "year" : 1999, "score" : 0.91333001852035522 }
{ "plot" : "A professional thief is hired by the FBI to steal a data tape from a company under investigation. The analysis of this tape, will prove the criminal activities of this company. As this ...", "genres" : ["Action", "Sci-Fi", "Thriller"], "title" : "Black Moon Rising", "year" : 1986, "score" : 0.91205686330795288 }
{ "plot" : "A group of heavily armed hijackers board a luxury ocean liner in the South Pacific Ocean to loot it, only to do battle with a series of large-sized, tentacled, man-eating sea creatures who have taken over the ship first.", "genres" : ["Action", "Adventure", "Horror"], "title" : "Deep Rising", "year" : 1998, "score" : 0.91180777549743652 }
{ "plot" : "A young man comes to the rescue of his girlfriend abducted by thieves and brought to Rio. An extravagant adventure ensues.", "genres" : ["Action", "Adventure", "Comedy"], "title" : "That Man from Rio", "year" : 1964, "score" : 0.91023355722427368 }
