// This file is auto-generated by generate-local-cli-commands.ts
// Source: mongodb/atlas-local-cli repository (main)
// Generated: 2026-02-19T03:10:19.922Z
// Do not edit manually - your changes will be overwritten

import type { TocItem } from '../types';

export const atlasCliLocalCommands: TocItem[] = [
  {
    label: 'connect',
    contentSite: 'atlas-cli',
    url: '/docs/atlas/cli/:version/command/atlas-local-connect/',
  },
  {
    label: 'delete',
    contentSite: 'atlas-cli',
    url: '/docs/atlas/cli/:version/command/atlas-local-delete/',
  },
  {
    label: 'list',
    contentSite: 'atlas-cli',
    url: '/docs/atlas/cli/:version/command/atlas-local-list/',
  },
  {
    label: 'logs',
    contentSite: 'atlas-cli',
    url: '/docs/atlas/cli/:version/command/atlas-local-logs/',
  },
  {
    label: 'search',
    contentSite: 'atlas-cli',
    url: '/docs/atlas/cli/:version/command/atlas-local-search/',
    collapsible: true,
    items: [
      {
        label: 'indexes',
        contentSite: 'atlas-cli',
        url: '/docs/atlas/cli/:version/command/atlas-local-search-indexes/',
        collapsible: true,
        items: [
          {
            label: 'create',
            contentSite: 'atlas-cli',
            url: '/docs/atlas/cli/:version/command/atlas-local-search-indexes-create/',
          },
          {
            label: 'delete',
            contentSite: 'atlas-cli',
            url: '/docs/atlas/cli/:version/command/atlas-local-search-indexes-delete/',
          },
          {
            label: 'describe',
            contentSite: 'atlas-cli',
            url: '/docs/atlas/cli/:version/command/atlas-local-search-indexes-describe/',
          },
          {
            label: 'list',
            contentSite: 'atlas-cli',
            url: '/docs/atlas/cli/:version/command/atlas-local-search-indexes-list/',
          },
        ],
      },
    ],
  },
  {
    label: 'setup',
    contentSite: 'atlas-cli',
    url: '/docs/atlas/cli/:version/command/atlas-local-setup/',
  },
  {
    label: 'start',
    contentSite: 'atlas-cli',
    url: '/docs/atlas/cli/:version/command/atlas-local-start/',
  },
  {
    label: 'stop',
    contentSite: 'atlas-cli',
    url: '/docs/atlas/cli/:version/command/atlas-local-stop/',
  },
];
