// This file is auto-generated by generate-k8s-cli-commands.ts
// Source: mongodb/atlas-cli-plugin-kubernetes repository (main)
// Generated: 2026-03-17T23:09:22.175Z
// Do not edit manually - your changes will be overwritten

import type { TocItem } from '../types';

export const atlasCliK8sCommands: TocItem[] = [
  {
    label: 'config',
    contentSite: 'atlas-cli',
    url: '/docs/atlas/cli/:version/command/atlas-kubernetes-config/',
    collapsible: true,
    items: [
      {
        label: 'apply',
        contentSite: 'atlas-cli',
        url: '/docs/atlas/cli/:version/command/atlas-kubernetes-config-apply/',
      },
      {
        label: 'generate',
        contentSite: 'atlas-cli',
        url: '/docs/atlas/cli/:version/command/atlas-kubernetes-config-generate/',
      },
    ],
  },
  {
    label: 'dry-run',
    contentSite: 'atlas-cli',
    url: '/docs/atlas/cli/:version/command/atlas-kubernetes-dry-run/',
  },
  {
    label: 'operator',
    contentSite: 'atlas-cli',
    url: '/docs/atlas/cli/:version/command/atlas-kubernetes-operator/',
    collapsible: true,
    items: [
      {
        label: 'install',
        contentSite: 'atlas-cli',
        url: '/docs/atlas/cli/:version/command/atlas-kubernetes-operator-install/',
      },
    ],
  },
];
