import { isRecursiveRedirect, isVersionCatchAll, migrateEntries } from '../../../scripts/migrate-redirects';
import type { RedirectEntry } from '@/redirects/redirect-utils';

describe('migrate-redirects', () => {
  describe('isRecursiveRedirect', () => {
    it('identifies wildcard redirects where destination adds /current', () => {
      expect(
        isRecursiveRedirect({
          source: '/docs/drivers/node/:path*',
          destination: '/docs/drivers/node/current/:path*',
          statusCode: 301,
        }),
      ).toBe(true);
    });

    it('does not match bare-path redirects that insert a version slug', () => {
      expect(
        isRecursiveRedirect({
          source: '/docs/atlas/reference/api-resources-spec/',
          destination: '/docs/atlas/reference/api-resources-spec/v2/',
          statusCode: 301,
        }),
      ).toBe(false);
    });

    it('identifies identity rewrites where source and destination are identical', () => {
      expect(
        isRecursiveRedirect({
          source: '/docs/atlas/operator/upcoming/:path*',
          destination: '/docs/atlas/operator/upcoming/:path*',
          statusCode: 200,
        }),
      ).toBe(true);
    });

    it('does not match version consolidation redirects', () => {
      expect(
        isRecursiveRedirect({
          source: '/docs/drivers/node/v7.2/:path*',
          destination: '/docs/drivers/node/v7.x/:path*',
          statusCode: 301,
        }),
      ).toBe(false);
    });

    it('does not match page-specific redirects', () => {
      expect(
        isRecursiveRedirect({
          source: '/docs/drivers/node/:version/quick-start/',
          destination: '/docs/drivers/node/:version/get-started/',
          statusCode: 301,
        }),
      ).toBe(false);
    });
  });

  describe('isVersionCatchAll', () => {
    it('identifies :path* catch-all patterns that insert /current/', () => {
      expect(
        isVersionCatchAll({
          source: '/docs/drivers/node/:path*',
          destination: '/docs/drivers/node/current/:path*',
          statusCode: 301,
        }),
      ).toBe(true);
    });

    it('identifies :path* catch-all patterns that insert /upcoming/', () => {
      expect(
        isVersionCatchAll({
          source: '/docs/drivers/node/:path*',
          destination: '/docs/drivers/node/upcoming/:path*',
          statusCode: 301,
        }),
      ).toBe(true);
    });

    it('identifies :path* catch-all patterns that insert a versioned slug', () => {
      expect(
        isVersionCatchAll({
          source: '/docs/drivers/node/:path*',
          destination: '/docs/drivers/node/v6.x/:path*',
          statusCode: 301,
        }),
      ).toBe(true);
    });

    it('does not match version consolidation redirects', () => {
      expect(
        isVersionCatchAll({
          source: '/docs/drivers/node/v7.2/:path*',
          destination: '/docs/drivers/node/v7.x/:path*',
          statusCode: 301,
        }),
      ).toBe(false);
    });

    it('does not match regex catch-all entries generated by the migration', () => {
      expect(
        isVersionCatchAll({
          source: '/docs/drivers/node/:first((?!current|upcoming|v\\d)[^/]+)/:rest*',
          destination: '/docs/drivers/node/current/:first/:rest*',
          statusCode: 301,
        }),
      ).toBe(false);
    });
  });

  describe('migrateEntries', () => {
    const input: RedirectEntry[] = [
      // Version consolidation (wildcard) — kept as-is
      {
        source: '/docs/drivers/node/v7.2/:path*',
        destination: '/docs/drivers/node/v7.x/:path*',
        statusCode: 301,
      },
      // Page-specific — kept as-is
      {
        source: '/docs/drivers/node/:version/quick-start/',
        destination: '/docs/drivers/node/:version/get-started/',
        statusCode: 301,
      },
      // Explicit force from netlify.toml — preserved
      {
        source: '/docs/atlas/security/add-ip-address-to-list/',
        destination: '/docs/atlas/security/ip-access-list/',
        statusCode: 301,
        force: true,
      },
      // Version catch-all — removed and replaced with regex redirect
      {
        source: '/docs/drivers/node/:path*',
        destination: '/docs/drivers/node/current/:path*',
        statusCode: 301,
      },
      // Identity rewrite — removed with no replacement
      {
        source: '/docs/atlas/operator/upcoming/:path*',
        destination: '/docs/atlas/operator/upcoming/:path*',
        statusCode: 200,
      },
    ];

    it('removes version catch-all and recursive redirect entries', () => {
      const { removed } = migrateEntries(input);

      expect(removed).toHaveLength(2);
      expect(removed[0].source).toBe('/docs/drivers/node/:path*');
      expect(removed[1].source).toBe('/docs/atlas/operator/upcoming/:path*');
    });

    it('generates bare-path and regex replacements for version catch-all entries', () => {
      const { migrated } = migrateEntries(input);

      const barePath = migrated.find(
        (e) => e.source === '/docs/drivers/node/' && e.destination === '/docs/drivers/node/current/',
      );
      expect(barePath).toEqual({
        source: '/docs/drivers/node/',
        destination: '/docs/drivers/node/current/',
        statusCode: 301,
      });

      const regex = migrated.filter((e) => e.source.includes(':first('));
      expect(regex).toHaveLength(1);
      expect(regex[0]).toEqual({
        source: '/docs/drivers/node/:first((?!current|upcoming|v\\d)[^/]+)/:rest*',
        destination: '/docs/drivers/node/current/:first/:rest*',
        statusCode: 301,
      });
    });

    it('keeps non-recursive entries plus generated replacements', () => {
      const { migrated } = migrateEntries(input);

      // 3 kept + 2 replacements (bare-path + regex, deduped across both catch-alls)
      expect(migrated).toHaveLength(5);
    });

    it('does NOT add force: true to wildcard entries', () => {
      const { migrated } = migrateEntries(input);

      expect(migrated[0]).toEqual({
        source: '/docs/drivers/node/v7.2/:path*',
        destination: '/docs/drivers/node/v7.x/:path*',
        statusCode: 301,
      });
      expect(migrated[0].force).toBeUndefined();
    });

    it('preserves existing force: true from entries that had it in netlify.toml', () => {
      const { migrated } = migrateEntries(input);

      const forceEntry = migrated.find((e) => e.source.includes('add-ip-address-to-list'));
      expect(forceEntry?.force).toBe(true);
    });

    it('does not mutate the original input array', () => {
      const original = JSON.parse(JSON.stringify(input));
      migrateEntries(input);
      expect(input).toEqual(original);
    });

    it('deduplicates entries with identical source, destination, and statusCode', () => {
      const duped: RedirectEntry[] = [
        {
          source: '/docs/drivers/node/v7.2/:path*',
          destination: '/docs/drivers/node/v7.x/:path*',
          statusCode: 301,
        },
        {
          source: '/docs/drivers/node/v7.2/:path*',
          destination: '/docs/drivers/node/v7.x/:path*',
          statusCode: 301,
        },
      ];
      const { migrated } = migrateEntries(duped);
      expect(migrated).toHaveLength(1);
    });
  });
});
