import type { Docset } from '@/types/data';

export const mockDocsets: Docset[] = [
  {
    displayName: 'MongoDB Manual',
    project: 'docs',
    repoName: 'docs-mongodb-internal',
    internalOnly: false,
    prodDeployable: true,
    groups: null,
    branches: [
      {
        gitBranchName: 'master',
        active: true,
        urlSlug: 'upcoming',
        urlAliases: null,
        versionSelectorLabel: 'master (upcoming)',
        offlineUrl: '/offline/master',
        noIndexing: false,
      },
    ],
    prefix: {
      dotcomprd: '/docs',
      dotcomstg: '/docs',
      prd: '/docs',
      stg: '/docs',
    },
    url: {
      dev: 'https://dev.mongodb.com/docs',
      dotcomprd: 'https://mongodb.com/docs',
      dotcomstg: 'https://staging.mongodb.com/docs',
      prd: 'https://mongodb.com/docs',
      stg: 'https://staging.mongodb.com/docs',
      regression: 'https://regression.mongodb.com/docs',
    },
    bucket: {
      dev: 'docs-dev',
      dotcomprd: 'docs-prod',
      dotcomstg: 'docs-staging',
      prd: 'docs-prod',
      stg: 'docs-staging',
      regression: 'docs-regression',
    },
  },
  {
    displayName: 'MongoDB Node.js Driver',
    project: 'docs-node',
    repoName: 'docs-mongodb-internal',
    internalOnly: false,
    prodDeployable: true,
    groups: null,
    branches: [
      {
        gitBranchName: 'upcoming',
        active: true,
        urlAliases: ['upcoming'],
        urlSlug: 'upcoming',
        versionSelectorLabel: 'v4.12 (upcoming)',
        offlineUrl: '/offline/v4.12',
        noIndexing: false,
      },
      {
        gitBranchName: 'current',
        active: true,
        urlAliases: ['current'],
        urlSlug: 'current',
        versionSelectorLabel: 'v4.11 (current)',
        offlineUrl: '/offline/v4.11',
        noIndexing: false,
      },
      {
        gitBranchName: 'v4.9',
        active: true,
        urlAliases: [],
        urlSlug: 'v4.9',
        versionSelectorLabel: 'v4.9',
        offlineUrl: '/offline/v4.9',
        noIndexing: false,
      },
    ],
    prefix: {
      dotcomprd: '/docs/languages/node',
      dotcomstg: '/docs/languages/node',
      prd: '/docs/languages/node',
      stg: '/docs/languages/node',
    },
    url: {
      dev: 'https://dev.mongodb.com/docs',
      dotcomprd: 'https://mongodb.com/docs',
      dotcomstg: 'https://staging.mongodb.com/docs',
      prd: 'https://mongodb.com/docs',
      stg: 'https://staging.mongodb.com/docs',
      regression: 'https://regression.mongodb.com/docs',
    },
    bucket: {
      dev: 'docs-dev',
      dotcomprd: 'docs-prod',
      dotcomstg: 'docs-staging',
      prd: 'docs-prod',
      stg: 'docs-staging',
      regression: 'docs-regression',
    },
  },
];
