extends: existence
message: "Use descriptive link text instead of '%s'. Describe what the link leads to."
link: https://www.mongodb.com/docs/meta/style-guide/
level: error
raw:
  - '`(click here|read more|here|this link|more info|more information)\s*<https?://|\.\. \|click here\|'
