extends: existence
message: "Avoid starting a sentence with the ambiguous pronoun '%s'. Identify the specific subject."
link: 'https://www.mongodb.com/docs/meta/style-guide/writing/use-pronouns-carefully/'
level: suggestion
scope: sentence
raw:
  - '^(This|That)\b'
