extends: existence
message: "Don't use '&' to mean 'and' in prose unless quoting a UI element that shows an ampersand."
link: https://www.mongodb.com/docs/meta/style-guide/style/punctuation/#ampersands
level: warning
raw:
  - '(?<!\w)&(?!\w)'
