extends: existence
message: "Avoid anthropomorphizing software with '%s'. Use objective language (e.g., 'requires' instead of 'needs')."
link: https://www.mongodb.com/docs/meta/style-guide/writing/use-effective-verbs/#dont-humanize-inanimate-objects
level: warning
raw:
  - '\b\w+\s+(wants\s+to|wishes\s+to|likes\s+to|cares\s+about|remembers\s+your|thinks|knows\s+where|knows\s+how|knows\s+what)\b'
