extends: existence
message: "Avoid anthropomorphizing software with '%s'. Use objective language (e.g., 'requires' instead of 'needs')."
link: https://www.mongodb.com/docs/meta/style-guide/writing/use-effective-verbs/#dont-humanize-inanimate-objects
level: warning
raw:
  - '\b\w+ (wants to|wishes to|likes to|cares about|remembers your|thinks|knows where|knows how|knows what)\b'
