extends: existence
message: "Avoid future tense: '%s'. Use present tense instead."
link: 'https://www.mongodb.com/docs/meta/style-guide/writing/use-present-tense/'
level: warning
raw:
  - "(going to|will|won't) [a-zA-Z]+|[a-zA-Z]+'ll [a-zA-Z]+"
