extends: existence
message: "Avoid future tense: '%s'. Use present tense instead."
link: 'https://www.mongodb.com/docs/meta/style-guide/writing/use-present-tense/'
level: suggestion
raw:
  - '(going\s+to|will|won''t)\s+[a-zA-Z]+|[a-zA-Z]+''ll\s+[a-zA-Z]+'
