extends: existence
message: "Avoid '%s' to express uncertainty. Use 'must' for requirements, 'can' for ability, or rephrase."
link: https://www.mongodb.com/docs/meta/style-guide/writing/use-effective-verbs/#use-modal-verbs-accurately
level: error
raw:
  - '\bshould (download|appear|work|display|show|return|complete|be|run|start|stop|open|close|load|install|connect)\b'
