extends: existence
message: "Avoid '%s' as link text. Use descriptive text that identifies the destination."
link: 'https://www.mongodb.com/docs/meta/style-guide/writing/link-text/'
level: error
ignorecase: true
tokens:
  - click here
  - this link
