extends: existence
message: "Capitalize the first word after a colon in a heading: '%s'."
link: 'https://www.mongodb.com/docs/meta/style-guide/style/punctuation/#colons'
nonword: true
level: suggestion
scope: heading
# The style guide says that when a title or heading includes a colon, the
# first word after the colon is capitalized.
tokens:
  - ':\s[a-z]\w*'
