extends: existence
message: "Use the Oxford comma in '%s'."
link: 'https://www.mongodb.com/docs/meta/style-guide/style/punctuation/#commas'
level: suggestion
nonword: true
tokens:
  - '(?:[^\s,]+,){1,}\s+\w+\s+(?:and|or)\s+\w+[.?!]'
  - '(?:[\w-_` ]+,){2,}(?:[\w-_` ]+)\s+(and\s+|or\s+)'
