extends: substitution
message: "Use '%s' instead of '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/terminology/concise-terms/
level: error
ignorecase: true
swap:
  'a\s+great\s+many': many
  'a\s+number\s+of': several
  'along\s+with': with
  'are\s+able\s+to': can
  'are\s+not\s+able\s+to': cannot
  'as\s+a\s+result\s+of': because
  'as\s+long\s+as': 'if'
  'as\s+opposed\s+to': 'instead of'
  'as\s+well\s+as': and
  'at\s+the\s+current\s+time': now
  'at\s+the\s+present\s+time': now
  'at\s+the\s+point\s+where': when
  'at\s+the\s+time\s+of\s+this\s+writing': now
  'at\s+this\s+point\s+in\s+time': now
  'check\s+to\s+ensure': verify
  'despite\s+the\s+fact\s+that': although
  'did\s+not\s+run\s+successfully': failed
  'due\s+to\s+the\s+fact\s+that': because
  'during\s+the\s+process\s+of': while
  'for\s+the\s+purpose\s+of': to
  'from\s+time\s+to\s+time': periodically
  'has\s+the\s+ability\s+to': can
  'have\s+the\s+ability\s+to': can
  'in\s+between': between
  'in\s+combination\s+with': with
  'in\s+conjunction\s+with': with
  'in\s+many\s+cases': often
  'in\s+order\s+to': to
  'in\s+other\s+words': 'for example'
  'in\s+regard\s+to': about
  'in\s+spite\s+of': regardless
  'in\s+the\s+case\s+of': when
  'in\s+the\s+event\s+that': 'if'
  'inside\s+of': inside
  'is\s+able\s+to': can
  'is\s+capable\s+of': can
  'it\s+is\s+recommended': 'we recommend'
  'keep\s+in\s+mind': consider
  'leave\s+out': omit
  'make\s+use\s+of': use
  'most\s+of\s+the\s+time': usually
  'once\s+in\s+a\s+while': sometimes
  'pertaining\s+to': about
  'prior\s+to': before
  'provided\s+that': 'if'
  'provides\s+a\s+description\s+of': describes
  'quite\s+a\s+few': several
  'reach\s+out\s+to': contact
  'revert\s+back': revert
  'take\s+a\s+backup\s+of': 'back up'
  'utilize': use
  'utilization': usage
  'whether\s+or\s+not': whether
  'with\s+respect\s+to': about
  'with\s+the\s+exception\s+of': 'except for'
