extends: substitution
message: "Use '%s' instead of '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/terminology/concise-terms/
level: error
ignorecase: true
swap:
  'a great many': many
  'a number of': several
  'along with': with
  'are able to': can
  'are not able to': cannot
  'as a result of': because
  'as long as': 'if'
  'as opposed to': 'instead of'
  'as well as': and
  'at the current time': now
  'at the present time': now
  'at the point where': when
  'at the time of this writing': now
  'at this point in time': now
  'check to ensure': verify
  'despite the fact that': although
  'did not run successfully': failed
  'due to the fact that': because
  'during the process of': while
  'for the purpose of': to
  'from time to time': periodically
  'has the ability to': can
  'have the ability to': can
  'in between': between
  'in combination with': with
  'in conjunction with': with
  'in many cases': often
  'in order to': to
  'in other words': 'for example'
  'in regard to': about
  'in spite of': regardless
  'in the case of': when
  'in the event that': 'if'
  'inside of': inside
  'is able to': can
  'is capable of': can
  'it is recommended': 'we recommend'
  'keep in mind': consider
  'leave out': omit
  'make use of': use
  'most of the time': usually
  'once in a while': sometimes
  'pertaining to': about
  'prior to': before
  'provided that': 'if'
  'provides a description of': describes
  'quite a few': several
  'reach out to': contact
  'revert back': revert
  'take a backup of': 'back up'
  'utilize': use
  'utilization': usage
  'whether or not': whether
  'with respect to': about
  'with the exception of': 'except for'
