extends: substitution
message: "Use '%s' instead of '%s' when referring to versions."
link: https://www.mongodb.com/docs/meta/style-guide/style/product-names-version-numbers/
level: error
ignorecase: false
swap:
  'or higher': 'or later'
  'and higher': 'and later'
  'or lower': 'or earlier'
  'and lower': 'and earlier'
  'or older': 'or earlier'
  'and older': 'and earlier'
  'or newer': 'or later'
  'and newer': 'and later'
