extends: substitution
message: "Feel free to use '%s' instead of '%s', unless you mean to emphasize the negative."
link: 'https://www.mongodb.com/docs/meta/style-guide/style/contractions/'
level: suggestion
ignorecase: true
action:
  name: replace
swap:
  'are\s+not': aren't
  cannot: can't
  'did\s+not': didn't
  'does\s+not': doesn't
  'do\s+not': don't
  'is\s+not': isn't
  'was\s+not': wasn't
  'were\s+not': weren't
  'will\s+not': won't
  'would\s+not': wouldn't
  'could\s+not': couldn't
  'has\s+not': hasn't
  'have\s+not': haven't
  'should\s+not': shouldn't
