extends: existence
message: "Avoid the non-standard or obscure contraction '%s'. Use the full form instead."
link: https://www.mongodb.com/docs/meta/style-guide/style/contractions/
level: suggestion
ignorecase: false
tokens:
  - mustn't
  - mightn't
  - should've
  - could've
  - would've
  - that'll
  - it'll
