extends: existence
message: "Remove whitespace around '%s'."
link: 'https://www.mongodb.com/docs/meta/style-guide/style/punctuation/#dashes'
ignorecase: true
scope: sentence
nonword: true
level: suggestion
action:
  name: edit
  params:
    - remove
    - ' '
tokens:
  - '[—–]\s|\s[—–]'
