extends: existence
message: "Use one space between words and sentences."
link: 'https://www.mongodb.com/docs/meta/style-guide/style/punctuation/'
level: warning
nonword: true
tokens:
  - '(?<=[A-Za-z,;)])[.?!]?  +(?=[A-Za-z(])'
