extends: existence
message: "Avoid ellipses in documentation prose."
link: https://www.mongodb.com/docs/meta/style-guide/style/punctuation/
level: suggestion
nonword: true
tokens:
  - '\.\.\.'
  - '…'
