extends: existence
message: "Avoid '%s'. Rewrite to lead with the subject."
link: 'https://www.mongodb.com/docs/meta/style-guide/writing/write-clear-concise-sentences-paragraphs/'
level: suggestion
nonword: true
tokens:
  - 'There is\b'
  - 'There are\b'
  - 'There was\b'
  - 'There were\b'
  - "There's\b"
  - 'It is\b'
  - 'It was\b'
  - "It's\b"
