extends: existence
message: "Use gender-neutral pronouns (they/them/their) instead of '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/writing/use-gender-neutral-pronouns/
level: error
ignorecase: true
raw:
  - '\b(he/she|she/he|s/he|him/her|her/him|his/her|her/his|\(s\)he|he or she|she or he|his or her|her or his|him or her)\b'
