extends: existence
message: "Use gender-neutral pronouns (they/them/their) instead of '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/writing/use-gender-neutral-pronouns/
level: error
ignorecase: true
raw:
  - '\b(he/she|she/he|s/he|him/her|her/him|his/her|her/his|\(s\)he|he\s+or\s+she|she\s+or\s+he|his\s+or\s+her|her\s+or\s+his|him\s+or\s+her)\b'
