extends: substitution
message: "Avoid idioms and colloquialisms. Use '%s' instead of '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/terminology/terms-for-global-audience/#dont-use-idioms-or-colloquialisms
level: warning
ignorecase: true
swap:
  'in a nutshell': briefly
  'the bottom line': 'in summary'
  'across the board': universally
  'on the fly': dynamically
  'for the most part': generally
  'keep an eye out for': 'look for'
  'get a feel for': 'become familiar with'
  'in light of': 'because of'
  'kind of like': 'similar to'
  'lots of': many
  "what's more": moreover
  'sanity check': 'test or evaluate'
  'spin up': create
  'fire up': start
  'grayed out': unavailable
  'grayed-out': unavailable
