extends: substitution
message: "Avoid metaphors. Use '%s' instead of '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/terminology/terms-for-global-audience/#avoid-metaphorical-terms
level: error
ignorecase: true
swap:
  'a\s+handful\s+of': 'a few'
  'the\s+vanilla\s+model': 'the standard model'
  'the\s+vanilla\s+option': 'the standard option'
  'common\s+pitfalls': 'common problems'
