extends: substitution
message: "Avoid idioms and colloquialisms. Use '%s' instead of '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/terminology/terms-for-global-audience/#dont-use-idioms-or-colloquialisms
level: warning
ignorecase: true
swap:
  'in\s+a\s+nutshell': briefly
  'the\s+bottom\s+line': 'in summary'
  'across\s+the\s+board': universally
  'on\s+the\s+fly': dynamically
  'for\s+the\s+most\s+part': generally
  'keep\s+an\s+eye\s+out\s+for': 'look for'
  'get\s+a\s+feel\s+for': 'become familiar with'
  'in\s+light\s+of': 'because of'
  'kind\s+of\s+like': 'similar to'
  'lots\s+of': many
  'what''s\s+more': moreover
  'sanity\s+check': 'test or evaluate'
  'spin\s+up': create
  'fire\s+up': start
  'grayed\s+out': unavailable
  'grayed-out': unavailable
