extends: substitution
message: "Use non-oppressive language. Replace '%s' with '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/terminology/terms-for-global-audience/#use-non-oppressive-language
level: warning
ignorecase: true
swap:
  'blacklist': blocklist
  'whitelist': allowlist
  'black hat': unethical
  'white hat': ethical
  'master/slave': primary/secondary
