extends: substitution
message: "Avoid metaphors. Use '%s' instead of '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/terminology/terms-for-global-audience/#avoid-metaphorical-terms
level: error
ignorecase: true
swap:
  'a handful of': 'a few'
  'the vanilla model': 'the standard model'
  'the vanilla option': 'the standard option'
  'common pitfalls': 'common problems'
