extends: existence
message: "Usually words with the prefix self- ('%s') are hyphenated."
link: 'https://www.mongodb.com/docs/meta/style-guide/terminology/alphabetical-terms/'
ignorecase: true
level: error
action:
  name: convert
  params:
    - simple
tokens:
  - 'self\w+'
