extends: substitution
message: "Prefer positive language. Use '%s' instead of '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/writing/use-positive-statements/#avoid-negative-words
level: error
ignorecase: true
swap:
  'catastrophic': serious
  'fatal error': 'serious error'
  'fatal failure': 'serious failure'
  'will damage': 'will affect'
  'can damage': 'can affect'
