extends: existence
message: "Use numerals for '%s'. Spell out only zero through nine."
link: 'https://www.mongodb.com/docs/meta/style-guide/style/numbers/'
level: suggestion
ignorecase: true
tokens:
  - \bten\b
  - \beleven\b
  - \btwelve\b
  - \bthirteen\b
  - \bfourteen\b
  - \bfifteen\b
  - \bsixteen\b
  - \bseventeen\b
  - \beighteen\b
  - \bnineteen\b
  - \btwenty\b
  - \bthirty\b
  - \bforty\b
  - \bfifty\b
  - \bsixty\b
  - \bseventy\b
  - \beighty\b
  - \bninety\b
