extends: existence
message: "Don't follow a spelled-out number with a numeral in parentheses: '%s'."
link: 'https://www.mongodb.com/docs/meta/style-guide/style/numbers/'
level: warning
ignorecase: true
nonword: true
tokens:
  - '\b(?:one|two|three|four|five|six|seven|eight|nine|ten)\s+\(\d+\)'
