extends: existence
message: "Use '%s' without an apostrophe to form the plural or attributive."
link: 'https://www.mongodb.com/docs/meta/style-guide/style/plurals/'
level: error
raw:
  - \b[A-Z]{2,}'s\b
