extends: existence
message: "Incorrect MongoDB product name usage: '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/style/product-names-version-numbers/
level: error
ignorecase: false
tokens:
  - "MongoDB's"
  - MongoDb
  - mongoDB
  - Mongodb
  - 'MONGODB(?!-)'
  - "Atlas's"
  - "Compass's"
  - "Realm's"
  - 'Ops\s+Manager''s'
  - 'Cloud\s+Manager''s'
  - 'BI\s+Connector''s'
  - 'Spark\s+Connector''s'
