extends: existence
message: "Incorrect MongoDB product name usage: '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/style/product-names-version-numbers/
level: error
ignorecase: false
tokens:
  - "MongoDB's"
  - MongoDb
  - mongoDB
  - Mongodb
  - MONGODB
  - "Atlas's"
  - "Compass's"
  - "Realm's"
  - "Ops Manager's"
  - "Cloud Manager's"
  - "BI Connector's"
  - "Spark Connector's"
