extends: existence
message: "Avoid semicolons. Break into separate sentences or use a list instead."
link: https://www.mongodb.com/docs/meta/style-guide/style/punctuation/#semicolons
level: suggestion
raw:
  - ';'
