extends: occurrence
message: "This sentence has %s words. Keep sentences to 25 words or fewer."
link: https://www.mongodb.com/docs/meta/style-guide/writing/write-clear-concise-sentences-paragraphs/#restrict-sentence-length
level: suggestion
scope: sentence
max: 25
token: \b\w+\b
