extends: existence
message: "Avoid single quotes in documentation prose. Use double quotes or rephrase."
link: https://www.mongodb.com/docs/meta/style-guide/style/punctuation/
level: suggestion
raw:
  - '\s''[a-zA-Z]'
