extends: existence
message: "Avoid slashes in prose. Use 'or' instead of '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/style/punctuation/#slashes
level: suggestion
ignorecase: true
tokens:
  - and/or
  - or/and
