extends: existence
message: "If this is a restrictive clause, use 'that' instead of 'which'. If it's nonrestrictive, add a comma before 'which'."
link: 'https://www.mongodb.com/docs/meta/style-guide/writing/use-that-which-correctly/'
level: suggestion
nonword: true
tokens:
  - '\w+\s+which\b'
