extends: existence
message: "Use 'AM' or 'PM' with a space and no periods, and use 'midnight' or 'noon' for 12 AM or 12 PM, not '%s'."
link: 'https://www.mongodb.com/docs/meta/style-guide/style/time/'
level: warning
nonword: true
tokens:
  - '\b\d{1,2}(?::\d{2})?\s*[AaPp]\.[Mm]\.'
  - '\b\d{1,2}(?::\d{2})?(?:AM|PM)\b'
  - '\b12(?::00)?\s+(?:AM|PM)\b'
