extends: existence
message: "Don't end a heading with '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/style/titles-and-headings/#general-style-and-structure
level: error
scope: heading
raw:
  - '[.:]$'
