extends: existence
message: "Add a space between the number and the unit in '%s'."
link: 'https://www.mongodb.com/docs/meta/style-guide/style/numbers/'
level: error
nonword: true
tokens:
  - '\b\d+(?:\.\d+)?(?:KB|MB|GB|TB|PB|KiB|MiB|GiB|TiB|Mbps|Gbps)\b'
