extends: existence
message: "Put the product name before the version number in '%s', or use a version directive."
link: 'https://www.mongodb.com/docs/meta/style-guide/style/version/'
level: suggestion
nonword: true
tokens:
  - '\b(?:[Ss]tarting|[Bb]eginning)\s+(?:in|with)\s+(?:version\s+)?\d+\.\d+(?:\.\d+)?\b'
  - '\b(?:in|In)\s+version\s+\d+\.\d+(?:\.\d+)?\b'
