extends: substitution
message: "Simplify the nominalization. Use '%s' instead of '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/writing/use-effective-verbs/#avoid-nouns-built-from-verbs
level: error
ignorecase: true
swap:
  'provides a description of': describes
  'perform an installation': install
  'perform the installation': install
  'perform a configuration': configure
  'perform the configuration': configure
  'enables the encryption of': encrypts
  'perform a backup of': 'back up'
  'perform a backup': back up
  'make a determination': determine
  'make a recommendation': recommend
  'provides an implementation of': implements
  'gives an indication of': indicates
  'provides a summary of': summarizes
  'perform a review of': review
  'provides a list of': lists
  'contains a list of': lists
