extends: substitution
message: "Simplify the nominalization. Use '%s' instead of '%s'."
link: https://www.mongodb.com/docs/meta/style-guide/writing/use-effective-verbs/#avoid-nouns-built-from-verbs
level: error
ignorecase: true
swap:
  'provides\s+a\s+description\s+of': describes
  'perform\s+an\s+installation': install
  'perform\s+the\s+installation': install
  'perform\s+a\s+configuration': configure
  'perform\s+the\s+configuration': configure
  'enables\s+the\s+encryption\s+of': encrypts
  'perform\s+a\s+backup\s+of': 'back up'
  'perform\s+a\s+backup': back up
  'make\s+a\s+determination': determine
  'make\s+a\s+recommendation': recommend
  'provides\s+an\s+implementation\s+of': implements
  'gives\s+an\s+indication\s+of': indicates
  'provides\s+a\s+summary\s+of': summarizes
  'perform\s+a\s+review\s+of': review
  'provides\s+a\s+list\s+of': lists
  'contains\s+a\s+list\s+of': lists
