import { defineDocset } from "../define";

export default defineDocset({
	project: "atlas-cli",
	displayName: "Atlas CLI",
	prefix: "docs/atlas/cli",
	search: { categoryTitle: "Atlas CLI" },
	versions: [
		{ name: "upcoming" },
		{ name: "current", label: "current (v1.58.3)", stable: true },
		{ name: "v1.57" },
		{ name: "v1.56" },
		{ name: "v1.55" },
		{ name: "v1.54" },
		{ name: "v1.53", active: false, eol: "download" },
		{ name: "v1.52", active: false, eol: "download" },
		{ name: "v1.51", active: false, eol: "download" },
		{ name: "v1.50", active: false, eol: "download" },
		{ name: "v1.49", active: false, eol: "download" },
		{ name: "v1.48", active: false, eol: "download" },
		{ name: "v1.47", active: false, eol: "download" },
		{ name: "v1.46", active: false, eol: "download" },
		{ name: "v1.45", active: false, eol: "download" },
		{ name: "v1.44", active: false, eol: "download" },
		{ name: "v1.43", active: false, eol: "download" },
		{ name: "v1.42", active: false, eol: "download" },
		{ name: "v1.41", active: false, eol: "download" },
		{ name: "v1.40", active: false, eol: "download" },
		{ name: "v1.39", active: false, eol: "download" },
		{ name: "v1.38", label: "1.38", active: false, eol: "download" },
		{ name: "v1.37", active: false, eol: "download" },
		{ name: "v1.36", active: false, eol: "download" },
		{ name: "v1.35", active: false, eol: "download" },
		{ name: "v1.34", active: false, eol: "download" },
		{ name: "v1.33", active: false, eol: "download" },
		{ name: "v1.32", active: false, eol: "download" },
		{ name: "v1.31", active: false, eol: "download" },
		{ name: "v1.30", active: false, eol: "download" },
		{ name: "v1.29", active: false, eol: "download" },
		{ name: "v1.28", label: "1.28", active: false, eol: "download" },
		{ name: "v1.27", label: "1.27", active: false, eol: "download" },
		{ name: "v1.26", label: "1.26", active: false, eol: "download" },
		{ name: "v1.25", label: "1.25", active: false, eol: "download" },
		{ name: "v1.24", label: "1.24", active: false, eol: "download" },
		{ name: "v1.23", label: "1.23", active: false, eol: "download" },
		{ name: "v1.22", label: "1.22", active: false, eol: "download" },
		{ name: "v1.21", label: "1.21", active: false, eol: "download" },
		{ name: "v1.20", label: "1.20", active: false, eol: "download" },
		{ name: "v1.19", label: "1.19", active: false, eol: "download" },
		{ name: "v1.18", label: "1.18", active: false, eol: "download" },
		{ name: "v1.17", label: "1.17", active: false, eol: "download" },
		{ name: "v1.16", label: "1.16", active: false, eol: "download" },
		{ name: "v1.15", label: "1.15", active: false, eol: "download" },
		{ name: "v1.14", label: "1.14", active: false, eol: "download" },
		{ name: "v1.13", label: "1.13", active: false, eol: "download" },
		{ name: "v1.12", label: "1.12", active: false, eol: "download" },
		{ name: "v1.11", label: "1.11", active: false, eol: "download" },
		{ name: "v1.10", active: false, eol: "download" },
		{ name: "v1.9", active: false, eol: "download" },
		{ name: "v1.8", active: false, eol: "download" },
		{ name: "v1.7", active: false, eol: "download" },
		{ name: "v1.6", active: false, eol: "download" },
		{ name: "v1.5", active: false, eol: "download" },
		{ name: "v1.4", label: "1.4", active: false },
		{ name: "v1.3", label: "1.3", active: false },
		{ name: "v1.2", label: "1.2", active: false },
		{ name: "v1.1", label: "1.1", active: false },
		{ name: "v1.0", label: "1.0", active: false },
	],
});
