import { defineDocset } from "../define";

export default defineDocset({
	project: "docs-k8s-operator",
	displayName: "Kubernetes Operator",
	prefix: "docs/kubernetes-operator",
	search: { categoryTitle: "Kubernetes Operator" },
	versions: [
		{ name: "v1.33", label: "Version v1.33", active: false, stable: true, eol: "download" },
		{ name: "v1.32", label: "Version 1.32", active: false, eol: "download" },
		{ name: "v1.31", label: "Version 1.31", active: false, eol: "download" },
		{ name: "v1.30", label: "Version 1.30", active: false, eol: "download" },
		{ name: "v1.29", label: "Version 1.29", active: false, eol: "download" },
		{ name: "v1.28", label: "Version 1.28", active: false, eol: "download" },
		{ name: "v1.27", label: "Version 1.27", active: false, eol: "download" },
		{ name: "v1.26", label: "Version 1.26", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.26.tar.gz" },
		{ name: "v1.25", label: "Version 1.25", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.25.tar.gz" },
		{ name: "v1.24", label: "Version 1.24", active: false, eol: "download" },
		{ name: "v1.23", label: "Version 1.23", active: false, eol: "download" },
		{ name: "v1.22", label: "Version 1.22", active: false, eol: "download" },
		{ name: "v1.21", label: "Version 1.21", active: false, eol: "download" },
		{ name: "v1.20", label: "Version 1.20", active: false, eol: "download" },
		{ name: "v1.19", label: "Version 1.19", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.19.tar.gz" },
		{ name: "v1.18", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.18.tar.gz" },
		{ name: "v1.17", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.17.tar.gz" },
		{ name: "v1.16", label: "Version 1.16", active: false, offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.16.tar.gz" },
		{ name: "v1.15", label: "Version 1.15", active: false, offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.15.tar.gz" },
		{ name: "v1.14", label: "Version 1.14", active: false, offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.14.tar.gz" },
		{ name: "v1.13", label: "Version 1.13", active: false, offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.13.tar.gz" },
		{ name: "v1.12", label: "Version 1.12", active: false, offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.12.tar.gz" },
		{ name: "v1.11", label: "Version 1.11", active: false, offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.11.tar.gz" },
		{ name: "v1.10", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.10.tar.gz" },
		{ name: "v1.9", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.9.tar.gz" },
		{ name: "v1.8", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.8.tar.gz" },
		{ name: "v1.7", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.7.tar.gz" },
		{ name: "v1.6", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.6.tar.gz" },
		{ name: "v1.5", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.5.tar.gz" },
		{ name: "v1.4", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.4.tar.gz" },
		{ name: "v1.3", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.3.tar.gz" },
		{ name: "v1.2", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.2.tar.gz" },
		{ name: "v1.1", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.1.tar.gz" },
		{ name: "v0.12", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v0.12.tar.gz" },
		{ name: "v0.11", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v0.11.tar.gz" },
		{ name: "v0.10", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v0.10.tar.gz" },
		{ name: "v0.8", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v0.8.tar.gz" },
		{ name: "v0.9", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v0.9.tar.gz" },
		{ name: "v1.0", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/docs-k8s-operator-v1.0.tar.gz" },
	],
});
