import { defineDocset } from "../define";

export default defineDocset({
	project: "docs",
	displayName: "MongoDB Manual",
	prefix: "docs",
	search: { categoryTitle: "MongoDB Manual", categoryName: "manual" },
	groups: [
		{ groupLabel: "Major Release", includedVersions: ["manual", "v8.0", "v7.0"] },
		{ groupLabel: "Minor Release", includedVersions: ["upcoming", "v8.3"] },
	],
	versions: [
		{ name: "upcoming", label: "9.1 (Upcoming)", noIndexing: true },
		{ name: "manual", label: "9.0 (Current)", stable: true },
		{ name: "v8.3", label: "8.3" },
		{ name: "rapid", label: "8.1", active: false, noIndexing: true, eol: "download" },
		{ name: "v8.2", label: "8.2", active: false, eol: "download" },
		{ name: "v8.0", label: "8.0" },
		{ name: "v7.3", label: "7.3", active: false, eol: "download" },
		{ name: "v7.2", label: "7.2", active: false, eol: "download" },
		{ name: "v7.1", label: "7.1", active: false, eol: "download" },
		{ name: "v7.0", label: "7.0" },
		{ name: "v6.3", label: "6.3", active: false, eol: "download" },
		{ name: "v6.2", label: "6.2", active: false, eol: "download" },
		{ name: "v6.0", label: "6.0", active: false, eol: "download" },
		{ name: "v5.0", label: "5.0", active: false, eol: "download" },
		{ name: "v4.4", label: "4.4", active: false, eol: "download" },
		{ name: "v4.2", label: "4.2", active: false, eol: "download" },
		{ name: "v6.1", active: false, eol: "download" },
		{ name: "v5.3", active: false, eol: "download" },
		{ name: "v5.2", active: false, eol: "download" },
		{ name: "v5.1", active: false, eol: "download" },
		{ name: "v4.0", active: false, eol: "download" },
		{ name: "v3.6", label: "3.6", active: false, eol: "download" },
		{ name: "v3.4", label: "3.4", active: false, eol: "download" },
		{ name: "v3.2", label: "3.2", active: false, eol: "download" },
		{ name: "v3.0", label: "3.0", active: false, eol: "download" },
		{ name: "v2.6", label: "2.6", active: false, eol: "download" },
		{ name: "v2.4", label: "2.4", active: false, eol: "download" },
		{ name: "v2.2", label: "2.2", active: false, eol: "download" },
	],
});
