import { defineDocset } from "../define";

export default defineDocset({
	project: "mongocli",
	displayName: "MongoDB CLI",
	prefix: "docs/mongocli",
	search: { categoryTitle: "MongoDB CLI" },
	versions: [
		{ name: "upcoming", label: "2.1 (upcoming)", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-upcoming.tar.gz" },
		{ name: "current", label: "2.0.9 (current)", stable: true },
		{ name: "v1.31", label: "1.31", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.31.tar.gz" },
		{ name: "v1.30", label: "1.30", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.30.tar.gz" },
		{ name: "v1.29", label: "1.29", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.29.tar.gz" },
		{ name: "v1.28", label: "1.28", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.28.tar.gz" },
		{ name: "v1.27", label: "1.27", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.27.tar.gz" },
		{ name: "v1.26", label: "1.26", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.26.tar.gz" },
		{ name: "v1.25", label: "1.25", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.25.tar.gz" },
		{ name: "v1.24", label: "1.24", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.24.tar.gz" },
		{ name: "v1.23", label: "1.23", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.23.tar.gz" },
		{ name: "v1.22", label: "1.22", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.22.tar.gz" },
		{ name: "v1.21", label: "1.21", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.21.tar.gz" },
		{ name: "v1.20", label: "1.20", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.20.tar.gz" },
		{ name: "v1.19", label: "1.19", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.19.tar.gz" },
		{ name: "v1.18", label: "1.18", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.18.tar.gz" },
		{ name: "v1.17", label: "1.17", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.17.tar.gz" },
		{ name: "v1.16", label: "1.16", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.16.tar.gz" },
		{ name: "v1.15", label: "1.15", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.15.tar.gz" },
		{ name: "v1.14", label: "1.14", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.14.tar.gz" },
		{ name: "v1.13", label: "1.13", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.13.tar.gz" },
		{ name: "v1.12", label: "1.12", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.12.tar.gz" },
		{ name: "v1.11", label: "1.11", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.11.tar.gz" },
		{ name: "v1.10", label: "1.10", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.10.tar.gz" },
		{ name: "v1.9", label: "1.9", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.9.tar.gz" },
		{ name: "v1.8", label: "1.8", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.8.tar.gz" },
		{ name: "v1.7", label: "1.7", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.7.tar.gz" },
		{ name: "v1.6", label: "1.6", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.6.tar.gz" },
		{ name: "v1.5", label: "1.5", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.5.tar.gz" },
		{ name: "v1.4.0", label: "1.4", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.4.0.tar.gz" },
		{ name: "v1.3.0", label: "1.3", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.3.0.tar.gz" },
		{ name: "v1.2.0", label: "1.2", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.2.0.tar.gz" },
		{ name: "v1.1.0", label: "1.1", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.1.0.tar.gz" },
		{ name: "v1.0.0", label: "1.0", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v1.0.0.tar.gz" },
		{ name: "v0.5.0", label: "0.5.0", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v0.5.0.tar.gz" },
		{ name: "v0.0.4", label: "0.0.4", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v0.0.4.tar.gz" },
		{ name: "v0.0.3", label: "0.0.3", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v0.0.3.tar.gz" },
		{ name: "v0.2.0", label: "0.2.0", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v0.2.0.tar.gz" },
		{ name: "v0.1.0", label: "0.1.0", active: false, eol: "download", offlineUrl: "https://www.mongodb.com/docs/offline/mongocli-v0.1.0.tar.gz" },
	],
});
