import { defineDocset } from "../define";

export default defineDocset({
	project: "node",
	displayName: "Node.js Driver",
	prefix: "docs/drivers/node",
	search: { categoryTitle: "Node.js Driver" },
	versions: [
		{ name: "upcoming", noIndexing: true },
		{ name: "current", label: "v7.x (current)", stable: true },
		{ name: "v6.x" },
		{ name: "v6.20", active: false },
		{ name: "v6.19", active: false },
		{ name: "v6.18", active: false },
		{ name: "v6.17", active: false },
		{ name: "v6.16", active: false },
		{ name: "v6.15", active: false },
		{ name: "v6.14", active: false },
		{ name: "v6.13", active: false },
		{ name: "v6.12", active: false, eol: "download" },
		{ name: "v6.11", active: false, eol: "download" },
		{ name: "v6.10", active: false, eol: "download" },
		{ name: "v6.9", active: false, eol: "download" },
		{ name: "v6.8", active: false, eol: "download" },
		{ name: "v6.7", active: false, eol: "download" },
		{ name: "v6.6", active: false, eol: "download" },
		{ name: "v6.5", active: false, eol: "download" },
		{ name: "v6.4", active: false, eol: "download" },
		{ name: "v6.3", active: false, eol: "download" },
		{ name: "v6.2", active: false, eol: "download" },
		{ name: "v6.1", active: false, eol: "download" },
		{ name: "v6.0", active: false, eol: "download" },
		{ name: "v5.9", active: false, eol: "download" },
		{ name: "v5.8", active: false, eol: "download" },
		{ name: "v5.7", active: false, eol: "download" },
		{ name: "v5.6", active: false, eol: "download" },
		{ name: "v5.5", active: false, eol: "download" },
		{ name: "v5.4", active: false, eol: "download" },
		{ name: "v5.3", active: false, eol: "download" },
		{ name: "v5.2", active: false, eol: "download" },
		{ name: "v5.1", active: false, eol: "download" },
		{ name: "v5.0", active: false, eol: "download" },
		{ name: "v4.17", active: false, eol: "download" },
		{ name: "v4.16", active: false, eol: "download" },
		{ name: "v4.15", active: false, eol: "download" },
		{ name: "v4.14", active: false, eol: "download" },
		{ name: "v4.13", active: false, eol: "download" },
		{ name: "v4.12", active: false, eol: "download" },
		{ name: "v4.11", active: false, eol: "download" },
		{ name: "v4.10", active: false, eol: "download" },
		{ name: "v4.9", active: false, eol: "download" },
		{ name: "v4.8", active: false, eol: "download" },
		{ name: "v4.7", active: false, eol: "download" },
		{ name: "v4.6", active: false, eol: "download" },
		{ name: "v4.5", active: false, eol: "download" },
		{ name: "v4.4", active: false, eol: "download" },
		{ name: "v4.3", active: false, eol: "download" },
		{ name: "v4.2", active: false, eol: "download" },
		{ name: "v4.1", active: false, eol: "download" },
		{ name: "v4.0", active: false, eol: "download" },
		{ name: "v3.7", active: false, eol: "download" },
		{ name: "v3.6", active: false, eol: "download" },
	],
});
