import { defineDocset } from "../define";

export default defineDocset({
	project: "ruby-driver",
	displayName: "Ruby Driver",
	prefix: "docs/ruby-driver",
	search: { categoryTitle: "Ruby Driver", categoryName: "docs-ruby" },
	versions: [
		{ name: "upcoming", noIndexing: true },
		{ name: "current", label: "v2.x (current)", stable: true },
		{ name: "v2.22", active: false },
		{ name: "v2.21", active: false, eol: "download" },
		{ name: "v2.20", active: false, eol: "download" },
		{ name: "v2.19", label: "Version 2.19", active: false, eol: "download" },
		{ name: "v2.18", label: "Version 2.18", active: false, eol: "download" },
		{ name: "v2.17", label: "Version 2.17", active: false, eol: "download" },
		{ name: "v2.16", label: "Version 2.16", active: false, eol: "download" },
		{ name: "v2.15", label: "Version 2.15", active: false, eol: "download" },
		{ name: "v2.14", label: "Version 2.14", active: false, eol: "download" },
		{ name: "v2.13", label: "Version 2.13", active: false, eol: "download" },
		{ name: "v2.12", label: "Version 2.12", active: false, eol: "download" },
		{ name: "v2.11", label: "Version 2.11", active: false, eol: "download" },
		{ name: "v2.10", label: "Version 2.10", active: false, eol: "download" },
		{ name: "v2.9", label: "Version 2.9", active: false, eol: "download" },
		{ name: "v2.8", label: "Version 2.8", active: false, eol: "download" },
		{ name: "v2.7", label: "Version 2.7", active: false, eol: "download" },
		{ name: "v2.6", label: "Version 2.6", active: false, eol: "download" },
		{ name: "v2.5", label: "Version 2.5", active: false, eol: "download" },
		{ name: "v2.4", label: "Version 2.4", active: false, eol: "download" },
		{ name: "v2.3", label: "Version 2.3", active: false, eol: "download" },
		{ name: "v2.2", label: "Version 2.2", active: false, eol: "download" },
		{ name: "v2.0", label: "Version 2.0", active: false, eol: "download" },
		{ name: "v1.x", label: "Version 1.x", active: false, eol: "download" },
	],
});
