# Curl commands from makefile

curl -SfL https://raw.githubusercontent.com/mongodb/mongo-python-driver/master/test/test_examples.py -o $(pwd)/curl_examples/test_examples.py
curl -SfL https://raw.githubusercontent.com/mongodb/motor/master/test/asyncio_tests/test_examples.py -o $(pwd)/curl_examples/test_examples_motor.py
curl -SfL https://raw.githubusercontent.com/mongodb/mongo-perl-driver/master/t/examples/driver-examples.t -o $(pwd)/curl_examples/driver-examples.t
curl -SfL https://raw.githubusercontent.com/mongodb/mongo-php-library/master/tests/DocumentationExamplesTest.php -o $(pwd)/curl_examples/DocumentationExamplesTest.php
curl -SfL https://raw.githubusercontent.com/mongodb/mongo-java-driver/master/driver-sync/src/examples/documentation/DocumentationSamples.java -o $(pwd)/curl_examples/DocumentationSamples.java
curl -SfL https://raw.githubusercontent.com/mongodb/node-mongodb-native/2.2/test/functional/examples_tests.js -o $(pwd)/curl_examples/examples_tests.js
curl -SfL https://raw.githubusercontent.com/mongodb/mongo-ruby-driver/master/spec/integration/shell_examples_spec.rb -o $(pwd)/curl_examples/shell_examples_spec.rb
curl -SfL https://raw.githubusercontent.com/mongodb/mongo-ruby-driver/master/spec/integration/change_stream_examples_spec.rb -o $(pwd)/curl_examples/change_stream_examples_spec.rb
curl -SfL https://raw.githubusercontent.com/mongodb/mongo-scala-driver/master/driver/src/it/scala/org/mongodb/scala/DocumentationExampleSpec.scala -o $(pwd)/curl_examples/DocumentationExampleSpec.scala
curl -SfL https://raw.githubusercontent.com/mongodb/mongo-csharp-driver/master/tests/MongoDB.Driver.Examples/DocumentationExamples.cs -o $(pwd)/curl_examples/DocumentationExamples.cs
curl -SfL https://raw.githubusercontent.com/mongodb/mongo-csharp-driver/master/tests/MongoDB.Driver.Examples/ChangeStreamExamples.cs -o $(pwd)/curl_examples/ChangeStreamExamples.cs
#curl -SfL https://raw.githubusercontent.com/mongodb/mongo-c-driver/master/tests/test-mongoc-sample-commands.c -o $(pwd)/curl_examples/test-mongoc-sample-commands.c
curl -SfL https://raw.githubusercontent.com/mongodb/mongo-go-driver/master/examples/documentation_examples/examples.go -o $(pwd)/curl_examples/examples.go
curl -SfL https://raw.githubusercontent.com/mongodb/mongo-java-driver-reactivestreams/master/examples/documentation/src/DocumentationSamples.java -o $(pwd)/curl_examples/AsyncDocumentationSamples.java
curl -Sfl https://raw.githubusercontent.com/skerschb/testauth/react_stitch_google/src/index.js -o $(pwd)/curl_examples/react_stitch_google.js
curl -Sfl https://raw.githubusercontent.com/mongodb/mongo-go-driver/master/examples/documentation_examples/examples.go -o $(pwd)/curl_examples/examples.go	
curl -SfL https://raw.githubusercontent.com/skerschb/testauth/master/src/index.js -o $(pwd)/curl_examples/react_stitch_google.js
