[mcp_servers.mongodb]
command = "npx"
args = [ "-y", "mongodb-mcp-server@latest", "--readOnly" ]

[mcp_servers.mongodb.env]
MDB_MCP_API_CLIENT_ID = "<client-id>"
MDB_MCP_API_CLIENT_SECRET = "<client-secret>"