[
  {
    _id: ObjectId('573a1390f29313caabcd42e8'),
    plot: 'A group of bandits stage a brazen train hold-up, only to find a determined posse hot on their heels.',
    genres: [ 'Short', 'Western' ],
    runtime: 11,
    cast: [
      'A.C. Abadie',
      "Gilbert M. 'Broncho Billy' Anderson",
      'George Barnes',
      'Justus D. Barnes'
    ],
    poster: 'https://m.media-amazon.com/images/M/MV5BMTU3NjE5NzYtYTYyNS00MDVmLWIwYjgtMmYwYWIxZDYyNzU2XkEyXkFqcGdeQXVyNzQzNzQxNzI@._V1_SY1000_SX677_AL_.jpg',
    title: 'The Great Train Robbery',
    fullplot: "Among the earliest existing films in American cinema - notable as the first film that presented a narrative story to tell - it depicts a group of cowboy outlaws who hold up a train and rob the passengers. They are then pursued by a Sheriff's posse. Several scenes have color included - all hand tinted.",
    languages: [ 'English' ],
    released: ISODate('1903-12-01T00:00:00.000Z'),
    directors: [ 'Edwin S. Porter' ],
    rated: 'TV-G',
    awards: { wins: 1, nominations: 0, text: '1 win.' },
    lastupdated: '2015-08-13 00:27:59.177000000',
    year: 1903,
    imdb: { rating: 7.4, votes: 9847, id: 439 },
    countries: [ 'USA' ],
    type: 'movie',
    tomatoes: {
      viewer: { rating: 3.7, numReviews: 2559, meter: 75 },
      fresh: 6,
      critic: { rating: 7.6, numReviews: 6, meter: 100 },
      rotten: 0,
      lastUpdated: ISODate('2015-08-08T19:16:10.000Z')
    },
    num_mflix_comments: 0
  },
  {
    _id: ObjectId('573a1390f29313caabcd446f'),
    plot: "A greedy tycoon decides, on a whim, to corner the world market in wheat. This doubles the price of bread, forcing the grain's producers into charity lines and further into poverty. The film...",
    genres: [ 'Short', 'Drama' ],
    runtime: 14,
    cast: [
      'Frank Powell',
      'Grace Henderson',
      'James Kirkwood',
      'Linda Arvidson'
    ],
    num_mflix_comments: 1,
    title: 'A Corner in Wheat',
    fullplot: "A greedy tycoon decides, on a whim, to corner the world market in wheat. This doubles the price of bread, forcing the grain's producers into charity lines and further into poverty. The film continues to contrast the ironic differences between the lives of those who work to grow the wheat and the life of the man who dabbles in its sale for profit.",
    languages: [ 'English' ],
    released: ISODate('1909-12-13T00:00:00.000Z'),
    directors: [ 'D.W. Griffith' ],
    rated: 'G',
    awards: { wins: 1, nominations: 0, text: '1 win.' },
    lastupdated: '2015-08-13 00:46:30.660000000',
    year: 1909,
    imdb: { rating: 6.6, votes: 1375, id: 832 },
    countries: [ 'USA' ],
    type: 'movie',
    tomatoes: {
      viewer: { rating: 3.6, numReviews: 109, meter: 73 },
      lastUpdated: ISODate('2015-05-11T18:36:53.000Z')
    }
  },
  {
    _id: ObjectId('573a1390f29313caabcd4eaf'),
    plot: 'A woman, with the aid of her police officer sweetheart, endeavors to uncover the prostitution ring that has kidnapped her sister, and the philanthropist who secretly runs it.',
    genres: [ 'Crime', 'Drama' ],
    runtime: 88,
    cast: [ 'Jane Gail', 'Ethel Grandin', 'William H. Turner', 'Matt Moore' ],
    num_mflix_comments: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BYzk0YWQzMGYtYTM5MC00NjM2LWE5YzYtMjgyNDVhZDg1N2YzXkEyXkFqcGdeQXVyMzE0MjY5ODA@._V1_SY1000_SX677_AL_.jpg',
    title: 'Traffic in Souls',
    lastupdated: '2015-09-15 02:07:14.247000000',
    languages: [ 'English' ],
    released: ISODate('1913-11-24T00:00:00.000Z'),
    directors: [ 'George Loane Tucker' ],
    rated: 'TV-PG',
    awards: { wins: 1, nominations: 0, text: '1 win.' },
    year: 1913,
    imdb: { rating: 6, votes: 371, id: 3471 },
    countries: [ 'USA' ],
    type: 'movie',
    tomatoes: {
      viewer: { rating: 3, numReviews: 85, meter: 57 },
      dvd: ISODate('2008-08-26T00:00:00.000Z'),
      lastUpdated: ISODate('2015-08-10T18:33:55.000Z')
    }
  },
  {
    _id: ObjectId('573a1390f29313caabcd56df'),
    plot: 'An immigrant leaves his sweetheart in Italy to find a better life across the sea in the grimy slums of New York. They are eventually reunited and marry. But life in New York is hard and ...',
    genres: [ 'Drama' ],
    runtime: 78,
    rated: 'PASSED',
    cast: [ 'George Beban', 'Clara Williams', 'J. Frank Burke', 'Leo Willis' ],
    title: 'The Italian',
    fullplot: 'An immigrant leaves his sweetheart in Italy to find a better life across the sea in the grimy slums of New York. They are eventually reunited and marry. But life in New York is hard and tragedy tarnishes their dream of a better life in the new world.',
    languages: [ 'English' ],
    released: ISODate('1915-01-01T00:00:00.000Z'),
    directors: [ 'Reginald Barker' ],
    writers: [ 'Thomas H. Ince (story)', 'C. Gardner Sullivan (story)' ],
    awards: { wins: 1, nominations: 0, text: '1 win.' },
    lastupdated: '2015-07-27 00:07:43.230000000',
    year: 1915,
    imdb: { rating: 6.4, votes: 175, id: 5557 },
    countries: [ 'USA' ],
    type: 'movie',
    tomatoes: {
      viewer: { rating: 4, numReviews: 204, meter: 60 },
      dvd: ISODate('2008-08-26T00:00:00.000Z'),
      lastUpdated: ISODate('2015-07-24T19:30:02.000Z')
    },
    num_mflix_comments: 0
  },
  {
    _id: ObjectId('573a1390f29313caabcd587d'),
    plot: 'At 10 years old, Owens becomes a ragged orphan when his sainted mother dies. The Conways, who are next door neighbors, take Owen in, but the constant drinking by Jim soon puts Owen on the ...',
    genres: [ 'Biography', 'Crime', 'Drama' ],
    runtime: 72,
    rated: 'PASSED',
    cast: [ 'John McCann', 'James A. Marcus', 'Maggie Weston', 'Harry McCoy' ],
    num_mflix_comments: 1,
    poster: 'https://m.media-amazon.com/images/M/MV5BNDkxZGU4NmMtODJlNy00YzA2LTg4ZGMtNGFlNzAyNzcxOTM1XkEyXkFqcGdeQXVyOTM3MjcyMjI@._V1_SY1000_SX677_AL_.jpg',
    title: 'Regeneration',
    fullplot: 'At 10 years old, Owens becomes a ragged orphan when his sainted mother dies. The Conways, who are next door neighbors, take Owen in, but the constant drinking by Jim soon puts Owen on the street. By 17, Owen learns that might is right. By 25, Owen is the leader of his own gang who spend most of their time gambling and drinking. But Marie comes into the gangster area of town and everything changes for Owen as he falls for Marie. But he cannot tell her so, so he comes to her settlement to find education and inspiration. But soon, his old way of life will rise to confront him again.',
    languages: [ 'English' ],
    released: ISODate('1915-09-13T00:00:00.000Z'),
    directors: [ 'Raoul Walsh' ],
    writers: [
      'Owen Frawley Kildare (book)',
      'Raoul Walsh (adapted from the book: "My Mamie Rose")',
      'Carl Harbaugh (adapted from the book: "My Mamie Rose")'
    ],
    awards: { wins: 1, nominations: 0, text: '1 win.' },
    lastupdated: '2015-08-14 01:28:18.957000000',
    year: 1915,
    imdb: { rating: 6.8, votes: 626, id: 5960 },
    countries: [ 'USA' ],
    type: 'movie',
    tomatoes: {
      viewer: { rating: 3.4, numReviews: 395, meter: 70 },
      dvd: ISODate('2001-11-27T00:00:00.000Z'),
      critic: { rating: 9.2, numReviews: 5, meter: 100 },
      lastUpdated: ISODate('2015-09-17T17:22:42.000Z'),
      rotten: 0,
      production: 'Fox Film Corporation',
      fresh: 5
    }
  }
]