setup_vector_search_index(
    wiki_data_collection,
    vector_index_definition_scalar_quantized,
    vector_search_scalar_quantized_index_name,
)
setup_vector_search_index(
    wiki_data_collection,
    vector_index_definition_binary_quantized,
    vector_search_binary_quantized_index_name,
)
setup_vector_search_index(
    wiki_data_collection,
    vector_index_definition_float32_ann,
    vector_search_float32_ann_index_name,
)