export K8S_CTX="<your kubernetes context here>"

export MDB_NS="mongodb"

export MDB_VERSION="8.0.10"

export MDB_ADMIN_USER_PASSWORD="admin-user-password-CHANGE-ME"
export MDB_USER_PASSWORD="mdb-user-password-CHANGE-ME"
export MDB_SEARCH_SYNC_USER_PASSWORD="search-sync-user-password-CHANGE-ME"

export MDB_SEARCH_HOSTNAME="mdbs-search"

# External MongoDB replica set members - REPLACE THESE VALUES with your actual external MongoDB hosts
# In production, replace with your actual external MongoDB replica set members
export MDB_EXTERNAL_HOST_0="mdbc-rs-0.mdbc-rs-svc.${MDB_NS}.svc.cluster.local:27017"
export MDB_EXTERNAL_HOST_1="mdbc-rs-1.mdbc-rs-svc.${MDB_NS}.svc.cluster.local:27017"
export MDB_EXTERNAL_HOST_2="mdbc-rs-2.mdbc-rs-svc.${MDB_NS}.svc.cluster.local:27017"

# REPLACE with your external MongoDB keyfile secret name
export MDB_EXTERNAL_KEYFILE_SECRET_NAME="mdbc-rs-keyfile"

# REPLACE with the actual keyfile content from your external MongoDB replica set
# For testing, this will be automatically generated by the MongoDB Community resource
export MDB_EXTERNAL_KEYFILE_CONTENT="your-mongodb-keyfile-content-CHANGE-ME"

# REPLACE with your actual external MongoDB replica set name
export MDB_EXTERNAL_REPLICA_SET_NAME="mdbc-rs"

export OPERATOR_HELM_CHART="mongodb/mongodb-kubernetes"
export OPERATOR_ADDITIONAL_HELM_VALUES=""

export MDB_CONNECTION_STRING="mongodb://mdb-user:${MDB_USER_PASSWORD}@${MDB_EXTERNAL_HOST_0}/?replicaSet=${MDB_EXTERNAL_REPLICA_SET_NAME}"
