
# 1. Create a netlify.toml file at the root of your new project subdirectory
# 2. Copy the contents of this file into new netlify.toml file. 
# 3. Replace the "BASE" and "REPO_NAME" vars with the appropriate values 

[build]
    publish = "dist"
    base = "content/meta"

[build.environment]
    REPO_NAME ="docs-meta"
    SECRETS_SCAN_ENABLED = "false"
    OFFLINE_SNOOTY_ENABLED = "false"
    SEARCH_MANIFEST_ENABLED = "false"
    MUT_COMMANDS_ENABLED = "false"
    REDOC_ENABLED = "false"

[context.production.environment]
    ENV = "dotcomprd"

[context.preprd.environment]
    ENV = "dotcomstg"

[context.deploy-preview.environment]
    ENV = "prd"
    FRONTEND_VERSION = "main"

[context.branch-deploy.environment]
    ENV = "prd"

[context.preview-server.environment]
    ENV = "prd"

[context.dev.environment]
    ENV = "stg"

[[redirects]] 
from = "/docs/meta/style-guide/code-example-guidelines/"
to = "https://www.mongodb.com/docs/meta/code/"

[[redirects]]
from = "/docs/meta/style-guide/code-examples/"
to = "https://www.mongodb.com/docs/meta/code/"

[[redirects]]
from = "/docs/meta/images-guide/"
to = "https://www.mongodb.com/docs/meta/style-guide/screenshots/screenshot-guidelines/"

[[redirects]]
from = "/docs/meta/snooty/"
to = "https://www.mongodb.com/docs/meta/style-guide/"

[[redirects]]
from = "/docs/meta/organization/"
to = "https://www.mongodb.com/docs/meta/style-guide/"

[[redirects]]
from = "/docs/meta/translation/"
to = "https://www.mongodb.com/docs/meta/style-guide/"

[[redirects]]
from = "/docs/meta/redirects/"
to = "https://www.mongodb.com/docs/meta/style-guide/"

[[redirects]]
from = "/docs/meta/reference/apiargs/"
to = "https://www.mongodb.com/docs/meta/reference/"

[[redirects]]
from = "/docs/meta/reference/options/"
to = "https://www.mongodb.com/docs/meta/reference/"

[[redirects]]
from = "/docs/meta/reference/eval/"
to = "https://www.mongodb.com/docs/meta/reference/"

[[redirects]]
from = "/docs/meta/reference/xmlrole/"
to = "https://www.mongodb.com/docs/meta/reference/"

[[redirects]]
from = "/docs/meta/tutorials/generating-a-browser-list/"
to = "https://www.mongodb.com/docs/meta/tutorials/review-agent-skill/"

[[redirects]]
from = "/docs/meta/tutorials/guide/"
to = "https://www.mongodb.com/docs/meta/tutorials/review-agent-skill/"

[[redirects]]
from = "/docs/meta/tutorials/install/"
to = "https://www.mongodb.com/docs/meta/tutorials/review-agent-skill/"

[[redirects]]
from = "/docs/meta/tutorials/repo/"
to = "https://www.mongodb.com/docs/meta/tutorials/review-agent-skill/"

[[redirects]]
from = "/docs/meta/tutorials/version-bumping/"
to = "https://www.mongodb.com/docs/meta/tutorials/review-agent-skill/"

[[redirects]]
from = "/docs/meta/tutorials/install/"
to = "https://www.mongodb.com/docs/meta/tutorials/"
