import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { generate } from '../src/generator';
import { LLMS_TXT_CHAR_LIMIT } from '../src/types';

async function writeFile(filePath: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf-8');
}

describe('generate', () => {
  let monorepoPath: string;
  let outputDir: string;
  let descriptionsPath: string;

  async function writeDescriptions(map: Record<string, string | string[]>): Promise<void> {
    await writeFile(descriptionsPath, JSON.stringify(map));
  }

  beforeEach(async () => {
    monorepoPath = await fs.mkdtemp(path.join(os.tmpdir(), 'generate-llms-fixture-'));
    outputDir = path.join(monorepoPath, 'llms-output');
    descriptionsPath = path.join(monorepoPath, 'llms-descriptions.json');
    await writeDescriptions({ 'go-driver': 'The Go Driver landing page.' });

    // Generated by `pnpm build:prefix-map` in docs-nextjs; keyed by content
    // directory name, not Snooty project name. "unmapped-project" is
    // deliberately omitted to exercise the unmapped-project skip path.
    // "standby-clusters" IS mapped here to prove INTERNAL_ONLY_PROJECTS skips
    // it before URL resolution is even attempted.
    await writeFile(
      path.join(monorepoPath, 'platform', 'docs-nextjs', 'src', 'generated', 'dir-name-to-prefix.json'),
      JSON.stringify({
        'go-driver': 'docs/drivers/go',
        meta: 'docs/meta',
        shared: 'docs/shared',
        'standby-clusters': 'docs/standby-clusters',
      }),
    );

    await writeFile(
      path.join(monorepoPath, 'content', 'go-driver', 'current', 'snooty.toml'),
      `name = "golang"
title = "Go Driver"

[constants]
driver-short = "Go Driver"
`,
    );
    await writeFile(
      path.join(monorepoPath, 'content', 'go-driver', 'current', 'source', 'index.txt'),
      `====================
{+driver-short+} Docs
====================

.. meta::
   :description: The {+driver-short+} landing page.

Welcome.
`,
    );
    await writeFile(
      path.join(monorepoPath, 'content', 'go-driver', 'current', 'source', 'quick-start.txt'),
      `Quick Start
===========

.. meta::
   :description: Get started quickly.

Body.
`,
    );
    // No title -> should be skipped.
    await writeFile(
      path.join(monorepoPath, 'content', 'go-driver', 'current', 'source', 'no-title.txt'),
      'Just a paragraph, no heading.\n',
    );
    // Should be skipped: nested under an excluded subdirectory.
    await writeFile(
      path.join(monorepoPath, 'content', 'go-driver', 'current', 'source', 'includes', 'fact.rst'),
      `Some Fact
=========

Body.
`,
    );
    // Older, non-current version: should not be walked.
    await writeFile(
      path.join(monorepoPath, 'content', 'go-driver', 'v1.0', 'source', 'index.txt'),
      `Old Version
===========

Body.
`,
    );

    // Excluded top-level project directory (has a source/ dir, but is on the exclusion list).
    await writeFile(path.join(monorepoPath, 'content', 'meta', 'source', 'index.txt'), 'Meta\n====\n');

    // Not a documentation project at all (no source/ dir anywhere).
    await fs.mkdir(path.join(monorepoPath, 'content', 'shared'), { recursive: true });

    // internalOnly project (per HEALTH_CHECK_PREFIX_DENYLIST precedent): has
    // real pages and IS mapped in dir-name-to-prefix.json, but should still
    // be skipped because it isn't live on production.
    await writeFile(
      path.join(monorepoPath, 'content', 'standby-clusters', 'snooty.toml'),
      `name = "standby-clusters"
title = "Standby Clusters"
`,
    );
    await writeFile(
      path.join(monorepoPath, 'content', 'standby-clusters', 'source', 'index.txt'),
      'Standby Clusters\n================\n',
    );

    // Unmapped project name: has real pages but no entry in dir-name-to-prefix.json.
    await writeFile(
      path.join(monorepoPath, 'content', 'unmapped-project', 'snooty.toml'),
      `name = "unmapped-project"
title = "Unmapped Project"
`,
    );
    await writeFile(
      path.join(monorepoPath, 'content', 'unmapped-project', 'source', 'index.txt'),
      'Unmapped Project\n================\n',
    );
  });

  afterEach(async () => {
    await fs.rm(monorepoPath, { recursive: true, force: true });
  });

  it('generates an llms.txt for a mapped project, resolving substitutions and skipping excluded content', async () => {
    const results = await generate({
      monorepoPath,
      outputDir,
      baseUrl: 'https://www.mongodb.com/docs',
      descriptionsPath,
      noDescriptions: false,
    });

    const goDriver = results.find((r) => r.project === 'go-driver');
    expect(goDriver).toBeDefined();
    expect(goDriver?.version).toBe('current');
    // index.txt, quick-start.txt; no-title.txt and includes/fact.rst excluded; v1.0 not walked.
    expect(goDriver?.pages).toHaveLength(2);

    const titles = goDriver?.pages.map((p) => p.title).sort();
    expect(titles).toEqual(['Go Driver Docs', 'Quick Start']);

    // The project header title comes from snooty.toml's `title`, not `name`.
    // The description comes from llms-descriptions.json, not any page's meta
    // description.
    expect(goDriver?.indexDescription).toBe('The Go Driver landing page.');

    const rootPage = goDriver?.pages.find((p) => p.title === 'Go Driver Docs');
    expect(rootPage?.url).toBe('https://www.mongodb.com/docs/drivers/go/current/index.md');

    const quickStart = goDriver?.pages.find((p) => p.title === 'Quick Start');
    expect(quickStart?.url).toBe('https://www.mongodb.com/docs/drivers/go/current/quick-start.md');

    // Small project, well under the limit: a single llms.txt, not split.
    expect(goDriver?.outputPaths).toHaveLength(1);
    expect(goDriver?.anyPartOverLimit).toBe(false);

    const writtenContent = await fs.readFile(goDriver!.outputPaths[0], 'utf-8');
    expect(writtenContent).toContain('# Go Driver - (current)');
    // The blockquote summary comes from llms-descriptions.json...
    expect(writtenContent).toContain('> The Go Driver landing page.');
    // ...while each page's own meta description is still appended inline.
    expect(writtenContent).toContain(
      '- [Go Driver Docs](https://www.mongodb.com/docs/drivers/go/current/index.md): The Go Driver landing page.',
    );
    expect(writtenContent).toContain(
      '- [Quick Start](https://www.mongodb.com/docs/drivers/go/current/quick-start.md): Get started quickly.',
    );

    // Excluded / internal-only / unresolvable projects should not appear at all.
    expect(results.find((r) => r.project === 'meta')).toBeUndefined();
    expect(results.find((r) => r.project === 'shared')).toBeUndefined();
    expect(results.find((r) => r.project === 'standby-clusters')).toBeUndefined();
    expect(results.find((r) => r.project === 'unmapped-project')).toBeUndefined();
  });

  it('resolves |name| substitutions in titles, with page-level declarations winning', async () => {
    await writeFile(
      path.join(monorepoPath, 'content', 'atlas-operator', 'current', 'snooty.toml'),
      `name = "atlas-operator"
title = "Atlas Kubernetes Operator"

[substitutions]
ak8so = "Atlas Kubernetes Operator"
service = "Atlas"
`,
    );
    await writeFile(
      path.join(monorepoPath, 'content', 'atlas-operator', 'current', 'source', 'index.txt'),
      `============
|ak8so|
============

Welcome.
`,
    );
    // This page defines its own, page-local override for "ak8so" via a
    // standard RST ".. |name| replace::" directive, which should win over
    // the project-wide snooty.toml [substitutions] value above.
    await writeFile(
      path.join(monorepoPath, 'content', 'atlas-operator', 'current', 'source', 'changelog.txt'),
      `.. |ak8so| replace:: AKO

|ak8so| Changelog
=================

Body.
`,
    );
    // Some substitutions (e.g. manual's per-version release-notes
    // |newversion|/|oldversion|) aren't declared on the page itself, but in
    // a shared snippet pulled in via a plain ".. include:: /path.rst"
    // directive.
    await writeFile(
      path.join(monorepoPath, 'content', 'atlas-operator', 'current', 'source', 'includes', 'version-facts.rst'),
      '.. |newversion| replace:: 2.5\n',
    );
    await writeFile(
      path.join(monorepoPath, 'content', 'atlas-operator', 'current', 'source', 'upgrade.txt'),
      `.. include:: /includes/version-facts.rst

Upgrade to |newversion|
========================

Body.
`,
    );
    await writeFile(
      path.join(monorepoPath, 'platform', 'docs-nextjs', 'src', 'generated', 'dir-name-to-prefix.json'),
      JSON.stringify({ 'atlas-operator': 'docs/atlas/operator' }),
    );

    const results = await generate({
      monorepoPath,
      outputDir,
      baseUrl: 'https://www.mongodb.com/docs',
      descriptionsPath,
      noDescriptions: false,
      forProject: 'atlas-operator',
    });

    expect(results).toHaveLength(1);
    const project = results[0];

    const rootPage = project.pages.find((p) => p.pagePath === '');
    expect(rootPage?.title).toBe('Atlas Kubernetes Operator');

    // Substitution defined only in a shared snippet pulled in via
    // ".. include::", not in snooty.toml or directly on the page.
    const upgradePage = project.pages.find((p) => p.pagePath === 'upgrade');
    expect(upgradePage?.title).toBe('Upgrade to 2.5');

    // Page-level override: "AKO", not the project-wide "Atlas Kubernetes Operator".
    const changelogPage = project.pages.find((p) => p.pagePath === 'changelog');
    expect(changelogPage?.title).toBe('AKO Changelog');
  });

  it('supports --for-project to limit generation to a single project', async () => {
    const results = await generate({
      monorepoPath,
      outputDir,
      baseUrl: 'https://www.mongodb.com/docs',
      descriptionsPath,
      noDescriptions: false,
      forProject: 'go-driver',
    });

    expect(results).toHaveLength(1);
    expect(results[0].project).toBe('go-driver');
  });

  it('omits the summary blockquote and every page`s inline description from the written file when noDescriptions is set', async () => {
    const results = await generate({
      monorepoPath,
      outputDir,
      baseUrl: 'https://www.mongodb.com/docs',
      descriptionsPath,
      noDescriptions: true,
      forProject: 'go-driver',
    });

    const written = await fs.readFile(results[0].outputPaths[0], 'utf-8');
    expect(written).not.toContain('The Go Driver landing page.');
    expect(written).not.toContain('Get started quickly.');
    expect(written).toContain('- [Quick Start](https://www.mongodb.com/docs/drivers/go/current/quick-start.md)\n');
    // indexDescription is still captured/reported regardless of what was written.
    expect(results[0].indexDescription).toBe('The Go Driver landing page.');
    // The per-page description is still captured/reported too.
    const quickStart = results[0].pages.find((p) => p.pagePath === 'quick-start');
    expect(quickStart?.description).toBe('Get started quickly.');
    // The char counts are still reported for both variants regardless of what was written.
    expect(results[0].charsWithDescriptions).toBeGreaterThan(results[0].charsWithoutDescriptions);
  });

  it('splits an oversized project into multiple part files without breaking an L3 section across files', async () => {
    const sections = ['alpha', 'beta', 'gamma'];
    const pagesPerSection = 100;
    // Padding pages out with long titles keeps the fixture to ~300 files
    // (instead of thousands) while still comfortably exceeding the 50k limit.
    const padding = 'x'.repeat(400);

    for (const section of sections) {
      for (let i = 0; i < pagesPerSection; i++) {
        const n = String(i).padStart(3, '0');
        await writeFile(
          path.join(monorepoPath, 'content', 'big-project', 'current', 'source', section, `page-${n}.txt`),
          `==========\n${section} Page ${n} ${padding}\n==========\n\nBody.\n`,
        );
      }
    }
    await writeFile(
      path.join(monorepoPath, 'content', 'big-project', 'current', 'snooty.toml'),
      'name = "big-project"\ntitle = "Big Project"\n',
    );
    await writeFile(
      path.join(monorepoPath, 'content', 'big-project', 'current', 'source', 'index.txt'),
      'Big Project\n===========\n',
    );
    await writeFile(
      path.join(monorepoPath, 'platform', 'docs-nextjs', 'src', 'generated', 'dir-name-to-prefix.json'),
      JSON.stringify({ 'big-project': 'docs/big' }),
    );

    const results = await generate({
      monorepoPath,
      outputDir,
      baseUrl: 'https://www.mongodb.com/docs',
      descriptionsPath,
      noDescriptions: false,
      forProject: 'big-project',
    });

    expect(results).toHaveLength(1);
    const bigProject = results[0];
    expect(bigProject.charsWithDescriptions).toBeGreaterThan(LLMS_TXT_CHAR_LIMIT);
    expect(bigProject.outputPaths.length).toBeGreaterThan(1);
    expect(bigProject.anyPartOverLimit).toBe(false);

    const sectionsPerFile: Set<string>[] = [];
    for (const outputPath of bigProject.outputPaths) {
      expect(path.basename(outputPath)).toMatch(/^big-project-\d+-llms\.txt$/);
      const content = await fs.readFile(outputPath, 'utf-8');
      expect(content.length).toBeLessThanOrEqual(LLMS_TXT_CHAR_LIMIT);
      expect(content).toMatch(/^# Big Project - \(current\) \(Part \d+ of \d+\)\n/);

      const sectionsInFile = new Set([...content.matchAll(/\/current\/([a-z]+)\/page-\d+\.md/g)].map((m) => m[1]));
      sectionsPerFile.push(sectionsInFile);
    }

    // Every section (L3) is fully contained in exactly one part file.
    const seen = new Set<string>();
    for (const sectionsInFile of sectionsPerFile) {
      for (const section of sectionsInFile) {
        expect(seen.has(section)).toBe(false);
        seen.add(section);
      }
    }
    expect(seen).toEqual(new Set(sections));
  });

  it('recurses one level deeper (L4) when a single L3 section is still oversized on its own', async () => {
    // "aaa" is tiny, so the depth-1 split cleanly isolates all of
    // "reference" into one chunk — but "reference" alone (its "one" and
    // "two" L4 subsections combined) is still too big to fit in a single
    // part, so it must be recursed into at depth 2.
    const padding = 'x'.repeat(400);
    await writeFile(
      path.join(monorepoPath, 'content', 'big-project', 'current', 'source', 'aaa', 'page-0.txt'),
      '==========\naaa Page 0\n==========\n\nBody.\n',
    );
    for (const subsection of ['one', 'two']) {
      for (let i = 0; i < 100; i++) {
        const n = String(i).padStart(3, '0');
        await writeFile(
          path.join(monorepoPath, 'content', 'big-project', 'current', 'source', 'reference', subsection, `page-${n}.txt`),
          `==========\n${subsection} Page ${n} ${padding}\n==========\n\nBody.\n`,
        );
      }
    }
    await writeFile(
      path.join(monorepoPath, 'content', 'big-project', 'current', 'snooty.toml'),
      'name = "big-project"\ntitle = "Big Project"\n',
    );
    await writeFile(
      path.join(monorepoPath, 'content', 'big-project', 'current', 'source', 'index.txt'),
      'Big Project\n===========\n',
    );
    await writeFile(
      path.join(monorepoPath, 'platform', 'docs-nextjs', 'src', 'generated', 'dir-name-to-prefix.json'),
      JSON.stringify({ 'big-project': 'docs/big' }),
    );

    const results = await generate({
      monorepoPath,
      outputDir,
      baseUrl: 'https://www.mongodb.com/docs',
      descriptionsPath,
      noDescriptions: false,
      forProject: 'big-project',
    });

    expect(results).toHaveLength(1);
    const bigProject = results[0];
    expect(bigProject.outputPaths.length).toBeGreaterThan(2);
    expect(bigProject.anyPartOverLimit).toBe(false);

    const sectionsPerFile: Set<string>[] = [];
    for (const outputPath of bigProject.outputPaths) {
      const content = await fs.readFile(outputPath, 'utf-8');
      expect(content.length).toBeLessThanOrEqual(LLMS_TXT_CHAR_LIMIT);
      const sectionsInFile = new Set(
        [...content.matchAll(/\/current\/reference\/([a-z]+)\/page-\d+\.md/g)].map((m) => m[1]),
      );
      sectionsPerFile.push(sectionsInFile);
    }

    // Neither "one" nor "two" (the L4 subsections) is split across two files.
    const seen = new Set<string>();
    for (const sectionsInFile of sectionsPerFile) {
      for (const section of sectionsInFile) {
        expect(seen.has(section)).toBe(false);
        seen.add(section);
      }
    }
    expect(seen).toEqual(new Set(['one', 'two']));
  });

  it('supports --oversized-section-parts to force a specific sub-part count for an oversized section', async () => {
    const padding = 'x'.repeat(400);
    await writeFile(
      path.join(monorepoPath, 'content', 'big-project', 'current', 'source', 'aaa', 'page-0.txt'),
      '==========\naaa Page 0\n==========\n\nBody.\n',
    );
    for (const subsection of ['one', 'two']) {
      for (let i = 0; i < 100; i++) {
        const n = String(i).padStart(3, '0');
        await writeFile(
          path.join(monorepoPath, 'content', 'big-project', 'current', 'source', 'reference', subsection, `page-${n}.txt`),
          `==========\n${subsection} Page ${n} ${padding}\n==========\n\nBody.\n`,
        );
      }
    }
    await writeFile(
      path.join(monorepoPath, 'content', 'big-project', 'current', 'snooty.toml'),
      'name = "big-project"\ntitle = "Big Project"\n',
    );
    await writeFile(
      path.join(monorepoPath, 'content', 'big-project', 'current', 'source', 'index.txt'),
      'Big Project\n===========\n',
    );
    await writeFile(
      path.join(monorepoPath, 'platform', 'docs-nextjs', 'src', 'generated', 'dir-name-to-prefix.json'),
      JSON.stringify({ 'big-project': 'docs/big' }),
    );

    const results = await generate({
      monorepoPath,
      outputDir,
      baseUrl: 'https://www.mongodb.com/docs',
      descriptionsPath,
      noDescriptions: false,
      forProject: 'big-project',
      oversizedSectionParts: 2,
    });

    expect(results).toHaveLength(1);
    // "aaa" is its own part, plus exactly 2 forced sub-parts for "reference" == 3.
    expect(results[0].outputPaths).toHaveLength(3);
  });

  it('supports --parts to force a specific number of part files', async () => {
    const sections = ['alpha', 'beta', 'gamma'];
    const pagesPerSection = 100;
    const padding = 'x'.repeat(400);

    for (const section of sections) {
      for (let i = 0; i < pagesPerSection; i++) {
        const n = String(i).padStart(3, '0');
        await writeFile(
          path.join(monorepoPath, 'content', 'big-project', 'current', 'source', section, `page-${n}.txt`),
          `==========\n${section} Page ${n} ${padding}\n==========\n\nBody.\n`,
        );
      }
    }
    await writeFile(
      path.join(monorepoPath, 'content', 'big-project', 'current', 'snooty.toml'),
      'name = "big-project"\ntitle = "Big Project"\n',
    );
    await writeFile(
      path.join(monorepoPath, 'content', 'big-project', 'current', 'source', 'index.txt'),
      'Big Project\n===========\n',
    );
    await writeFile(
      path.join(monorepoPath, 'platform', 'docs-nextjs', 'src', 'generated', 'dir-name-to-prefix.json'),
      JSON.stringify({ 'big-project': 'docs/big' }),
    );

    const results = await generate({
      monorepoPath,
      outputDir,
      baseUrl: 'https://www.mongodb.com/docs',
      descriptionsPath,
      noDescriptions: false,
      forProject: 'big-project',
      parts: 3,
    });

    expect(results).toHaveLength(1);
    // The 3 equal-sized sections naturally line up with 3 requested parts.
    expect(results[0].outputPaths).toHaveLength(3);
    for (const outputPath of results[0].outputPaths) {
      expect(path.basename(outputPath)).toMatch(/^big-project-\d+-llms\.txt$/);
      const content = await fs.readFile(outputPath, 'utf-8');
      expect(content).toMatch(/^# Big Project - \(current\) \(Part \d+ of 3\)\n/);
    }
  });

  it('excludes pages under a "meta" subdirectory (error/PDF utility pages, not real content)', async () => {
    await writeFile(
      path.join(monorepoPath, 'content', 'go-driver', 'current', 'source', 'meta', '404.txt'),
      'Page Not Found\n==============\n\nBody.\n',
    );

    const results = await generate({
      monorepoPath,
      outputDir,
      baseUrl: 'https://www.mongodb.com/docs',
      descriptionsPath,
      noDescriptions: false,
      forProject: 'go-driver',
    });

    expect(results).toHaveLength(1);
    // Still just index.txt and quick-start.txt; meta/404.txt is excluded.
    expect(results[0].pages).toHaveLength(2);
    expect(results[0].pages.some((p) => p.title === 'Page Not Found')).toBe(false);
  });

  it('applies the built-in "manual" split override automatically, with no --parts/--oversized-section-parts flags', async () => {
    const padding = 'x'.repeat(400);
    await writeFile(
      path.join(monorepoPath, 'content', 'manual', 'manual', 'source', 'aaa', 'page-0.txt'),
      '==========\naaa Page 0\n==========\n\nBody.\n',
    );
    for (const subsection of ['one', 'two']) {
      for (let i = 0; i < 100; i++) {
        const n = String(i).padStart(3, '0');
        await writeFile(
          path.join(monorepoPath, 'content', 'manual', 'manual', 'source', 'reference', subsection, `page-${n}.txt`),
          `==========\n${subsection} Page ${n} ${padding}\n==========\n\nBody.\n`,
        );
      }
    }
    await writeFile(
      path.join(monorepoPath, 'content', 'manual', 'manual', 'snooty.toml'),
      'name = "manual"\ntitle = "MongoDB Manual"\n',
    );
    await writeFile(
      path.join(monorepoPath, 'content', 'manual', 'manual', 'source', 'index.txt'),
      'MongoDB Manual\n==============\n',
    );
    await writeFile(
      path.join(monorepoPath, 'platform', 'docs-nextjs', 'src', 'generated', 'dir-name-to-prefix.json'),
      JSON.stringify({ manual: 'docs/manual' }),
    );

    const results = await generate({
      monorepoPath,
      outputDir,
      baseUrl: 'https://www.mongodb.com/docs',
      descriptionsPath,
      noDescriptions: false,
      forProject: 'manual',
    });

    expect(results).toHaveLength(1);
    // The override forces a 2-way initial split; the only available L3
    // boundary is between "aaa" and "reference", so that's isolated as its
    // own part. "reference" is still oversized on its own, so the override
    // also forces its first recursive split into exactly 2 sub-parts
    // ("one" and "two") instead of however many the automatic, size-driven
    // count would otherwise produce — 3 files total, none over the limit.
    expect(results[0].outputPaths).toHaveLength(3);
    expect(results[0].anyPartOverLimit).toBe(false);

    // An explicit --parts flag for the targeted project still wins over
    // the built-in override's initial-split count: forcing 3 (instead of
    // the override's 2) lines up with all 3 available L3 boundaries
    // ("", "aaa", "reference"), isolating "reference" on its own before it
    // recurses into the override's still-inherited 2 sub-parts — 4 files
    // total, not the override-only 3.
    const explicitlyForced = await generate({
      monorepoPath,
      outputDir,
      baseUrl: 'https://www.mongodb.com/docs',
      descriptionsPath,
      noDescriptions: false,
      forProject: 'manual',
      parts: 3,
    });
    expect(explicitlyForced[0].outputPaths).toHaveLength(4);
  });
});
