name = "agentengine"
title = "MongoDB Atlas Agent Engine"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

# toc_landing_pages = ["/paths/to/pages/that/have/nested/content"]

[[banners]]
targets = ["*"]
variant = "warning"
value = "{+mdb-ai-platform+} is in Public Preview and intended for evaluation and prototyping purposes only. We do not recommend production deployments during preview and expect to communicate breaking changes with you periodically. To learn more about preview feature considerations, see `Preview Features <https://www.mongodb.com/docs/preview-features/>`__."

[constants]
mdb-ai-platform = "MongoDB Atlas Agent Engine"
platform-short = "Atlas Agent Engine"
version = "0.1.94-alpha"
