exports = async function onNewCustomFunctionUser({ user }) {
  // This is the user's internal account ID that was generated by your app
  const internalId = user.id;

  // This is the external ID returned from the authentication function
  const customFunctionIdentity = user.identities.find((id) => {
    return id.provider_type === "custom-function";
  });
  const externalId = customFunctionIdentity.id;

  // Create a custom user data document for the user
  const mdb = context.services.get("mongodb-atlas");
  const users = mdb.db("myApp").collection("users");
  return await users.insertOne({
    // Include both the internal ID and external ID
    user_id: internalId,
    external_id: externalId,
    // Add any other data you want to include
    created_at: new Date(),
  });
};
