import type { Metadata } from 'next';
// import { cookies } from "next/headers";
import './globals.css'; // TODO:
import '../styles/mongodb-docs.css';
import '../styles/global-dark-mode.css';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { LeafyGreenProvider } from './emotion';
import layoutStyles from './layout.module.scss';
import IconBook from '@/components/icons/Book';
import IconCompass from '@/components/icons/Compass';
import IconC from '@/components/icons/C';
import IconCpp from '@/components/icons/Cpp';
import IconCsharp from '@/components/icons/Csharp';
import IconDarkmode from '@/components/icons/DarkMode';
import IconDart from '@/components/icons/Dart';
import IconGo from '@/components/icons/Go';
import IconJava from '@/components/icons/Java';
import IconJavascript from '@/components/icons/Javascript';
import IconKotlin from '@/components/icons/Kotlin';
import IconLightningBolt from '@/components/icons/LightningBolt';
import IconNode from '@/components/icons/Node';
import IconObjectiveC from '@/components/icons/ObjectiveC';
import IconPhp from '@/components/icons/Php';
import IconPython from '@/components/icons/Python';
import IconRuby from '@/components/icons/Ruby';
import IconRust from '@/components/icons/Rust';
import IconScala from '@/components/icons/Scala';
import IconShell from '@/components/icons/Shell';
import IconSwift from '@/components/icons/Swift';
import IconTypescript from '@/components/icons/Typescript';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: handle dark mode here using cookies or local storage
  // const cookiesObj = await cookies();
  console.log('RootLayout cookies', 'TODO: handle dark mode here using cookies or local storage');
  return (
    <html lang="en">
      <body>
        <div className={layoutStyles.layout}>
          <LeafyGreenProvider>
            <Header />
            {/* TODO: return a sidenav here */}
            <div
              className={'sidenav-container'}
              style={{
                gridArea: 'sidenav',
                width: '268px',
              }}
            >
              REPLACE WITH SIDENAV
              <IconBook />
              <IconCompass />
              <IconC />
              <IconCpp />
              <IconCsharp />
              <IconDarkmode />
              <IconDart />
              <IconGo />
              <IconJava />
              <IconJavascript />
              <IconKotlin />
              <IconLightningBolt />
              <IconNode />
              <IconObjectiveC />
              <IconPhp />
              <IconPython />
              <IconRuby />
              <IconRust />
              <IconScala />
              <IconShell />
              <IconSwift />
              <IconTypescript />
            </div>
            {children}
            <Footer />
          </LeafyGreenProvider>
        </div>
      </body>
    </html>
  );
}
