import type { Metadata } from "next";
// import { cookies } from "next/headers";
import "./globals.css"; // TODO: 
import Header from "@/components/header";
import Footer from "@/components/footer";
import { LeafyGreenProvider } from "./emotion";
import layoutStyles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: handle dark mode here using cookies or local storage
  // const cookiesObj = await cookies();
  console.log("RootLayout cookies", "TODO: handle dark mode here using cookies or local storage");
  return (
    <html lang="en">
      <body>
        <div className={layoutStyles.layout}>
          <LeafyGreenProvider>
            <Header />
            {/* TODO: return a sidenav here */}
            <div className={'sidenav-container'} style={{
              gridArea: 'sidenav',
              width: '268px'
            }}>REPLACE WITH SIDENAV</div>
            {children}
            <Footer />
          </LeafyGreenProvider>
        </div>
      </body>
    </html >
  );
}
