import type { Metadata } from 'next';
// import { cookies } from "next/headers";
import './globals.css'; // TODO:
import '../styles/mongodb-docs.css';
import '../styles/global-dark-mode.css';
import Header from '@/components/header';
import Footer from '@/components/footer';
import TrackJSProvider from '@/components/trackjs-provider';
import { LeafyGreenProviderWrapper } from './emotion';
import layoutStyles from './layout.module.scss';
import { DarkModeContextProvider } from '@/context/dark-mode-context';

const faviconUrl = `https://www.mongodb.com/docs/assets/favicon.ico`;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: faviconUrl,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TrackJSProvider />
        <div className={layoutStyles.layout}>
          <DarkModeContextProvider>
            <LeafyGreenProviderWrapper>
              <Header />
              {children}
              <Footer />
            </LeafyGreenProviderWrapper>
          </DarkModeContextProvider>
        </div>
      </body>
    </html>
  );
}
