import path from 'path';
import type { Root } from 'mdast';
import type { Node } from 'unist';
import type { MdxJsxAttribute, MdxJsxFlowElement, MdxJsxTextElement } from 'mdast-util-mdx-jsx';
import { visit } from 'unist-util-visit';
import imageDimensions from '@/generated/image-dimensions.json';

type MdxJsxElement = MdxJsxFlowElement | MdxJsxTextElement;

const dimensionsMap = imageDimensions as Record<string, { width: number; height: number }>;

/**
 * Remark plugin that injects intrinsic pixel dimensions onto <Image> nodes.
 *
 * The <Image> component renders content images with next/image, which requires
 * numeric width+height. The Snooty→MDX pipeline only emits :width:/:figwidth:/
 * :height: when present in the RST (and figwidth/width may be percentages), so
 * those attributes are not a reliable intrinsic-size source. Instead we look up
 * each image's real dimensions from image-dimensions.json (generated by
 * scripts/copy-content-images.ts) and set `intrinsicWidth`/`intrinsicHeight`.
 *
 * The lookup key mirrors the component's own path.join(projectPath, src) so the
 * manifest key ("<project>/<version>/images/foo.png") matches. Images with no
 * manifest entry (e.g. an SVG without an intrinsic size) are left untouched; the
 * component falls back to a plain <img> for those.
 *
 * Must run after remarkResolveImports so that <Image> nodes inlined from
 * includes are present in the tree.
 */
export const remarkImageDimensions = ({ projectPath }: { projectPath: string }) => {
  return (tree: Root) => {
    visit(tree, (node) => {
      if (!isJsxElement(node) || node.name !== 'Image') return;

      const src = getAttr(node, 'src');
      if (!src) return;

      // Skip if dimensions were already injected (e.g. a re-run over cached AST).
      if (getAttr(node, 'intrinsicWidth')) return;

      const key = path.posix.join(projectPath, src).replace(/^\//, '');
      const dims = dimensionsMap[key];
      if (!dims) return;

      node.attributes.push(makeAttr('intrinsicWidth', String(dims.width)));
      node.attributes.push(makeAttr('intrinsicHeight', String(dims.height)));
    });
  };
};

const makeAttr = (name: string, value: string): MdxJsxAttribute => ({
  type: 'mdxJsxAttribute',
  name,
  value,
});

const isJsxElement = (node: Node): node is MdxJsxElement =>
  node.type === 'mdxJsxFlowElement' || node.type === 'mdxJsxTextElement';

const getAttr = (node: MdxJsxElement, name: string): string | undefined => {
  const attr = node.attributes?.find((a) => (a as MdxJsxAttribute).name === name);
  if (!attr || typeof (attr as MdxJsxAttribute).value !== 'string') return undefined;
  return (attr as MdxJsxAttribute).value as string;
};
