name = "self-managed-search"
title = "Self-Managed MongoDB Search and Vector Search"

intersphinx = [ "https://www.mongodb.com/docs/atlas/objects.inv",
                "https://www.mongodb.com/docs/atlas/cli/current/objects.inv",
                "https://www.mongodb.com/docs/kubernetes/current/objects.inv",
                "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/mcp-server/objects.inv",
                "https://www.mongodb.com/docs/mongodb-shell/objects.inv",
                "https://www.mongodb.com/docs/search/objects.inv",
                "https://www.mongodb.com/docs/vector-search/objects.inv",
                "https://www.mongodb.com/docs/voyageai/objects.inv",
              ]

toc_landing_pages = [
    "/index",
    "/deployment/compatibility-requirements",
    "/resource-planning-sizing/introduction",
    "/deployment/backup-restore",
    "/troubleshooting",
    "/limitations",
    "/release-notes"
]

# [constants]
# constant = "value"


[constants]
api = "API"
atlas-ui = "Atlas UI"
avs = "MongoDB Vector Search"
cloud-backup = "Cloud Backup"
fts = "MongoDB Search"
k8s = "Kubernetes"
k8s-op = "MongoDB Controllers for Kubernetes Operator"
k8s-op-short = "Kubernetes Operator"
mdb-search = "MongoDB Search and Vector Search"
mdb-search-full = "MongoDB Search and Vector Search in Community"
model-api-key = "model API key"
model-api-keys = "model API keys"
mongod = ":binary:`~bin.mongod`"
mongosh = ":binary:`~bin.mongosh`"
mql = ":abbr:`MQL (MongoDB Query Language)`"
om = "Ops Manager"
playground = "MongoDB Search Playground"
service = "Atlas"
rag = ":abbr:`RAG (Retrieval-Augmented Generation)`"
smd = "self-managed deployment"
SMD = "Self-Managed Deployment"
voyageai = "Voyage AI"


[substitutions]
text-search = "MongoDB Search"
vector-search = "Vector Search"
avs = "MongoDB Vector Search"
api = ":abbr:`API (Application Programming Interface)`"
ca-cert = "CA Certificate"
ca-certs = "CA Certificates"
certauth = ":abbr:`CA (Certificate Authority)`"
compass = ":compass:`MongoDB Compass </>`"
company = "MongoDB, Inc."
ent-build = "MongoDB Enterprise"
fts = "MongoDB Search"
http = ":abbr:`HTTP (HyperText Transport Protocol)`"
k8s = "Kubernetes"
k8s-op = "MongoDB Controllers for Kubernetes Operator"
k8s-op-short = "Kubernetes Operator"
mck = ":abbr:`MongoDB Controllers for Kubernetes Operator`"
mdb-search = "MongoDB Search and Vector Search"
mongod = ":binary:`~bin.mongod`"
mongosh = ":binary:`~bin.mongosh`"
service-fullname = "MongoDB Atlas"
service = "Atlas"
tls = ":abbr:`TLS (Transport Layer Security)`"
voyage = "Voyage AI"
