// Auto-generated by scripts/generate-all-redirects.ts — do not edit manually.
// Run: pnpm generate:redirects to regenerate.
import type { RedirectEntry } from './redirect-utils';
import appServicesRedirects from './app-services-redirects.json';
import atlasCliRedirects from './atlas-cli-redirects.json';
import landingRedirects from './landing-redirects.json';
import realmRedirects from './realm-redirects.json';
import searchRedirects from './search-redirects.json';
import standbyClustersRedirects from './standby-clusters-redirects.json';
import vectorSearchRedirects from './vector-search-redirects.json';

export const allRedirects: RedirectEntry[] = [
  ...appServicesRedirects,
  ...atlasCliRedirects,
  ...landingRedirects,
  ...realmRedirects,
  ...searchRedirects,
  ...standbyClustersRedirects,
  ...vectorSearchRedirects,
] as RedirectEntry[];
