// Auto-generated by scripts/generate-all-redirects.ts — do not edit manually.
// Run: pnpm generate:redirects to regenerate.
import type { RedirectEntry } from './redirect-utils';
import appServicesRedirects from './app-services-redirects.json';
import atlasArchitectureRedirects from './atlas-architecture-redirects.json';
import atlasCliRedirects from './atlas-cli-redirects.json';
import atlasGovernmentRedirects from './atlas-government-redirects.json';
import atlasOperatorRedirects from './atlas-operator-redirects.json';
import atlasRedirects from './atlas-redirects.json';
import landingRedirects from './landing-redirects.json';
import manualRedirects from './manual-redirects.json';
import nodeRedirects from './node-redirects.json';
import realmRedirects from './realm-redirects.json';

export const allRedirects: RedirectEntry[] = [
  ...appServicesRedirects,
  ...atlasArchitectureRedirects,
  ...atlasCliRedirects,
  ...atlasGovernmentRedirects,
  ...atlasOperatorRedirects,
  ...atlasRedirects,
  ...landingRedirects,
  ...manualRedirects,
  ...nodeRedirects,
  ...realmRedirects,
] as RedirectEntry[];
