[
  { title: 'The Great Train Robbery' },
  { title: 'A Corner in Wheat' },
  { title: 'From Hand to Mouth' },
  { title: 'One Week' },
  { title: 'The Devil to Pay!' },
  { title: 'Footlight Parade' },
  { title: 'Gold Diggers of 1935' },
  { title: 'Naughty Marietta' },
  { title: 'Modern Times' },
  { title: 'Gone with the Wind' },
  { title: 'Fantasia' },
  { title: 'The Man Who Came to Dinner' },
  { title: 'National Velvet' },
  { title: 'Alice in Wonderland' },
  { title: 'The Member of the Wedding' },
  { title: 'Seven Brides for Seven Brothers' },
  { title: 'Around the World in Eighty Days' },
  { title: 'The King and I' },
  { title: 'A King in New York' },
  { title: 'Ben-Hur' }
]
