/**
 * Offline docs build: produces a static snapshot that works from the filesystem (e.g. file:// or a zip).
 *
 * Usage: pnpm build:offline --tocFile=<name> [--version=<version>]
 *   --tocFile  File name (without .ts) from src/context/table-of-contents/offline-docs/
 *   --version  Version string passed to the build (default: "main")
 *
 * - Runs Next.js static export (passes NEXT_PUBLIC_OFFLINE_TOC_FILE and STATIC_BUILD_VERSION as env vars)
 * - Merges all CSS into one file and rewrites image url()s to assets/
 * - Copies static and content-referenced images into the output
 * - Rewrites HTML so stylesheets and links are relative (scripts untouched)
 * - Flattens output: keeps only docs/, moves it to the build root, and fixes link paths
 */

import fs from 'fs/promises';
import { readFileSync } from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load .env files for local development — Netlify CI provides these as real env vars.
for (const envFile of ['.env.local', '.env']) {
  try { process.loadEnvFile(path.resolve(process.cwd(), envFile)); } catch {}
}

const OUT_DIR = path.join(process.cwd(), 'out');

const DOCS_DIR = path.join(OUT_DIR, 'docs');
const NEXT_STATIC_DIR = path.join(OUT_DIR, '_next', 'static');
const NEXT_CSS_DIR = path.join(NEXT_STATIC_DIR, 'css');
const MERGED_CSS_PATH = path.join(DOCS_DIR, 'styles.css');
const ASSETS_DIR = path.join(DOCS_DIR, 'assets');
const OFFLINE_DOCS_DIR = path.join(process.cwd(), 'src', 'context', 'table-of-contents', 'offline-docs');
const OFFLINE_TOC_SELECTED_PATH = path.join(process.cwd(), 'src', 'context', 'toc-data', 'offline-toc-selected.ts');

// Get tocFile and version from command line arguments
function parseCliArgs(): { tocFile: string; version: string } {
  let tocFile = '';
  let version = 'main';
  for (const arg of process.argv.slice(2)) {
    const m = arg.match(/^--(\w+)=(.+)$/);
    if (m?.[1] === 'tocFile') tocFile = m[2].replace(/\.ts$/, '');
    if (m?.[1] === 'version') version = m[2];
  }
  return { tocFile, version };
}

async function validateTocFile(tocFile: string): Promise<void> {
  const tocFilePath = path.join(OFFLINE_DOCS_DIR, `${tocFile}.ts`);
  try {
    await fs.access(tocFilePath);
  } catch {
    const files = await fs.readdir(OFFLINE_DOCS_DIR);
    const names = files.filter((f) => f.endsWith('.ts')).map((f) => `  ${f.replace('.ts', '')}`);
    console.error(`Error: TOC file "${tocFile}" not found.\nAvailable options:\n${names.join('\n')}`);
    process.exit(1);
  }
  console.log(`TOC file: ${tocFile}`);
}

/** Writes a re-export of the selected TOC file to offline-toc-selected.ts. */
async function setupOfflineToc(tocFile: string, version: string): Promise<void> {
  const content =
    `// Auto-generated by scripts/build-offline.ts — do not edit manually.\n` +
    `// Run: pnpm build:offline --tocFile=${tocFile} --version=${version} to regenerate.\n` +
    `export { toc } from '@/context/table-of-contents/offline-docs/${tocFile}';\n`;
  await fs.writeFile(OFFLINE_TOC_SELECTED_PATH, content, 'utf-8');
  console.log(`Offline TOC selected: ${tocFile} (version: ${version})`);
}

function runNextBuild(version: string): void {
  // Copy content images into public/docs/images so the static export emits them
  // to out/ (the `build:offline:generate` script runs `next build` directly and
  // does not trigger the `prebuild` image-copy hook).
  execSync('pnpm run build:images', { stdio: 'inherit' });

  execSync('pnpm run build:offline:generate', {
    stdio: 'inherit',
    env: {
      ...process.env,
      STATIC_BUILD_VERSION: version,
      NEXT_PUBLIC_STATIC_BUILD_VERSION: version,
    },
  });
}

const IMAGE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg', '.ico', '.avif']);
const isImagePath = (name: string) => IMAGE_EXTENSIONS.has(path.extname(name).toLowerCase());

function getRelativePrefix(htmlFilePath: string): string {
  const dir = path.dirname(htmlFilePath);
  const segments = path.relative(OUT_DIR, dir).split(path.sep).filter(Boolean);
  return segments.length === 0 ? './' : '../'.repeat(segments.length);
}

const stripDocsPrefix = (rest: string) => rest.replace(/^docs\/?/, '');

/** Rewrite href/src to relative paths only outside <script> (preserve RSC payload). */
function rewriteHtmlLinks(content: string, prefix: string): string {
  const scripts: string[] = [];
  const noScripts = content.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, (match) => {
    scripts.push(match);
    return `\x00S${scripts.length - 1}\x00`;
  });
  const rewritten = noScripts.replace(
    /(href|src)=["']\/(?!\/)([^"']*)["']/g,
    (_, attr, rest) => `${attr}="${prefix}${stripDocsPrefix(rest)}"`,
  );
  return rewritten.replace(/\x00S(\d+)\x00/g, (_, i) => scripts[parseInt(i, 10)] ?? '');
}

async function findImageFiles(dir: string, baseDir: string): Promise<{ src: string; rel: string }[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: { src: string; rel: string }[] = [];
  for (const e of entries) {
    const src = path.join(dir, e.name);
    const rel = path.relative(baseDir, src);
    if (e.isDirectory()) files.push(...(await findImageFiles(src, baseDir)));
    else if (e.isFile() && isImagePath(e.name)) files.push({ src, rel });
  }
  return files;
}

async function findHtmlFiles(dir: string): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) files.push(...(await findHtmlFiles(full)));
    else if (e.name.toLowerCase().endsWith('.html')) files.push(full);
  }
  return files;
}

/** Copy image files from srcDir to destDir (same relative paths). No-op if srcDir missing or no images. */
async function copyImageFilesTo(srcDir: string, destDir: string, logLabel: string): Promise<void> {
  let imageFiles: { src: string; rel: string }[];
  try {
    await fs.access(srcDir);
    imageFiles = await findImageFiles(srcDir, srcDir);
  } catch {
    return;
  }
  if (imageFiles.length === 0) return;
  for (const { src, rel } of imageFiles) {
    const dest = path.join(destDir, rel);
    await fs.mkdir(path.dirname(dest), { recursive: true });
    await fs.cp(src, dest);
  }
  console.log(`${logLabel}: ${imageFiles.length}`);
}

async function mergeCssIntoOutput(): Promise<void> {
  try {
    await fs.access(NEXT_CSS_DIR);
  } catch {
    console.log('No _next/static/css, skipping CSS merge.');
    return;
  }
  const entries = await fs.readdir(NEXT_CSS_DIR, { withFileTypes: true });
  const cssFiles = entries
    .filter((e) => e.isFile() && e.name.toLowerCase().endsWith('.css'))
    .map((e) => path.join(NEXT_CSS_DIR, e.name))
    .sort();
  if (cssFiles.length === 0) return;
  const chunks = await Promise.all(cssFiles.map((f) => fs.readFile(f, 'utf-8')));
  let merged = chunks.join('\n');
  // Image url()s → relative assets/ so they work after we remove _next; other url()s stay absolute (e.g. fonts) and may 404 offline
  merged = merged.replace(/url\(["']?\/_next\/static\/([^"')]+)["']?\)/g, (_, rest) => {
    const norm = rest.replace(/\\/g, '/');
    return isImagePath(norm) ? `url("assets/${norm}")` : `url("/_next/static/${norm}")`;
  });
  await fs.mkdir(path.dirname(MERGED_CSS_PATH), { recursive: true });
  await fs.writeFile(MERGED_CSS_PATH, merged, 'utf-8');
  console.log(`Merged ${cssFiles.length} CSS file(s) into styles.css`);
}

/** Match one or more Next stylesheet links (so we replace the group with a single link). */
const STYLE_LINKS_RE =
  /(<link(?=[^>]*rel=["']stylesheet["'])(?=[^>]*href=["']\/_next\/static\/css\/[^"']+["'])[^>]*>\s*)+/gi;

async function replaceCssLinksInHead(htmlFiles: string[]): Promise<void> {
  for (const filePath of htmlFiles) {
    const content = await fs.readFile(filePath, 'utf-8');
    const headEnd = content.indexOf('</head>');
    if (headEnd === -1) continue;
    const head = content.slice(0, headEnd);
    const rest = content.slice(headEnd);
    const relativeToCss = path.relative(path.dirname(filePath), MERGED_CSS_PATH).split(path.sep).join('/');
    const newHead = head.replace(STYLE_LINKS_RE, `<link rel="stylesheet" href="${relativeToCss}">`);
    if (newHead !== head) await fs.writeFile(filePath, newHead + rest, 'utf-8');
  }
}

async function keepOnlyDocs(): Promise<void> {
  const entries = await fs.readdir(OUT_DIR, { withFileTypes: true });
  for (const e of entries) {
    if (e.name === 'docs') continue;
    await fs.rm(path.join(OUT_DIR, e.name), { recursive: true });
  }
}

async function moveDocsContentsUp(): Promise<void> {
  const entries = await fs.readdir(DOCS_DIR, { withFileTypes: true });
  for (const e of entries) {
    await fs.rename(path.join(DOCS_DIR, e.name), path.join(OUT_DIR, e.name));
  }
  await fs.rmdir(DOCS_DIR);
}

async function removeAllTxtFiles(dir: string): Promise<void> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const fullPath = path.join(dir, e.name);
    if (e.isDirectory()) {
      await removeAllTxtFiles(fullPath);
    }
    if (e.isFile() && e.name.toLowerCase().endsWith('.txt')) {
      await fs.rm(fullPath);
    }
  }
}

interface OfflineUIModule {
  /** HTML marker string that must be present for this module to activate. */
  detect: string;
  /** Filename under offline-ui/ to inline as a <script> before </body>. */
  jsFile: string;
  /** Optional inline CSS to inject before </head>. */
  headStyle?: string;
}

// Each entry describes one offline UI enhancement. Order matters: more specific
// detect strings (e.g. 'offline-collapsible-nav') must come before substrings
// they contain (e.g. 'offline-collapsible') to avoid double-injecting styles.
const OFFLINE_UI_MODULES: OfflineUIModule[] = [
  {
    detect: 'data-lgid="lg-tabs"',
    jsFile: 'tabs.js',
    // Override the default LeafyGreen tab activation behavior to show the green underline.
    headStyle: `<style>
  [data-lgid="lg-tabs-tab_list"] [role="tab"][aria-selected="true"]::after {
    background-color: #00A35C;
    transform: scaleX(1);
  }
</style>`,
  },
  {
    detect: 'offline-collapsible-nav',
    jsFile: 'sidenav-collapsible.js',
    // Rotate the always-rendered CaretDown icon 180° to look like CaretUp when closed.
    headStyle: `<style>
  .offline-collapsible-nav:not(.nav-open) svg[aria-label="Caret Down Icon"] {
    transform: rotate(180deg);
  }
</style>`,
  },
  {
    detect: 'offline-collapsible',
    jsFile: 'collapsible.js',
    // Rotate the ChevronRight icon 90° clockwise to look like ChevronDown when open.
    headStyle: `<style>
  details.offline-collapsible[open] summary button svg {
    transform: rotate(90deg);
  }
</style>`,
  },
  { detect: 'offline-composable', jsFile: 'composable-tutorial.js' },
  { detect: 'data-io-toggle', jsFile: 'io-code.js' },
  { detect: 'data-testid="leafygreen-code-panel"', jsFile: 'code-copy.js' },
];

const loadedOfflineUIModules = OFFLINE_UI_MODULES.map((m) => ({
  ...m,
  script: `<script>\n${readFileSync(path.join(__dirname, 'offline-ui', m.jsFile), 'utf-8')}\n</script>`,
}));

function applyOfflineUI(content: string): string {
  for (const { detect, script, headStyle } of loadedOfflineUIModules) {
    if (!content.includes(detect)) continue;
    if (headStyle) content = content.replace(/<\/head>/i, headStyle + '\n</head>');
    content = content.replace(/<\/body>/i, script + '\n</body>');
  }
  return content;
}

async function postProcess(): Promise<void> {
  const htmlFiles = await findHtmlFiles(OUT_DIR);
  for (const filePath of htmlFiles) {
    const content = await fs.readFile(filePath, 'utf-8');
    const prefix = getRelativePrefix(filePath);
    let rewritten = rewriteHtmlLinks(content, prefix);
    rewritten = applyOfflineUI(rewritten);
    if (rewritten !== content) await fs.writeFile(filePath, rewritten, 'utf-8');
  }
}

// Minimum conservative byte size a fully-rendered page is expected to reach.
// A page that passes the layout-shell check but is still suspiciously small
const MIN_PAGE_BYTES = 40_000;

/**
 * Verify that each HTML file was fully server-rendered and correctly
 * post-processed.  Checks are grouped into four failure classes:
 *
 * 1. SSR / Emotion – Emotion SSR must have run so LeafyGreen styles are
 *    inlined. Missing styles means a client component (or context provider)
 *    returned null during static generation.
 *
 * 2. Content  – The page body must not be an empty layout shell, must
 *    reach a minimum byte size, and must not silently resolve to a 404 page.
 *
 * 3. Post-processing – CSS must have been merged into a single styles.css
 *    reference; raw /_next/static/css/ links indicate the merge step failed.
 *    All in-HTML navigation links must have been rewritten to relative paths.
 *
 * 4. Next.js RSC  – The React Server Components hydration payload
 *    (self.__next_f) must be present; its absence means next build did not
 *    produce a complete static export for that route.
 */
async function verifyOutput(): Promise<void> {
  const htmlFiles = await findHtmlFiles(OUT_DIR);
  const failures: { file: string; reason: string }[] = [];

  for (const filePath of htmlFiles) {
    const content = await fs.readFile(filePath, 'utf-8');
    const rel = path.relative(OUT_DIR, filePath);

    // 1. SSR / Emotion
    if (!content.includes('<style data-emotion=')) {
      failures.push({
        file: rel,
        reason: 'missing <style data-emotion="…"> — Emotion SSR did not run',
      });
    }

    // 2. Content
    if (/<div[^>]+layout_layout[^>]+>\s*<\/div>/.test(content)) {
      failures.push({
        file: rel,
        reason: 'body is an empty layout shell — page content did not render',
      });
    }

    if (content.length < MIN_PAGE_BYTES) {
      failures.push({
        file: rel,
        reason: `file is only ${content.length} bytes (< ${MIN_PAGE_BYTES}) — content may be partially missing`,
      });
    }

    // 3. Post-processing
    if (/<link[^>]+href=["']\/_next\/static\/css\/[^"']+["']/i.test(content)) {
      failures.push({
        file: rel,
        reason: 'raw /_next/static/css/ <link> still present — CSS merge step may have failed',
      });
    }

    if (!content.includes('styles.css')) {
      failures.push({
        file: rel,
        reason: 'merged styles.css reference not found — CSS merge step may have failed',
      });
    }

    if (/<a\b[^>]+href=["']\/docs\/[^"']*["']/i.test(content)) {
      failures.push({
        file: rel,
        reason: 'found absolute /docs/ href in an <a> tag — link-rewriting step may have failed',
      });
    }

    // 4. Next.js RSC payload
    if (!content.includes('self.__next_f')) {
      failures.push({
        file: rel,
        reason: 'missing RSC payload (self.__next_f) — Next.js static export may be incomplete for this route',
      });
    }
  }

  const failedFileSet = new Set(failures.map((f) => f.file));
  const totalPages = htmlFiles.length;
  const allPagesFailed = failures.length > 0 && totalPages > 0 && failedFileSet.size === totalPages;

  const diagnosticBlock =
    '\nLikely causes by failure class:\n' +
    '  SSR / Emotion\n' +
    '    • A React context provider (e.g. UnifiedTocProvider) returned null during SSG\n' +
    '    • A "use client" component calls useEffect/browser hooks that skip SSR\n' +
    '  Content\n' +
    '    • CONTENT_MDX_DIR does not contain the expected .mdx files\n' +
    '    • pnpm convert:rst-to-mdx was not run before the build\n' +
    '    • loadMDX returned null for the route\n' +
    '  Post-processing\n' +
    '    • mergeCssIntoOutput or replaceCssLinksInHead did not run / threw an error\n' +
    '    • postProcess (rewriteHtmlLinks) did not run / threw an error\n' +
    '  Next.js RSC\n' +
    '    • next build did not generate a static HTML file for this route\n' +
    '    • The page called notFound() or threw during static generation\n';

  if (failures.length > 0) {
    if (allPagesFailed) {
      console.error('\nOffline build verification FAILED:');
      for (const { file, reason } of failures) {
        console.error(`  ✗ ${file}: ${reason}`);
      }
      console.error(diagnosticBlock);
      process.exit(1);
    }

    console.warn('\nOffline build verification: some pages did not pass every check (other pages are OK):');
    for (const { file, reason } of failures) {
      console.warn(`  ⚠ ${file}: ${reason}`);
    }
    console.warn(diagnosticBlock);
  }

  if (failures.length === 0) {
    console.log(
      `Verified ${htmlFiles.length} HTML file(s): SSR styles present, content rendered, ` +
        `CSS merged, links rewritten, RSC payload intact.`,
    );
  } else if (!allPagesFailed) {
    const passedCount = totalPages - failedFileSet.size;
    console.log(
      `Verified with warnings: ${passedCount} of ${totalPages} HTML file(s) passed all checks; ` +
        `${failedFileSet.size} file(s) had issues (see above).`,
    );
  }
}

/** Depth-first search for the first item that has a navigable url. */
function findFirstTocUrl(items: { url?: string; isExternal?: boolean; items?: unknown[] }[]): string | null {
  for (const item of items) {
    if (item.url && !item.isExternal) return item.url;
    if (item.items) {
      const found = findFirstTocUrl(item.items as { url?: string; isExternal?: boolean; items?: unknown[] }[]);
      if (found) return found;
    }
  }
  return null;
}

/**
 * Write an index.html at the OUT_DIR root that immediately redirects to the first
 * page of the offline TOC. This lets users open the zip/folder and land on real content.
 */
async function writeRootRedirect(tocFile: string, version: string): Promise<void> {
  const tocFilePath = path.join(OFFLINE_DOCS_DIR, `${tocFile}.ts`);
  const mod = (await import(pathToFileURL(tocFilePath).href)) as {
    toc: { url?: string; isExternal?: boolean; items?: unknown[] }[];
  };
  const firstUrl = findFirstTocUrl(mod.toc);
  if (!firstUrl) {
    console.warn('Could not determine first TOC URL; skipping root index.html creation.');
    return;
  }
  // Replace :version placeholder with the build version (e.g. /docs/:version/… → /docs/:version/…).
  const resolvedUrl = firstUrl.replace(/:version/g, version);

  // Strip the /docs/ prefix and point directly to index.html so browsers open
  // the file correctly over file:// (bare directory URLs don't auto-serve index.html).
  // e.g. /docs/management → management/index.html
  const relativePath = resolvedUrl.replace(/^\/docs\/?/, '').replace(/\/?$/, '/') + 'index.html';
  const html = [
    '<!DOCTYPE html>',
    '<html>',
    '  <head>',
    '    <meta charset="utf-8">',
    `    <meta http-equiv="refresh" content="0; url=${relativePath}">`,
    `    <link rel="canonical" href="${relativePath}">`,
    '    <title>Redirecting\u2026</title>',
    `    <script>window.location.replace(${JSON.stringify(relativePath)});</script>`,
    '  </head>',
    '  <body>',
    `    <p>Redirecting to <a href="${relativePath}">${relativePath}</a>\u2026</p>`,
    '  </body>',
    '</html>',
  ].join('\n');
  await fs.writeFile(path.join(OUT_DIR, 'index.html'), html, 'utf-8');
  console.log(`Root redirect: index.html → ${relativePath}`);
}

async function main(): Promise<void> {
  const { tocFile, version } = parseCliArgs();

  if (!tocFile) {
    console.error('Error: --tocFile is required.\nUsage: pnpm build:offline --tocFile=ai-models --version=main');
    process.exit(1);
  }

  // TODO: DOP-6894 validate content directory - not needed but good to have
  await validateTocFile(tocFile);
  await setupOfflineToc(tocFile, version);
  runNextBuild(version);

  try {
    await fs.access(OUT_DIR);
  } catch {
    console.error(`Output directory ${OUT_DIR} not found.`);
    process.exit(1);
  }

  await mergeCssIntoOutput();
  await fs.mkdir(ASSETS_DIR, { recursive: true });
  await copyImageFilesTo(NEXT_STATIC_DIR, ASSETS_DIR, 'Static images');

  const htmlFiles = await findHtmlFiles(OUT_DIR);
  await replaceCssLinksInHead(htmlFiles);

  await keepOnlyDocs();
  await moveDocsContentsUp();
  await removeAllTxtFiles(OUT_DIR);
  await postProcess();
  await verifyOutput();
  await writeRootRedirect(tocFile, version);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
