/**
 * Offline docs build: produces a static snapshot that works from the filesystem (e.g. file:// or a zip).
 *
 * Usage: pnpm build:offline --tocFile=<name> [--version=<version>] [--tocDir=<dir>]
 *   --tocFile  File name (without .ts) from src/context/table-of-contents/<tocDir>/
 *   --version  Version string passed to the build (default: "main")
 *   --tocDir   TOC directory under table-of-contents/ (default: "offline-docs";
 *              use "legacy-docs" for a frozen EOL snapshot)
 *
 * - Runs Next.js static export (passes NEXT_PUBLIC_OFFLINE_TOC_FILE and STATIC_BUILD_VERSION as env vars)
 * - Merges all CSS into one file and rewrites _next url()s (fonts, images) to assets/
 * - Copies static media and content-referenced images into the output
 * - Rewrites HTML so stylesheets and links are relative (scripts untouched)
 * - Lifts the exported public/docs/images payload to the build root and prunes _next/
 */

import fs from 'fs/promises';
import { readFileSync } from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load .env files for local development — Netlify CI provides these as real env vars.
for (const envFile of ['.env.local', '.env']) {
  try { process.loadEnvFile(path.resolve(process.cwd(), envFile)); } catch {}
}

const OUT_DIR = path.join(process.cwd(), 'out');

// The static export sets no basePath, so pages land at out/<path>/index.html.
// out/docs/ is only the verbatim copy of public/docs/ — no pages live there.
const NEXT_DIR = path.join(OUT_DIR, '_next');
const DOCS_DIR = path.join(OUT_DIR, 'docs');
const EXPORTED_IMAGES_DIR = path.join(DOCS_DIR, 'images');
const NEXT_STATIC_DIR = path.join(NEXT_DIR, 'static');
const NEXT_CSS_DIR = path.join(NEXT_STATIC_DIR, 'css');
const NEXT_MEDIA_DIR = path.join(NEXT_STATIC_DIR, 'media');
const MERGED_CSS_PATH = path.join(OUT_DIR, 'styles.css');
const ASSETS_DIR = path.join(OUT_DIR, 'assets');
const ASSETS_MEDIA_DIR = path.join(ASSETS_DIR, 'media');
const IMAGES_DIR = path.join(OUT_DIR, 'images');
const TOC_PARENT_DIR = path.join(process.cwd(), 'src', 'context', 'table-of-contents');
const ALLOWED_TOC_DIRS = new Set(['offline-docs', 'legacy-docs']);
const OFFLINE_TOC_SELECTED_PATH = path.join(process.cwd(), 'src', 'context', 'toc-data', 'offline-toc-selected.ts');
const DIR_NAME_MAP_FILE = path.join(process.cwd(), 'src', 'generated', 'dir-name-to-prefix.json');

type OfflineBuildArgs = { tocFile: string; version: string; tocDir: string };

function tocDirPath(tocDir: string): string {
  return path.join(TOC_PARENT_DIR, tocDir);
}

function parseCliArgs(): OfflineBuildArgs {
  let tocFile = '';
  let version = 'main';
  let tocDir = 'offline-docs';
  for (const arg of process.argv.slice(2)) {
    const m = arg.match(/^--(\w+)=(.+)$/);
    if (m?.[1] === 'tocFile') tocFile = m[2].replace(/\.ts$/, '');
    if (m?.[1] === 'version') version = m[2];
    if (m?.[1] === 'tocDir') tocDir = m[2].replace(/\/$/, '');
  }
  if (!ALLOWED_TOC_DIRS.has(tocDir)) {
    console.error(
      `Error: --tocDir must be one of: ${[...ALLOWED_TOC_DIRS].join(', ')}. Got "${tocDir}".`,
    );
    process.exit(1);
  }
  return { tocFile, version, tocDir };
}

async function validateTocFile(tocFile: string, tocDir: string): Promise<void> {
  const dir = tocDirPath(tocDir);
  const tocFilePath = path.join(dir, `${tocFile}.ts`);
  try {
    await fs.access(tocFilePath);
  } catch {
    const files = await fs.readdir(dir).catch(() => [] as string[]);
    const names = files.filter((f) => f.endsWith('.ts')).map((f) => `  ${f.replace('.ts', '')}`);
    console.error(
      `Error: TOC file "${tocFile}" not found in ${tocDir}/.\nAvailable options:\n${names.join('\n')}`,
    );
    process.exit(1);
  }
  console.log(`TOC file: ${tocDir}/${tocFile}`);
}

/** Writes a re-export of the selected TOC file to offline-toc-selected.ts. */
async function setupOfflineToc(tocFile: string, version: string, tocDir: string): Promise<void> {
  const content =
    `// Auto-generated by scripts/build-offline.ts — do not edit manually.\n` +
    `// Run: pnpm build:offline --tocFile=${tocFile} --version=${version} --tocDir=${tocDir} to regenerate.\n` +
    `export { toc } from '@/context/table-of-contents/${tocDir}/${tocFile}';\n`;
  await fs.writeFile(OFFLINE_TOC_SELECTED_PATH, content, 'utf-8');
  console.log(`Offline TOC selected: ${tocDir}/${tocFile} (version: ${version})`);
}

/**
 * Fail fast if the dir-name-to-prefix map is missing or empty. load-mdx uses it to
 * resolve page URLs to content-mdx files; without it every route resolves to a 404
 * and the static export silently produces empty pages (only caught later, after a
 * full build, by verifyOutput). Better to stop before the expensive build.
 *
 * In CI this file is written by the nextjs-ssg-extension onPreBuild step; locally it
 * is generated by `pnpm build:prefix-map` (requires Cluster0 DB access).
 */
async function assertPrefixMap(): Promise<void> {
  const rel = path.relative(process.cwd(), DIR_NAME_MAP_FILE);
  let parsed: unknown = null;
  try {
    parsed = JSON.parse(await fs.readFile(DIR_NAME_MAP_FILE, 'utf-8'));
  } catch {
    // Missing or unparseable — handled by the emptiness check below.
  }
  if (!parsed || typeof parsed !== 'object' || Object.keys(parsed as object).length === 0) {
    console.error(
      `\nOffline build prerequisite missing or empty: ${rel}\n` +
        'load-mdx uses this prefix map to resolve page URLs to content-mdx files; without it\n' +
        'every route resolves to 404 and the build produces empty pages.\n' +
        '  • In CI it is written by the nextjs-ssg-extension onPreBuild step.\n' +
        '  • Locally, generate it with: pnpm build:prefix-map (requires Cluster0 DB access).\n',
    );
    process.exit(1);
  }
}

function runNextBuild(version: string): void {
  // build:offline:generate runs `next build` directly, so npm's `prebuild` hook
  // never fires. Run the parts of that hook the offline export needs, by hand:
  //  - build:mdx-to-md — `next build` type-checks the whole project, including the
  //    /api/markdown route that imports mdx-to-md's types; a stale dist fails the build.
  //  - build:images — copy content images into public/docs/images so the static export
  //    emits them to out/ (also writes image-dimensions.json).
  execSync('pnpm run build:mdx-to-md', { stdio: 'inherit' });
  execSync('pnpm run build:images', { stdio: 'inherit' });

  execSync('pnpm run build:offline:generate', {
    stdio: 'inherit',
    env: {
      ...process.env,
      STATIC_BUILD_VERSION: version,
      NEXT_PUBLIC_STATIC_BUILD_VERSION: version,
    },
  });
}

function getRelativePrefix(htmlFilePath: string): string {
  const dir = path.dirname(htmlFilePath);
  const segments = path.relative(OUT_DIR, dir).split(path.sep).filter(Boolean);
  return segments.length === 0 ? './' : '../'.repeat(segments.length);
}

const stripDocsPrefix = (rest: string) => rest.replace(/^docs\/?/, '');

/** Rewrite href/src to relative paths only outside <script> (preserve RSC payload). */
function rewriteHtmlLinks(content: string, prefix: string): string {
  const scripts: string[] = [];
  const noScripts = content.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, (match) => {
    scripts.push(match);
    return `\x00S${scripts.length - 1}\x00`;
  });
  const rewritten = noScripts.replace(
    /(href|src)=["']\/(?!\/)([^"']*)["']/g,
    (_, attr, rest) => `${attr}="${prefix}${stripDocsPrefix(rest)}"`,
  );
  return rewritten.replace(/\x00S(\d+)\x00/g, (_, i) => scripts[parseInt(i, 10)] ?? '');
}

async function findHtmlFiles(dir: string): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) files.push(...(await findHtmlFiles(full)));
    else if (e.name.toLowerCase().endsWith('.html')) files.push(full);
  }
  return files;
}

/**
 * Copy _next/static/media (fonts and CSS-referenced images) to assets/media, so the
 * url()s rewritten by mergeCssIntoOutput resolve after _next is pruned.
 */
async function copyStaticMedia(): Promise<void> {
  try {
    await fs.access(NEXT_MEDIA_DIR);
  } catch {
    return;
  }
  await fs.cp(NEXT_MEDIA_DIR, ASSETS_MEDIA_DIR, { recursive: true });
  const files = await fs.readdir(NEXT_MEDIA_DIR);
  console.log(`Static media: ${files.length}`);
}

async function mergeCssIntoOutput(): Promise<void> {
  try {
    await fs.access(NEXT_CSS_DIR);
  } catch {
    console.log('No _next/static/css, skipping CSS merge.');
    return;
  }
  const entries = await fs.readdir(NEXT_CSS_DIR, { withFileTypes: true });
  const cssFiles = entries
    .filter((e) => e.isFile() && e.name.toLowerCase().endsWith('.css'))
    .map((e) => path.join(NEXT_CSS_DIR, e.name))
    .sort();
  if (cssFiles.length === 0) return;
  const chunks = await Promise.all(cssFiles.map((f) => fs.readFile(f, 'utf-8')));
  let merged = chunks.join('\n');
  // Point every _next asset (fonts, images) at the copy in assets/, which survives the prune.
  merged = merged.replace(
    /url\(["']?\/_next\/static\/([^"')]+)["']?\)/g,
    (_, rest) => `url("assets/${rest.replace(/\\/g, '/')}")`,
  );
  await fs.mkdir(path.dirname(MERGED_CSS_PATH), { recursive: true });
  await fs.writeFile(MERGED_CSS_PATH, merged, 'utf-8');
  console.log(`Merged ${cssFiles.length} CSS file(s) into styles.css`);
}

/** Match one or more Next stylesheet links (so we replace the group with a single link). */
const STYLE_LINKS_RE =
  /(<link(?=[^>]*rel=["']stylesheet["'])(?=[^>]*href=["']\/_next\/static\/css\/[^"']+["'])[^>]*>\s*)+/gi;

async function replaceCssLinksInHead(htmlFiles: string[]): Promise<void> {
  for (const filePath of htmlFiles) {
    const content = await fs.readFile(filePath, 'utf-8');
    const headEnd = content.indexOf('</head>');
    if (headEnd === -1) continue;
    const head = content.slice(0, headEnd);
    const rest = content.slice(headEnd);
    const relativeToCss = path.relative(path.dirname(filePath), MERGED_CSS_PATH).split(path.sep).join('/');
    const newHead = head.replace(STYLE_LINKS_RE, `<link rel="stylesheet" href="${relativeToCss}">`);
    if (newHead !== head) await fs.writeFile(filePath, newHead + rest, 'utf-8');
  }
}

/**
 * Content images export to out/docs/images (from public/docs/images), but the HTML
 * references them at images/ because rewriteHtmlLinks strips the `docs/` prefix.
 * The rest of out/docs is generated sitemap/objects.inv scaffolding we don't ship.
 */
async function liftContentImages(): Promise<void> {
  try {
    await fs.rename(EXPORTED_IMAGES_DIR, IMAGES_DIR);
    console.log('Lifted content images to images/');
  } catch {
    // No images for this docset.
  }
  await fs.rm(DOCS_DIR, { recursive: true, force: true });
}

// Dead weight in an offline bundle: Next's build output and 404 export, plus the
// unified TOC data (~3.2 MB) that only the online site fetches.
const PRUNED_OUT_ENTRIES = ['_next', '404', '404.html', 'unified-toc.json', 'unified-docsets.json'];

/** Run after the CSS merge and media copy, which pull what the bundle needs out of _next/. */
async function pruneNonContentArtifacts(): Promise<void> {
  for (const name of PRUNED_OUT_ENTRIES) {
    await fs.rm(path.join(OUT_DIR, name), { recursive: true, force: true });
  }
}

async function removeAllTxtFiles(dir: string): Promise<void> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const fullPath = path.join(dir, e.name);
    if (e.isDirectory()) {
      await removeAllTxtFiles(fullPath);
    }
    if (e.isFile() && e.name.toLowerCase().endsWith('.txt')) {
      await fs.rm(fullPath);
    }
  }
}

interface OfflineUIModule {
  /** HTML marker string that must be present for this module to activate. */
  detect: string;
  /** Filename under offline-ui/ to inline as a <script> before </body>. */
  jsFile: string;
  /** Optional inline CSS to inject before </head>. */
  headStyle?: string;
}

// Each entry describes one offline UI enhancement. Order matters: more specific
// detect strings (e.g. 'offline-collapsible-nav') must come before substrings
// they contain (e.g. 'offline-collapsible') to avoid double-injecting styles.
const OFFLINE_UI_MODULES: OfflineUIModule[] = [
  {
    detect: 'data-lgid="lg-tabs"',
    jsFile: 'tabs.js',
    // Override the default LeafyGreen tab activation behavior to show the green underline.
    headStyle: `<style>
  [data-lgid="lg-tabs-tab_list"] [role="tab"][aria-selected="true"]::after {
    background-color: #00A35C;
    transform: scaleX(1);
  }
</style>`,
  },
  {
    detect: 'offline-collapsible-nav',
    jsFile: 'sidenav-collapsible.js',
    // Rotate the always-rendered CaretDown icon 180° to look like CaretUp when closed.
    headStyle: `<style>
  .offline-collapsible-nav:not(.nav-open) svg[aria-label="Caret Down Icon"] {
    transform: rotate(180deg);
  }
</style>`,
  },
  {
    detect: 'offline-collapsible',
    jsFile: 'collapsible.js',
    // Rotate the ChevronRight icon 90° clockwise to look like ChevronDown when open.
    headStyle: `<style>
  details.offline-collapsible[open] summary button svg {
    transform: rotate(90deg);
  }
</style>`,
  },
  { detect: 'offline-composable', jsFile: 'composable-tutorial.js' },
  { detect: 'data-io-toggle', jsFile: 'io-code.js' },
  { detect: 'data-testid="leafygreen-code-panel"', jsFile: 'code-copy.js' },
];

const loadedOfflineUIModules = OFFLINE_UI_MODULES.map((m) => ({
  ...m,
  script: `<script>\n${readFileSync(path.join(__dirname, 'offline-ui', m.jsFile), 'utf-8')}\n</script>`,
}));

function applyOfflineUI(content: string): string {
  for (const { detect, script, headStyle } of loadedOfflineUIModules) {
    if (!content.includes(detect)) continue;
    if (headStyle) content = content.replace(/<\/head>/i, headStyle + '\n</head>');
    content = content.replace(/<\/body>/i, script + '\n</body>');
  }
  return content;
}

async function postProcess(): Promise<void> {
  const htmlFiles = await findHtmlFiles(OUT_DIR);
  for (const filePath of htmlFiles) {
    const content = await fs.readFile(filePath, 'utf-8');
    const prefix = getRelativePrefix(filePath);
    let rewritten = rewriteHtmlLinks(content, prefix);
    rewritten = applyOfflineUI(rewritten);
    if (rewritten !== content) await fs.writeFile(filePath, rewritten, 'utf-8');
  }
}

// Minimum conservative byte size a fully-rendered page is expected to reach.
// A page that passes the layout-shell check but is still suspiciously small
const MIN_PAGE_BYTES = 40_000;

/**
 * Verify that each HTML file was fully server-rendered and correctly
 * post-processed.  Checks are grouped into four failure classes:
 *
 * 1. SSR / Emotion – Emotion SSR must have run so LeafyGreen styles are
 *    inlined. Missing styles means a client component (or context provider)
 *    returned null during static generation.
 *
 * 2. Content  – The page body must not be an empty layout shell, must
 *    reach a minimum byte size, and must not silently resolve to a 404 page.
 *
 * 3. Post-processing – CSS must have been merged into a single styles.css
 *    reference; raw /_next/static/css/ links indicate the merge step failed.
 *    All in-HTML navigation links must have been rewritten to relative paths.
 *
 * 4. Next.js RSC  – The React Server Components hydration payload
 *    (self.__next_f) must be present; its absence means next build did not
 *    produce a complete static export for that route.
 */
async function verifyOutput(): Promise<void> {
  const htmlFiles = await findHtmlFiles(OUT_DIR);

  // Without this, the loop below runs zero times and reports "Verified 0 HTML file(s)".
  if (htmlFiles.length === 0) {
    console.error(
      '\nOffline build verification FAILED: no HTML files found in out/.\n' +
        'The static export produced no pages, or a post-processing step deleted them.\n' +
        '  • Check that next build emitted out/<path>/index.html files\n' +
        '  • Check that liftContentImages/pruneNonContentArtifacts did not remove page content\n',
    );
    process.exit(1);
  }

  const failures: { file: string; reason: string }[] = [];

  for (const filePath of htmlFiles) {
    const content = await fs.readFile(filePath, 'utf-8');
    const rel = path.relative(OUT_DIR, filePath);

    // 1. SSR / Emotion
    if (!content.includes('<style data-emotion=')) {
      failures.push({
        file: rel,
        reason: 'missing <style data-emotion="…"> — Emotion SSR did not run',
      });
    }

    // 2. Content
    if (/<div[^>]+layout_layout[^>]+>\s*<\/div>/.test(content)) {
      failures.push({
        file: rel,
        reason: 'body is an empty layout shell — page content did not render',
      });
    }

    if (content.length < MIN_PAGE_BYTES) {
      failures.push({
        file: rel,
        reason: `file is only ${content.length} bytes (< ${MIN_PAGE_BYTES}) — content may be partially missing`,
      });
    }

    // 3. Post-processing
    if (/<link[^>]+href=["']\/_next\/static\/css\/[^"']+["']/i.test(content)) {
      failures.push({
        file: rel,
        reason: 'raw /_next/static/css/ <link> still present — CSS merge step may have failed',
      });
    }

    if (!content.includes('styles.css')) {
      failures.push({
        file: rel,
        reason: 'merged styles.css reference not found — CSS merge step may have failed',
      });
    }

    if (/<a\b[^>]+href=["']\/docs\/[^"']*["']/i.test(content)) {
      failures.push({
        file: rel,
        reason: 'found absolute /docs/ href in an <a> tag — link-rewriting step may have failed',
      });
    }

    // 4. Next.js RSC payload
    if (!content.includes('self.__next_f')) {
      failures.push({
        file: rel,
        reason: 'missing RSC payload (self.__next_f) — Next.js static export may be incomplete for this route',
      });
    }
  }

  const failedFileSet = new Set(failures.map((f) => f.file));
  const totalPages = htmlFiles.length;
  const allPagesFailed = failures.length > 0 && totalPages > 0 && failedFileSet.size === totalPages;

  const diagnosticBlock =
    '\nLikely causes by failure class:\n' +
    '  SSR / Emotion\n' +
    '    • A React context provider (e.g. UnifiedTocProvider) returned null during SSG\n' +
    '    • A "use client" component calls useEffect/browser hooks that skip SSR\n' +
    '  Content\n' +
    '    • CONTENT_MDX_DIR does not contain the expected .mdx files\n' +
    '    • pnpm convert:rst-to-mdx was not run before the build\n' +
    '    • loadMDX returned null for the route\n' +
    '  Post-processing\n' +
    '    • mergeCssIntoOutput or replaceCssLinksInHead did not run / threw an error\n' +
    '    • postProcess (rewriteHtmlLinks) did not run / threw an error\n' +
    '  Next.js RSC\n' +
    '    • next build did not generate a static HTML file for this route\n' +
    '    • The page called notFound() or threw during static generation\n';

  if (failures.length > 0) {
    if (allPagesFailed) {
      console.error('\nOffline build verification FAILED:');
      for (const { file, reason } of failures) {
        console.error(`  ✗ ${file}: ${reason}`);
      }
      console.error(diagnosticBlock);
      process.exit(1);
    }

    console.warn('\nOffline build verification: some pages did not pass every check (other pages are OK):');
    for (const { file, reason } of failures) {
      console.warn(`  ⚠ ${file}: ${reason}`);
    }
    console.warn(diagnosticBlock);
  }

  if (failures.length === 0) {
    console.log(
      `Verified ${htmlFiles.length} HTML file(s): SSR styles present, content rendered, ` +
        `CSS merged, links rewritten, RSC payload intact.`,
    );
  } else if (!allPagesFailed) {
    const passedCount = totalPages - failedFileSet.size;
    console.log(
      `Verified with warnings: ${passedCount} of ${totalPages} HTML file(s) passed all checks; ` +
        `${failedFileSet.size} file(s) had issues (see above).`,
    );
  }
}

/** Depth-first search for the first item that has a navigable url. */
function findFirstTocUrl(items: { url?: string; isExternal?: boolean; items?: unknown[] }[]): string | null {
  for (const item of items) {
    if (item.url && !item.isExternal && !item.url.startsWith('http')) return item.url;
    if (item.items) {
      const found = findFirstTocUrl(item.items as { url?: string; isExternal?: boolean; items?: unknown[] }[]);
      if (found) return found;
    }
  }
  return null;
}

/**
 * Write an index.html at the OUT_DIR root that immediately redirects to the first
 * page of the offline TOC. This lets users open the zip/folder and land on real content.
 */
async function writeRootRedirect(tocFile: string, version: string, tocDir: string): Promise<void> {
  const tocFilePath = path.join(tocDirPath(tocDir), `${tocFile}.ts`);
  const mod = (await import(pathToFileURL(tocFilePath).href)) as {
    toc: { url?: string; isExternal?: boolean; items?: unknown[] }[];
  };
  const firstUrl = findFirstTocUrl(mod.toc);
  if (!firstUrl) {
    console.warn('Could not determine first TOC URL; skipping root index.html creation.');
    return;
  }
  // Replace :version placeholder with the build version (e.g. /docs/:version/… → /docs/:version/…).
  const resolvedUrl = firstUrl.replace(/:version/g, version);

  // Strip the /docs/ prefix and point directly to index.html so browsers open
  // the file correctly over file:// (bare directory URLs don't auto-serve index.html).
  // e.g. /docs/management → management/index.html
  const relativePath = resolvedUrl.replace(/^\/docs\/?/, '').replace(/\/?$/, '/') + 'index.html';
  const html = [
    '<!DOCTYPE html>',
    '<html>',
    '  <head>',
    '    <meta charset="utf-8">',
    `    <meta http-equiv="refresh" content="0; url=${relativePath}">`,
    `    <link rel="canonical" href="${relativePath}">`,
    '    <title>Redirecting\u2026</title>',
    `    <script>window.location.replace(${JSON.stringify(relativePath)});</script>`,
    '  </head>',
    '  <body>',
    `    <p>Redirecting to <a href="${relativePath}">${relativePath}</a>\u2026</p>`,
    '  </body>',
    '</html>',
  ].join('\n');
  await fs.writeFile(path.join(OUT_DIR, 'index.html'), html, 'utf-8');
  console.log(`Root redirect: index.html → ${relativePath}`);
}

async function main(): Promise<void> {
  const { tocFile, version, tocDir } = parseCliArgs();

  if (!tocFile) {
    console.error(
      'Error: --tocFile is required.\nUsage: pnpm build:offline --tocFile=ai-models --version=main [--tocDir=offline-docs]',
    );
    process.exit(1);
  }

  // TODO: DOP-6894 validate content directory - not needed but good to have
  await validateTocFile(tocFile, tocDir);
  await setupOfflineToc(tocFile, version, tocDir);
  await assertPrefixMap();
  runNextBuild(version);

  try {
    await fs.access(OUT_DIR);
  } catch {
    console.error(`Output directory ${OUT_DIR} not found.`);
    process.exit(1);
  }

  await mergeCssIntoOutput();
  await copyStaticMedia();

  const htmlFiles = await findHtmlFiles(OUT_DIR);
  await replaceCssLinksInHead(htmlFiles);

  await liftContentImages();
  await pruneNonContentArtifacts();
  await removeAllTxtFiles(OUT_DIR);
  await postProcess();
  await verifyOutput();
  await writeRootRedirect(tocFile, version, tocDir);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
