/**
 * Generates all-redirects.ts from all *-redirects.json files in src/redirects/.
 *
 * The generated file is a static-import barrel used by the Next.js app (webpack
 * bundling). next.config.mjs uses readdirSync directly and does not depend on
 * this file.
 *
 * Run this script whenever a new *-redirects.json is added.
 * It is chained automatically by: pnpm import:redirects
 */
import fs from 'node:fs';
import path from 'node:path';

const REDIRECTS_DIR = path.resolve(__dirname, '../src/redirects');
const TS_OUTPUT = path.join(REDIRECTS_DIR, 'all-redirects.ts');
// Flat data read by the Deno edge function, which can't import the .ts barrel.
const JSON_OUTPUT = path.join(REDIRECTS_DIR, 'all-redirects.json');

function discoverRedirectFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    // Exclude the generated aggregate, which also ends with -redirects.json.
    .filter((f) => f.endsWith('-redirects.json') && f !== 'all-redirects.json')
    .sort();
}

// Converts a hyphen-separated stem to a camelCase identifier suffixed with "Redirects".
// e.g. "app-services" → "appServicesRedirects"
export function toCamelCase(stem: string): string {
  return stem.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()) + 'Redirects';
}

export function generateJsonFile(dir: string): string {
  const files = discoverRedirectFiles(dir);
  if (files.length === 0) {
    throw new Error(`No *-redirects.json files found in ${dir}`);
  }
  const all = files.flatMap((filename) =>
    JSON.parse(fs.readFileSync(path.join(dir, filename), 'utf-8')),
  );
  return JSON.stringify(all, null, 2) + '\n';
}

export function generateTsFile(dir: string): string {
  const files = discoverRedirectFiles(dir);
  if (files.length === 0) {
    throw new Error(`No *-redirects.json files found in ${dir}`);
  }

  const entries = files.map((filename) => {
    const stem = filename.replace(/-redirects\.json$/, '');
    const identifier = toCamelCase(stem);
    return { filename, identifier };
  });

  const importLines = entries.map((e) => `import ${e.identifier} from './${e.filename}';`);
  const spreadLines = entries.map((e) => `  ...${e.identifier},`);

  return [
    '// Auto-generated by scripts/generate-all-redirects.ts — do not edit manually.',
    '// Run: pnpm generate:redirects to regenerate.',
    "import type { RedirectEntry } from './redirect-utils';",
    ...importLines,
    '',
    'export const allRedirects: RedirectEntry[] = [',
    ...spreadLines,
    '] as RedirectEntry[];',
    '',
  ].join('\n');
}

if (require.main === module) {
  const tsContent = generateTsFile(REDIRECTS_DIR);
  fs.writeFileSync(TS_OUTPUT, tsContent, 'utf-8');
  console.log(`Generated ${path.relative(process.cwd(), TS_OUTPUT)}`);

  const jsonContent = generateJsonFile(REDIRECTS_DIR);
  fs.writeFileSync(JSON_OUTPUT, jsonContent, 'utf-8');
  console.log(`Generated ${path.relative(process.cwd(), JSON_OUTPUT)}`);
}
