[
  {
    _id: ObjectId('573a13a5f29313caabd14377'),
    fullplot: "In this high-adventure sequel the baby geniuses find themselves at the center of a nefarious scheme led by powerful media mogul Bill Biscane. Joining the babies in their battle against evil is a legendary baby named Kahuna. Part ultra-cool spy, part superhero, Kahuna joins babies Archie, Finkleman, Alex and Rosita in a race against time to stop the villainous Biscane from using his state-of-the-art satellite system to control the minds of the world's population.",
    imdb: { rating: 1.9, votes: 23802, id: 270846 },
    year: 2004,
    plot: "A group of smart-talking toddlers find themselves at the center of a media mogul's experiment to crack the code to baby talk. The toddlers must race against time for the sake of babies everywhere.",
    genres: [ 'Comedy', 'Family', 'Sci-Fi' ],
    rated: 'PG',
    metacritic: 9,
    title: 'Superbabies: Baby Geniuses 2',
    lastupdated: '2015-09-15 03:59:20.790000000',
    languages: [ 'English' ],
    writers: [ 'Steven Paul (story)', 'Gregory Poppen (screenplay)' ],
    type: 'movie',
    tomatoes: {
      website: 'http://www.sonypictures.com/movies/superbabiesbabygeniuses2/index.html',
      viewer: { rating: 2, numReviews: 6978, meter: 20 },
      dvd: ISODate('2005-01-04T00:00:00.000Z'),
      critic: { rating: 2.2, numReviews: 45, meter: 0 },
      boxOffice: '$9.0M',
      consensus: "A startling lack of taste pervades Superbabies, a sequel offering further proof that bad jokes still aren't funny when coming from the mouths of babes.",
      rotten: 45,
      production: 'Sony',
      lastUpdated: ISODate('2015-09-11T18:35:27.000Z'),
      fresh: 0
    },
    poster: 'https://m.media-amazon.com/images/M/MV5BNjY4NjM3MjQ2OF5BMl5BanBnXkFtZTcwOTc3NzYyMQ@@._V1_SY1000_SX677_AL_.jpg',
    num_mflix_comments: 1,
    released: ISODate('2004-08-27T00:00:00.000Z'),
    awards: { wins: 0, nominations: 4, text: '4 nominations.' },
    countries: [ 'Germany', 'UK', 'USA' ],
    cast: [ 'Jon Voight', 'Scott Baio', 'Vanessa Angel', 'Skyler Shaye' ],
    directors: [ 'Bob Clark' ],
    runtime: 88
  },
  {
    _id: ObjectId('573a13b8f29313caabd4cb69'),
    plot: "Nate moves to L.A. to track down Cristabel, the woman he's been in love with since childhood, only to discover that his plan to woo her only has one hurdle to overcome: what to do with June, Cristabel's ever-present, not-so-hot best friend? What's even more complicating is Nate's growing feelings for June, whose true beauty starts to emerge.",
    genres: [ 'Comedy', 'Romance' ],
    runtime: 91,
    metacritic: 7,
    rated: 'PG-13',
    cast: [
      'Paris Hilton',
      'Joel David Moore',
      'Christine Lakin',
      'Johann Urb'
    ],
    poster: 'https://m.media-amazon.com/images/M/MV5BMTA2NDc1ODUxNDZeQTJeQWpwZ15BbWU3MDQ1MjM1NTE@._V1_SY1000_SX677_AL_.jpg',
    title: 'The Hottie & the Nottie',
    fullplot: "Nate moves to L.A. to track down Cristabel, the woman he's been in love with since childhood, only to discover that his plan to woo her only has one hurdle to overcome: what to do with June, Cristabel's ever-present, not-so-hot best friend? What's even more complicating is Nate's growing feelings for June, whose true beauty starts to emerge.",
    languages: [ 'English' ],
    released: ISODate('2008-02-21T00:00:00.000Z'),
    directors: [ 'Tom Putnam' ],
    writers: [ 'Heidi Ferrer' ],
    awards: { wins: 4, nominations: 4, text: '4 wins & 4 nominations.' },
    lastupdated: '2015-09-07 00:02:31.210000000',
    year: 2008,
    imdb: { rating: 1.9, votes: 32639, id: 804492 },
    countries: [ 'USA' ],
    type: 'movie',
    tomatoes: {
      website: 'http://www.thehottieandthenottie.com',
      viewer: { rating: 2.6, numReviews: 12777, meter: 31 },
      dvd: ISODate('2008-05-06T00:00:00.000Z'),
      critic: { rating: 2.4, numReviews: 67, meter: 4 },
      lastUpdated: ISODate('2015-09-14T18:13:26.000Z'),
      consensus: "The Hottie and the Nottie is a crass, predictable, and ineptly staged gross-out comedy that serves little purpose beyond existing as another monument to Paris Hilton's vanity.",
      rotten: 64,
      production: 'Regent Releasing',
      fresh: 3
    },
    num_mflix_comments: 0
  },
  {
    _id: ObjectId('573a13c1f29313caabd64b87'),
    fullplot: 'Will, Lisa, and two of their friends attempt to flee man-made and natural disasters and encounter Batman, Hancock, The Hulk, Indiana Jones, Hannah Montana, Michael Jackson, Beowulf, the Love Guru, Iron Man, rabid chipmunks amongst others in their seemingly vain efforts to seek help and shelter from unknown threats.',
    imdb: { rating: 1.9, votes: 71382, id: 1213644 },
    year: 2008,
    plot: 'Over the course of one evening, an unsuspecting group of twenty-somethings find themselves bombarded by a series of natural disasters and catastrophic events.',
    genres: [ 'Comedy' ],
    rated: 'PG-13',
    metacritic: 15,
    title: 'Disaster Movie',
    lastupdated: '2015-09-07 00:21:55.677000000',
    languages: [ 'English' ],
    writers: [ 'Jason Friedberg', 'Aaron Seltzer' ],
    type: 'movie',
    tomatoes: {
      website: 'http://disastermovie.net/',
      viewer: { rating: 2.2, numReviews: 128557, meter: 19 },
      dvd: ISODate('2009-01-06T00:00:00.000Z'),
      critic: { rating: 1.8, numReviews: 70, meter: 1 },
      boxOffice: '$14.2M',
      consensus: 'Returning to their seemingly bottomless well of flatulence humor, racial stereotypes, and stale pop culture gags, Jason Friedberg and Aaron Seltzer have produced what is arguably their worst Movie yet.',
      rotten: 69,
      production: 'Lionsgate',
      lastUpdated: ISODate('2015-08-26T18:02:48.000Z'),
      fresh: 1
    },
    poster: 'https://m.media-amazon.com/images/M/MV5BMTIzMDQyNDgwNl5BMl5BanBnXkFtZTcwMDA0MTc3MQ@@._V1_SY1000_SX677_AL_.jpg',
    num_mflix_comments: 2,
    released: ISODate('2008-08-29T00:00:00.000Z'),
    awards: { wins: 0, nominations: 6, text: '6 nominations.' },
    countries: [ 'USA' ],
    cast: [
      'Matt Lanter',
      'Vanessa Lachey',
      "Gary 'G. Thang' Johnson",
      'Nicole Parker'
    ],
    directors: [ 'Jason Friedberg', 'Aaron Seltzer' ],
    runtime: 87
  },
  {
    _id: ObjectId('573a13cef29313caabd8709c'),
    plot: 'Follows Justin Bieber with some footage of performances from his 2010 concert tour.',
    genres: [ 'Documentary', 'Music' ],
    runtime: 105,
    metacritic: 52,
    cast: [ 'Justin Bieber', 'Boys II Men', 'Miley Cyrus', 'Sean Kingston' ],
    num_mflix_comments: 0,
    poster: 'https://m.media-amazon.com/images/M/MV5BMTY0NDQzMjIzOF5BMl5BanBnXkFtZTcwNDk2NzczNA@@._V1_SY1000_SX677_AL_.jpg',
    title: 'Justin Bieber: Never Say Never',
    fullplot: "The camera follows Justin Bieber (1994- ) during the ten days leading up to his August, 2010, sold-out show at Madison Square Garden. Footage of these ten days of concerts, rehearsals, and down time with boyhood friends, his mom, and his entourage is inter-cut with home movies, old photos, and interviews showing a musical prodigy who loves to perform, comes to the attention of an Atlanta agent via YouTube, impresses Usher, and rockets to international stardom soon after his 15th birthday. His manager emphasizes the importance of social media and of Justin's work ethic and personality in making him a star; the camera emphasizes Bieber's look. His mom and grandparents shine.",
    languages: [ 'English' ],
    released: ISODate('2011-02-11T00:00:00.000Z'),
    directors: [ 'Jon M. Chu' ],
    rated: 'G',
    awards: { wins: 2, nominations: 6, text: '2 wins & 6 nominations.' },
    lastupdated: '2015-08-23 00:33:04.327000000',
    year: 2011,
    imdb: { rating: 1.6, votes: 73548, id: 1702443 },
    countries: [ 'USA' ],
    type: 'movie',
    tomatoes: {
      website: 'http://www.JustinBieberNeverSayNever.com',
      viewer: { rating: 3.5, numReviews: 61961, meter: 65 },
      dvd: ISODate('2011-05-13T00:00:00.000Z'),
      critic: { rating: 5.8, numReviews: 102, meter: 64 },
      boxOffice: '$73.0M',
      consensus: "As a tour documentary, it's rather uninspired -- but as a 3D glimpse of a building pop culture phenomenon, Never Say Never is undeniably entertaining.",
      rotten: 37,
      production: 'Paramount Pictures',
      lastUpdated: ISODate('2015-08-18T19:05:06.000Z'),
      fresh: 65
    }
  },
  {
    _id: ObjectId('573a13e7f29313caabdc8b22'),
    plot: 'A backstage and on-stage look at Justin Bieber during his rise to super stardom.',
    genres: [ 'Documentary', 'Music' ],
    runtime: 92,
    metacritic: 39,
    rated: 'PG',
    cast: [ 'Justin Bieber', 'Scooter Braun', 'Ryan Good', 'Usher Raymond' ],
    poster: 'https://m.media-amazon.com/images/M/MV5BMjgzMDgxNjU1Ml5BMl5BanBnXkFtZTgwMDc3NTI2MDE@._V1_SY1000_SX677_AL_.jpg',
    title: "Justin Bieber's Believe",
    fullplot: 'A backstage and on-stage look at Justin Bieber during his rise to super stardom.',
    languages: [ 'English' ],
    released: ISODate('2013-12-25T00:00:00.000Z'),
    directors: [ 'Jon M. Chu' ],
    writers: [ 'Sarah Landman' ],
    awards: { wins: 0, nominations: 1, text: '1 nomination.' },
    lastupdated: '2015-08-25 00:58:14.853000000',
    year: 2013,
    imdb: { rating: 1.6, votes: 16511, id: 3165608 },
    countries: [ 'USA' ],
    type: 'movie',
    num_mflix_comments: 0
  },
  {
    _id: ObjectId('573a13f4f29313caabde0c23'),
    plot: 'Kirk is enjoying the annual Christmas party extravaganza thrown by his sister until he realizes he needs to help out Christian, his brother-in-law who has a bad case of the bah-humbugs. ...',
    genres: [ 'Comedy', 'Family' ],
    runtime: 80,
    metacritic: 18,
    rated: 'PG',
    cast: [
      'Kirk Cameron',
      'Darren Doane',
      'Bridgette Cameron',
      'David Shannon'
    ],
    poster: 'https://m.media-amazon.com/images/M/MV5BMTc3MTc3Njc5MV5BMl5BanBnXkFtZTgwNzU3NDE4MjE@._V1_SY1000_SX677_AL_.jpg',
    title: 'Saving Christmas',
    fullplot: "Kirk is enjoying the annual Christmas party extravaganza thrown by his sister until he realizes he needs to help out Christian, his brother-in-law who has a bad case of the bah-humbugs. Kirk's fresh look at Christmas provides Christians the chance to see Christ is where He has always been: at the center of our Christmas celebrations and traditions.",
    languages: [ 'English' ],
    released: ISODate('2014-11-14T00:00:00.000Z'),
    directors: [ 'Darren Doane' ],
    writers: [ 'Darren Doane', 'Cheston Hervey' ],
    awards: { wins: 4, nominations: 2, text: '4 wins & 2 nominations.' },
    lastupdated: '2015-08-16 00:12:45.527000000',
    year: 2014,
    imdb: { rating: 1.6, votes: 9744, id: 4009460 },
    countries: [ 'USA' ],
    type: 'movie',
    num_mflix_comments: 0
  }
]