name = "search"
title = "MongoDB Search"

sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

intersphinx = [ "https://www.mongodb.com/docs/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv",
                "https://www.mongodb.com/docs/atlas/app-services/objects.inv",
                "https://www.mongodb.com/docs/atlas/cli/objects.inv",
                "https://www.mongodb.com/docs/compass/current/objects.inv",
                "https://www.mongodb.com/docs/database-tools/objects.inv",
                "https://www.mongodb.com/docs/kubernetes/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/objects.inv",
                "https://www.mongodb.com/docs/drivers/csharp/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/go/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/java/sync/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/kotlin/coroutine/current/objects.inv",
                "https://www.mongodb.com/docs/languages/kotlin/kotlin-sync-driver/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/node/current/objects.inv",
                "https://www.mongodb.com/docs/php-library/current/objects.inv",
                "https://www.mongodb.com/docs/languages/python/pymongo-driver/objects.inv",
                "https://www.mongodb.com/docs/ruby-driver/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/rust/current/objects.inv",
                "https://www.mongodb.com/docs/languages/scala/scala-driver/current/objects.inv",
                "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/mongodb-shell/objects.inv",
                "https://www.mongodb.com/docs/search/self-managed/objects.inv",
                "https://www.mongodb.com/docs/vector-search/objects.inv",
                "https://www.mongodb.com/docs/voyageai/objects.inv",
              ]

toc_landing_pages = [
    "/search/query/operators-collectors/overview",
    "/search/index/analyzers/overview",
    "/search/index/analyzers/custom",
    "/search/index/define-field-mappings",
    "/search/about/design-patterns",
    "/search/query/accuracy",
    "/search/query/query-ref",
    "/search/query/aggregation-stages/search/",
    "/search/query/aggregation-stages/searchMeta/",
    "/search/index/manage-indexes",
    "/search/about/searching",
    "/search/performance/performance-options",
    "/search/query/query-syntax",
    "/search/query/explain",
    "/search/performance/overview",
    "/search/tutorial",
    "/search/index/index-definitions",
    "/search/tutorial/cross-collection-tutorials",
    "/search/query/search-options",
]

[constants]
atlas-admin-api = "Atlas Administration API"
atlas-cli = "Atlas CLI"
atlas-ui = "Atlas UI"
avs = "MongoDB Vector Search"
az-bs = "Azure Blob Storage"
Cloud-Backup = "Cloud Backup"
Compass = "`Compass <https://www.mongodb.com/try/download/compass>`__"
database-deployment = "cluster"
database-deployments = "clusters"
dedicated-clusters = "dedicated clusters"
Flex-cluster = "Flex cluster"
Flex-clusters = "Flex clusters"
Flex-Clusters = "Flex Clusters"
Free-cluster = "Free cluster"
Free-clusters = "Free clusters"
Free-Cluster = "Free Cluster"
fts = "MongoDB Search"
k8s-op-short = "Kubernetes Operator"
mongosh = ":binary:`~bin.mongosh`"
oauth-2 = "`OAuth 2.0 <https://oauth.net/2/>`__"
playground = "MongoDB Search Playground"
service = "Atlas"

[substitutions]
ann = ":abbr:`ANN (Approximate Nearest Neighbor)`"
api = ":abbr:`API (Application Programming Interface)`"
aws = ":abbr:`AWS (Amazon Web Services)`"
azure = ":abbr:`Azure (Microsoft Azure)`"
bson = ":abbr:`BSON (Binary Javascript Object Notation)`"
compass = "MongoDB Compass"
dns = ":abbr:`DNS (Domain Name System)`"
enn = ":abbr:`ENN (Exact Nearest Neighbor)`"
fts = "MongoDB Search"
gcp = "Google Cloud"
hnsw = "`Hierarchical Navigable Small Worlds <https://arxiv.org/abs/1603.09320>`__"
http = ":abbr:`HTTP (HyperText Transport Protocol)`"
https = ":abbr:`HTTPS (Secure HyperText Transport Protocol)`"
json = ":abbr:`JSON (Javascript Object Notation)`"
kms = ":abbr:`KMS (Key Management Service)`"
mdb-feedback = "`MongoDB Feedback <https://feedback.mongodb.com/>`__"
mongod = ":binary:`~bin.mongod`"
nvme = ":abbr:`NVMe (non-volatile memory express)`"
pcre = ":abbr:`PCRE (Perl Compatible Regular Expressions)`"
s3 = ":abbr:`S3 (Simple Storage Service)`"
service = "Atlas"
ssd = ":abbr:`SSD (Solid State Disk)`"
ui-org-menu = ":icon-mms:`office` :guilabel:`Organizations` menu"
url = ":abbr:`URL (Uniform Resource Locator)`"
voyage = "Voyage AI"
vpc = ":abbr:`VPC (Virtual Private Cloud)`"

[[composables]]
id = "deployment-type"
title = "Deployment Type"
default = "atlas"
options = [
   {id = "atlas", title = "Atlas (Cloud)"},
   {id = "local", title = "Atlas (Local)"},
   {id = "self", title = "Self-Managed (On-Premises)"},
   {id = "local-onprem", title = "Atlas (Local) or Self-Managed (On-Premises)"},
]

[[composables]]
id = "interface"
title = "Interface"
default = "mongosh"
options = [
   {id = "compass", title = "Compass"},
   {id = "mongosh", title = "MongoDB Shell"},
   {id = "atlas-ui", title = "Atlas UI"},
   {id = "driver", title = "Driver"},
   {id = "playground", title = "Search Playground"},
   {id = "atlas-cli", title = "Atlas CLI"},
   {id = "atlas-api", title = "Atlas Administration API"},
]

[[composables]]
id = "language"
title = "Language"
default = "nodejs"
dependencies = [{interface = "driver"}]
options = [
  {id = "c", title = "C"},
  {id = "csharp", title = "C#"},
  {id = "cpp", title = "C++"},
  {id = "go", title = "Go"},
  {id = "java-async", title = "Java (Async)"},
  {id = "java-sync", title = "Java (Sync)"},
  {id = "kotlin", title = "Kotlin"},
  {id = "kotlin-coroutine", title = "Kotlin (Coroutine)"},
  {id = "motor", title = "Motor"},
  {id = "nodejs", title = "Node.js"},
  {id = "php", title = "PHP"},
  {id = "python", title = "Python"},
  {id = "ruby", title = "Ruby"},
  {id = "rust", title = "Rust"},
  {id = "scala", title = "Scala"},
]

[[composables]]
id = "vector-search-type"
title = "Vector Search"
default = "ann"
options = [
   {id = "ann", title = "Approximate Nearest Neighbor"},
   {id = "enn", title = "Exact Nearest Neighbor"}
]

[[composables]]
id = "prefilter-type"
title = "Prefilter"
default = "compound"
options = [
   {id = "compound", title = "Compound"},
   {id = "fuzzy", title = "Fuzzy"}
]

[[composables]]
id = "hybrid-search-type"
title = "Hybrid Search Type"
default = "rank-fusion"
options = [
   {id = "rank-fusion", title = "Rank Fusion"},
   {id = "score-fusion", title = "Score Fusion"},
   {id = "semantic-boost", title = "Semantic Boosting"}
]

[[banners]]
# knnBeta operator deprecation
targets = [
        "query/operators-collectors/knn-beta.txt",
        "index/field-types/knn-vector.txt"
        ]
variant = "warning"
value = """\
        The Atlas Search knnVector field type and knnBeta operator are now deprecated. Instead, we recommend that you use the :atlas:`vector </search/field-types/vector-type/>` index type and :atlas:`vectorSearch </search/operators-collectors/vectorSearch/>` operator in your $search pipeline stage.
        """

[[banners]]
# temporary banner for Atlas Search RN
targets = [
    "changelog.txt",
]

variant = "warning"
value = """
        Atlas Vector Search is now generally available for both your development and production deployments. To learn more about the MongoDB Vector Search release, see the `Atlas Vector Search Changelog <https://www.mongodb.com/docs/vector-search/changelog>`__.
        """

[[banners]]
# dateFacet outdated
targets = [
    "index/field-types/date-facet-type.txt",
]
variant = "warning"
value = """\
        dateFacet is now outdated. Use :ref:`date <bson-data-types-date>` instead. To learn more, see :ref:`fts-facet-type-differences`.
        """

[[banners]]
# numberFacet outdated
targets = [
    "index/field-types/number-facet-type.txt",
]
variant = "warning"
value = """\
        numberFacet is now outdated. Use :ref:`number <bson-data-types-number>` instead. To learn more, see :ref:`fts-facet-type-differences`.
        """

[[banners]]
# stringFacet outdated
targets = [
    "index/field-types/string-facet-type.txt",
]
variant = "warning"
value = """\
        stringFacet is now outdated. Use :ref:`token <bson-data-types-token>` instead. To learn more, see :ref:`fts-facet-type-differences`.
        """

[[banners]]
# DOCSP-47898 Search with On-Prem deployments in Public Preview
targets = [
        "tutorial.txt"
        ]
variant = "warning"
value = """\
        MongoDB Search and MongoDB Vector Search with MongoDB Community is in Preview. The feature and the corresponding documentation might change at any time during the Preview period. To learn more, see `Preview Features <https://www.mongodb.com/docs/preview-features/>`__.\
        """