[build]
publish = "dist"
base = "content/rust"

[build.environment]
REPO_NAME = "docs-rust"
SECRETS_SCAN_ENABLED = "false"
MUT_COMMANDS_ENABLED = "false"
ALLOW_INACTIVE_VERSIONS = "true"

[context.production.environment]
ENV = "dotcomprd"

[context.preprd.environment]
ENV = "dotcomstg"

[context.deploy-preview.environment]
ENV = "prd"

[context.branch-deploy.environment]
ENV = "prd"

[context.preview-server.environment]
ENV = "prd"

[context.dev.environment]
ENV = "stg"


### OFFLINE REDIRECTS
### ALIAS REDIRECTS
### VERSION CONSOLIDATION
### PAGE-SPECIFIC REDIRECTS
### WILDCARD REDIRECTS
### CATCH ALLS
## redirects any pages not at any of the active versions to current (makes eols technically unnecessary)

### OFFLINE REDIRECTS

### ALIAS REDIRECTS

[[redirects]]
from = "/docs/drivers/rust/v3.x/*"
to = "/docs/drivers/rust/current/:splat"
status = 302

### VERSION CONSOLIDATION
# v3.x consolidation
[[redirects]]
from = "/docs/drivers/rust/v3.5/*"
to = "/docs/drivers/rust/v3.x/:splat"

[[redirects]]
from = "/docs/drivers/rust/v3.4/*"
to = "/docs/drivers/rust/v3.x/:splat"

[[redirects]]
from = "/docs/drivers/rust/v3.3/*"
to = "/docs/drivers/rust/v3.x/:splat"

[[redirects]]
from = "/docs/drivers/rust/v3.2/*"
to = "/docs/drivers/rust/v3.x/:splat"

[[redirects]]
from = "/docs/drivers/rust/v3.1/*"
to = "/docs/drivers/rust/v3.x/:splat"

[[redirects]]
from = "/docs/drivers/rust/v3.0/*"
to = "/docs/drivers/rust/v3.x/:splat"

# v2.x consolidation
[[redirects]]
from = "/docs/drivers/rust/v2.8/*"
to = "/docs/drivers/rust/v2.x/:splat"

[[redirects]]
from = "/docs/drivers/rust/v2.7/*"
to = "/docs/drivers/rust/v2.x/:splat"

### PAGE LEVELS

[[redirects]]
from = "/docs/drivers/rust/:version/fundamentals/"
to = "/docs/rust/:version/fundamentals/stable-api/"

[[redirects]]
from = "/docs/drivers/rust/:version/fundamentals/connections/"
to = "/docs/rust/:version/fundamentals/connections/connection-guide/"

[[redirects]]
from = "/docs/drivers/rust/:version/fundamentals/crud/"
to = "/docs/rust/:version/fundamentals/crud/compound-operations/"

[[redirects]]
from = "/docs/drivers/rust/:version/fundamentals/crud/read-operations/"
to = "/docs/rust/:version/fundamentals/crud/read-operations/retrieve/"

[[redirects]]
from = "/docs/drivers/rust/:version/fundamentals/crud/write-operations/"
to = "/docs/rust/:version/fundamentals/crud/write-operations/insert/"

[[redirects]]
from = "/docs/drivers/rust/:version/fundamentals/monitoring/"
to = "/docs/rust/:version/fundamentals/monitoring/cluster-monitoring/"

[[redirects]]
from = "/docs/drivers/rust/:version/fundamentals/aggregation/vector-search/"
to = "/docs/drivers/rust/:version/fundamentals/vector-search/"

### PAGE-LEVEL REDIRECTS
## v2.x
[[redirects]]
from = "/docs/drivers/rust/v2.x/fundamentals/aggregation/vector-search/"
to = "/docs/drivers/rust/v2.x/fundamentals/aggregation/"

## v3.x
[[redirects]]
from = "/docs/drivers/rust/v3.x/fundamentals/aggregation/vector-search/"
to = "/docs/drivers/rust/v3.x/fundamentals/aggregation/"

### WILDCARD REDIRECTS

[[redirects]]
from = "/docs/drivers/rust/:version/compatibility/"
to = "/docs/drivers/compatibility/?driver-language=rust"

### COMPREHENSIVE COVERAGE REDIRECTS - UPCOMING

[[redirects]]
from = "/docs/drivers/rust/upcoming/quick-start/"
to = "/docs/drivers/rust/upcoming/get-started/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/quick-start/download-and-install/"
to = "/docs/drivers/rust/upcoming/get-started/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/quick-start/create-a-deployment/"
to = "/docs/drivers/rust/upcoming/get-started/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/quick-start/create-a-connection-string/"
to = "/docs/drivers/rust/upcoming/get-started/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/quick-start/connect-to-mongodb/"
to = "/docs/drivers/rust/upcoming/get-started/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/quick-start/next-steps/"
to = "/docs/drivers/rust/upcoming/get-started/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/connections/"
to = "/docs/drivers/rust/upcoming/connect/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/connections/network-compression/"
to = "/docs/drivers/rust/upcoming/connect/connection-options/network-compression/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/connections/connection-guide/"
to = "/docs/drivers/rust/upcoming/connect/mongodb-client/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/connections/connection-options/"
to = "/docs/drivers/rust/upcoming/connect/connection-options/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/stable-api/"
to = "/docs/drivers/rust/upcoming/connect/connection-options/stable-api/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/performance/"
to = "/docs/drivers/rust/upcoming/connect/performance/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/connection-troubleshooting/"
to = "/docs/drivers/rust/upcoming/connect/connection-troubleshooting/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/database-collection/"
to = "/docs/drivers/rust/upcoming/database-collection/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/"
to = "/docs/drivers/rust/upcoming/crud/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/write-operations/insert/"
to = "/docs/drivers/rust/upcoming/crud/insert/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/read-operations/"
to = "/docs/drivers/rust/upcoming/crud/query/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/read-operations/sort/"
to = "/docs/drivers/rust/upcoming/crud/query/specify-documents/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/read-operations/skip/"
to = "/docs/drivers/rust/upcoming/crud/query/specify-documents/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/read-operations/limit/"
to = "/docs/drivers/rust/upcoming/crud/query/specify-documents/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/read-operations/query/"
to = "/docs/drivers/rust/upcoming/crud/query/specify-query/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/read-operations/retrieve/"
to = "/docs/drivers/rust/upcoming/crud/query/retrieve/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/usage-examples/count/"
to = "/docs/drivers/rust/upcoming/crud/query/count/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/usage-examples/distinct/"
to = "/docs/drivers/rust/upcoming/crud/query/distinct/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/read-operations/cursor/"
to = "/docs/drivers/rust/upcoming/crud/query/cursor/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/read-operations/text-search/"
to = "/docs/drivers/rust/upcoming/crud/query/text-search/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/geo/"
to = "/docs/drivers/rust/upcoming/crud/query/geo/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/write-operations/"
to = "/docs/drivers/rust/upcoming/crud/insert/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/write-operations/change/"
to = "/docs/drivers/rust/upcoming/crud/update/replace/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/write-operations/delete/"
to = "/docs/drivers/rust/upcoming/crud/delete/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/write-operations/bulk/"
to = "/docs/drivers/rust/upcoming/crud/bulk/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/transactions/"
to = "/docs/drivers/rust/upcoming/crud/transactions/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/gridfs/"
to = "/docs/drivers/rust/upcoming/crud/gridfs/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/compound-operations/"
to = "/docs/drivers/rust/upcoming/crud/compound-operations/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/web-app-tutorial/"
to = "/docs/drivers/rust/upcoming/crud/web-app-tutorial/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/schema-validation/"
to = "/docs/drivers/rust/upcoming/schema-validation/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/aggregation/"
to = "/docs/drivers/rust/upcoming/aggregation/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/collations/"
to = "/docs/drivers/rust/upcoming/aggregation/collations/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/serialization/"
to = "/docs/drivers/rust/upcoming/data-formats/serialization/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/time-series/"
to = "/docs/drivers/rust/upcoming/data-formats/time-series/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/indexes/"
to = "/docs/drivers/rust/upcoming/indexes/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/indexes/atlas-search-indexes/"
to = "/docs/drivers/rust/upcoming/indexes/atlas-search-indexes/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/run-command/"
to = "/docs/drivers/rust/upcoming/run-command/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/runtimes/"
to = "/docs/drivers/rust/upcoming/runtimes/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/atlas-search/"
to = "/docs/drivers/rust/upcoming/atlas-search/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/vector-search/"
to = "/docs/drivers/rust/upcoming/vector-search/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/monitoring/"
to = "/docs/drivers/rust/upcoming/monitoring-logging/monitoring/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/monitoring/cluster-monitoring/"
to = "/docs/drivers/rust/upcoming/monitoring-logging/monitoring/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/monitoring/command-monitoring/"
to = "/docs/drivers/rust/upcoming/monitoring-logging/monitoring/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/monitoring/connection-monitoring/"
to = "/docs/drivers/rust/upcoming/monitoring-logging/monitoring/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/monitoring/change-streams/"
to = "/docs/drivers/rust/upcoming/monitoring-logging/change-streams/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/tracing-logging/"
to = "/docs/drivers/rust/upcoming/monitoring-logging/tracing-logging/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/crud/read-operations/change-streams/"
to = "/docs/drivers/rust/upcoming/monitoring-logging/change-streams/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/tls/"
to = "/docs/drivers/rust/upcoming/security/tls/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/authentication/"
to = "/docs/drivers/rust/upcoming/security/authentication/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/whats-new/"
to = "/docs/drivers/rust/upcoming/reference/release-notes/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/quick-reference/"
to = "/docs/drivers/rust/upcoming/reference/quick-reference/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/view-source/"
to = "/docs/drivers/rust/upcoming/reference/view-source/"

[[redirects]]
from = "/docs/drivers/rust/upcoming/fundamentals/"
to = "/docs/drivers/rust/upcoming/"

#Online versions: dict_keys(['upcoming', 'current', 'v3.3', 'v3.2', 'v3.1', 'v3.0', 'v2.8', 'v2.7'])

### CATCH ALLS (add slug to paths without slug)
[[redirects]]
from = "/docs/drivers/rust/upcoming/*"
to = "/docs/drivers/rust/upcoming/:splat"
status = 200

[[redirects]]
from = "/docs/drivers/rust/current/*"
to = "/docs/drivers/rust/current/:splat"
status = 200

[[redirects]]
from = "/docs/drivers/rust/*"
to = "/docs/drivers/rust/current/:splat"
