List<Document> sampleDocuments = Arrays.asList(
        new Document()
                .append("metadata", new Document()
                        .append("sensorId", 5578)
                        .append("type", "omni")
                        .append("location", new Document()
                                .append("type", "Point")
                                .append("coordinates", Arrays.asList(-77.40711, 39.03335))))
                .append("timestamp", Date.from(Instant.parse("2022-01-15T00:00:00Z")))
                .append("currentConditions", new Document()
                        .append("windDirection", 127.0)
                        .append("tempF", 71.0)
                        .append("windSpeed", 2.0)
                        .append("cloudCover", null)
                        .append("precip", 0.1)
                        .append("humidity", 94.0)),
        new Document()
                .append("metadata", new Document()
                        .append("sensorId", 5578)
                        .append("type", "omni")
                        .append("location", new Document()
                                .append("type", "Point")
                                .append("coordinates", Arrays.asList(-77.40711, 39.03335))))
                .append("timestamp", Date.from(Instant.parse("2022-01-15T00:01:00Z")))
                .append("currentConditions", new Document()
                        .append("windDirection", 128.0)
                        .append("tempF", 69.8)
                        .append("windSpeed", 2.2)
                        .append("cloudCover", null)
                        .append("precip", 0.1)
                        .append("humidity", 94.3)),
        new Document()
                .append("metadata", new Document()
                        .append("sensorId", 5579)
                        .append("type", "omni")
                        .append("location", new Document()
                                .append("type", "Point")
                                .append("coordinates", Arrays.asList(-80.19773, 25.77481))))
                .append("timestamp", Date.from(Instant.parse("2022-01-15T00:01:00Z")))
                .append("currentConditions", new Document()
                        .append("windDirection", 115.0)
                        .append("tempF", 88.0)
                        .append("windSpeed", 1.0)
                        .append("cloudCover", null)
                        .append("precip", 0.0)
                        .append("humidity", 99.0))
);
