// Auto-generated by scripts/generate-all-redirects.ts — do not edit manually.
// Run: pnpm generate:redirects to regenerate.
import type { RedirectEntry } from './redirect-utils';
import cDriverRedirects from './c-driver-redirects.json';
import compassRedirects from './compass-redirects.json';
import cppDriverRedirects from './cpp-driver-redirects.json';
import csharpRedirects from './csharp-redirects.json';
import databaseToolsRedirects from './database-tools-redirects.json';
import djangoMongodbRedirects from './django-mongodb-redirects.json';
import driversRedirects from './drivers-redirects.json';
import entityFrameworkRedirects from './entity-framework-redirects.json';
import golangRedirects from './golang-redirects.json';
import hibernateRedirects from './hibernate-redirects.json';
import javaRedirects from './java-redirects.json';
import javaRsRedirects from './java-rs-redirects.json';
import kotlinRedirects from './kotlin-redirects.json';
import kotlinSyncRedirects from './kotlin-sync-redirects.json';
import laravelMongodbRedirects from './laravel-mongodb-redirects.json';
import manualRedirects from './manual-redirects.json';
import mcpServerRedirects from './mcp-server-redirects.json';
import metaRedirects from './meta-redirects.json';
import mongodbAnalyzerRedirects from './mongodb-analyzer-redirects.json';
import mongodbIntellijRedirects from './mongodb-intellij-redirects.json';
import mongodbShellRedirects from './mongodb-shell-redirects.json';
import mongodbVscodeRedirects from './mongodb-vscode-redirects.json';
import mongoidRedirects from './mongoid-redirects.json';
import mongosyncRedirects from './mongosync-redirects.json';
import nodeRedirects from './node-redirects.json';
import opsManagerRedirects from './ops-manager-redirects.json';
import phpLibraryRedirects from './php-library-redirects.json';
import pymongoArrowDriverRedirects from './pymongo-arrow-driver-redirects.json';
import pymongoDriverRedirects from './pymongo-driver-redirects.json';
import relationalMigratorRedirects from './relational-migrator-redirects.json';
import rubyDriverRedirects from './ruby-driver-redirects.json';
import rustRedirects from './rust-redirects.json';
import scalaDriverRedirects from './scala-driver-redirects.json';
import sparkConnectorRedirects from './spark-connector-redirects.json';

export const allRedirects: RedirectEntry[] = [
  ...cDriverRedirects,
  ...compassRedirects,
  ...cppDriverRedirects,
  ...csharpRedirects,
  ...databaseToolsRedirects,
  ...djangoMongodbRedirects,
  ...driversRedirects,
  ...entityFrameworkRedirects,
  ...golangRedirects,
  ...hibernateRedirects,
  ...javaRedirects,
  ...javaRsRedirects,
  ...kotlinRedirects,
  ...kotlinSyncRedirects,
  ...laravelMongodbRedirects,
  ...manualRedirects,
  ...mcpServerRedirects,
  ...metaRedirects,
  ...mongodbAnalyzerRedirects,
  ...mongodbIntellijRedirects,
  ...mongodbShellRedirects,
  ...mongodbVscodeRedirects,
  ...mongoidRedirects,
  ...mongosyncRedirects,
  ...nodeRedirects,
  ...opsManagerRedirects,
  ...phpLibraryRedirects,
  ...pymongoArrowDriverRedirects,
  ...pymongoDriverRedirects,
  ...relationalMigratorRedirects,
  ...rubyDriverRedirects,
  ...rustRedirects,
  ...scalaDriverRedirects,
  ...sparkConnectorRedirects,
] as RedirectEntry[];
