name = "vector-search"
title = "MongoDB Vector Search"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/app-services/objects.inv",
                "https://www.mongodb.com/docs/atlas/cli/objects.inv",
                "https://www.mongodb.com/docs/atlas/architecture/current/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv",
                "https://www.mongodb.com/docs/charts/objects.inv",
                "https://www.mongodb.com/docs/compass/current/objects.inv",
                "https://www.mongodb.com/docs/database-tools/objects.inv",
                "https://www.mongodb.com/docs/drivers/objects.inv",
                "https://www.mongodb.com/docs/drivers/csharp/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/go/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/java/sync/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/kotlin/coroutine/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/node/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/rust/current/objects.inv",
                "https://www.mongodb.com/docs/kubernetes/current/objects.inv",
                "https://www.mongodb.com/docs/languages/kotlin/kotlin-sync-driver/current/objects.inv",
                "https://www.mongodb.com/docs/languages/python/pymongo-driver/objects.inv",
                "https://www.mongodb.com/docs/languages/scala/scala-driver/current/objects.inv",
                "https://www.mongodb.com/docs/mcp-server/objects.inv",
                "https://www.mongodb.com/docs/mongocli/current/objects.inv",
                "https://www.mongodb.com/docs/mongodb-shell/objects.inv",
                "https://www.mongodb.com/docs/mongosync/current/objects.inv",
                "https://www.mongodb.com/docs/php-library/current/objects.inv",
                "https://www.mongodb.com/docs/relational-migrator/objects.inv",
                "https://www.mongodb.com/docs/ruby-driver/current/objects.inv",
                "https://www.mongodb.com/docs/search/objects.inv",
                "https://www.mongodb.com/docs/search/self-managed/objects.inv",
                "https://www.mongodb.com/docs/sql-interface/objects.inv",
                "https://www.mongodb.com/docs/voyageai/objects.inv",
                "https://www.mongodb.com/docs/objects.inv",
              ]

toc_landing_pages = [
    "/about/vector-search-overview",
    "/query/aggregation-stages/vector-search-stage",
    "/benchmark/benchmark-tests",
    "/tutorials/rag",
    "/hybrid-search/hybrid-search-overview",
    "/about/use-cases"
]

[constants]
arp = "Atlas Resource Policy"
arps = "Atlas Resource Policies"
Atlas-Flex = "Atlas Flex"
atlas-cli = "Atlas CLI"
atlas-admin-api = "Atlas Administration API"
atlas-ui = "Atlas UI"
avs = "MongoDB Vector Search"
avs-filter-types = "boolean, date, objectId, numeric, string, and UUID values, including arrays of these types"
voyageai = "Voyage AI"
az-bs = "Azure Blob Storage"
Compass = "`Compass <https://www.mongodb.com/try/download/compass>`__"
Deployment = "Deployment"
database-deployment = "cluster"
Dedicated-cluster = "Dedicated cluster"
Dedicated-clusters = "Dedicated clusters"
dedicated-cluster = "dedicated cluster"
dedicated-clusters = "dedicated clusters"
deployment = "deployment"
deployments = "deployments"
Flex-cluster = "Flex cluster"
Flex-clusters = "Flex clusters"
Free-cluster = "Free cluster"
Free-clusters = "Free clusters"
fts = "MongoDB Search"
model-api-key = "model API key"
model-api-keys = "model API keys"
mongosh = ":binary:`~bin.mongosh`"
mql = ":abbr:`MQL (MongoDB Query Language)`"
playground = "MongoDB Search Playground"
service = "Atlas"

[substitutions]
ann = ":abbr:`ANN (Approximate Nearest Neighbor)`"
api = ":abbr:`API (Application Programming Interface)`"
aws = ":abbr:`AWS (Amazon Web Services)`"
azure = ":abbr:`Azure (Microsoft Azure)`"
bson = ":abbr:`BSON (Binary Javascript Object Notation)`"
compass = "MongoDB Compass"
enn = ":abbr:`ENN (Exact Nearest Neighbor)`"
fts = "MongoDB Search"
gcp = "Google Cloud"
hnsw = "`Hierarchical Navigable Small Worlds <https://arxiv.org/abs/1603.09320>`__"
http = ":abbr:`HTTP (HyperText Transport Protocol)`"
json = ":abbr:`JSON (Javascript Object Notation)`"
kms = ":abbr:`KMS (Key Management Service)`"
llm = ":abbr:`LLM (Large Language Model)`"
mongod = ":binary:`~bin.mongod`"
rag = ":abbr:`RAG (Retrieval-Augmented Generation)`"
s3 = ":abbr:`S3 (Simple Storage Service)`"
service-fullname = "MongoDB Atlas"
service = "Atlas"
srv = ":abbr:`SRV (DNS Service Record)`"
ui-org-menu = ":icon-mms:`office` :guilabel:`Organizations` menu"
url = ":abbr:`URL (Uniform Resource Locator)`"
voyage = "Voyage AI"
vpc = ":abbr:`VPC (Virtual Private Cloud)`"

[[banners]]
# DOCSP-56098 Automated Embedding in Private Preview for Community Edition
targets = [
        "vector-search/source/index/vector-search-type/*",
        "vector-search/tutorials/quick-start/*",
        "vector-search/query/aggregation-stages/vector-search-stage/*",
        ]
variant = "warning"
value = """\
            Automated Embeddings is available as a Preview feature. The feature and the corresponding documentation might change at any time during the Preview period. Do not use this feature in your production environment. We do not use any customer data from this feature to train our models at this time. To learn more, see `Preview Features <https://www.mongodb.com/docs/preview-features/>`__.\
        """

[[banners]]
# DOCSP-47898 Search with On-Prem deployments in Public Preview
targets = [
        "tutorials/vector-search-quick-start.txt"
        ]
variant = "warning"
value = """\
        MongoDB Search and MongoDB Vector Search with MongoDB Community is in Preview. The feature and the corresponding documentation might change at any time during the Preview period. To learn more, see `Preview Features <https://www.mongodb.com/docs/preview-features/>`__.\
        """

[[banners]]
# $rerank in preview
targets = [
        "vector-search/query/aggregation-stages/rerank.txt",
        "vector-search/query/native-reranking/quickstart.txt",
        "vector-search/query/native-reranking/managing.txt",
        "vector-search/query/native-reranking/billing.txt",
        ]
variant = "warning"
value = """\
            Native reranking is in Preview. The feature and the corresponding documentation might change at any time during the Preview period. Therefore, we don't recommend using this feature in production environments. We do not use any customer data from this feature to train our models at this time. To learn more, see `Preview Features <https://www.mongodb.com/docs/preview-features/>`__.\
        """

[[composables]]
id = "deployment-type"
title = "Deployment Type"
default = "atlas"
options = [
   {id = "atlas", title = "Atlas (Cloud)"},
   {id = "local", title = "Atlas (Local)"},
   {id = "self", title = "Self-Managed (On-Premises)"},
   {id = "local-onprem", title = "Atlas (Local) or Self-Managed (On-Premises)"},
]

[[composables]]
id = "interface"
title = "Interface"
default = "mongosh"
options = [
   {id = "compass", title = "Compass"},
   {id = "mongosh", title = "MongoDB Shell"},
   {id = "atlas-ui", title = "Atlas UI"},
   {id = "driver", title = "Driver"},
   {id = "playground", title = "Search Playground"},
   {id = "atlas-cli", title = "Atlas CLI"},
   {id = "atlas-api", title = "Atlas Administration API"},
]

[[composables]]
id = "language"
title = "Language"
default = "nodejs"
dependencies = [{interface = "driver"}]
options = [
  {id = "c", title = "C"},
  {id = "csharp", title = "C#"},
  {id = "cpp", title = "C++"},
  {id = "go", title = "Go"},
  {id = "java-async", title = "Java (Async)"},
  {id = "java-sync", title = "Java (Sync)"},
  {id = "kotlin", title = "Kotlin"},
  {id = "kotlin-coroutine", title = "Kotlin (Coroutine)"},
  {id = "motor", title = "Motor"},
  {id = "nodejs", title = "Node.js"},
  {id = "php", title = "PHP"},
  {id = "python", title = "Python"},
  {id = "ruby", title = "Ruby"},
  {id = "rust", title = "Rust"},
  {id = "scala", title = "Scala"},
]

[[composables]]
id = "embedding-model"
title = "Embedding Model"
default = "voyage"
options = [
   {id = "voyage", title = "Voyage AI"},
   {id = "openai", title = "OpenAI"},
   {id = "open-source", title = "Open-source"},
]

[[composables]]
id = "embedding"
title = "Embeddings"
default = "Automated"
options = [
   {id = "auto", title = "Automatically Generate"},
   {id = "byo", title = "Use Existing"},
]

[[composables]]
id = "pipeline-stage"
title = "Pipeline Stage"
default = "rank-fusion"
options = [
   {id = "rank-fusion", title = "$rankFusion"},
   {id = "score-fusion", title = "$scoreFusion"},
]

[[composables]]
id = "llm"
title = "LLM"
default = "openai"
options = [
   {id = "openai", title = "OpenAI"},
   {id = "open-source", title = "Open-source"},
]

[[composables]]
id = "data-source"
title = "Data Source"
default = "new"
options = [
   {id = "new", title = "New Data"},
   {id = "existing", title = "Existing Data"}
]

[[composables]]
id = "language-no-interface"
title = "Language"
default = "python"
options = [
  {id = "c", title = "C"},
  {id = "csharp", title = "C#"},
  {id = "cpp", title = "C++"},
  {id = "go", title = "Go"},
  {id = "java-async", title = "Java (Async)"},
  {id = "java-sync", title = "Java (Sync)"},
  {id = "kotlin", title = "Kotlin"},
  {id = "kotlin-coroutine", title = "Kotlin (Coroutine)"},
  {id = "motor", title = "Motor"},
  {id = "nodejs", title = "Node.js"},
  {id = "php", title = "PHP"},
  {id = "python", title = "Python"},
  {id = "ruby", title = "Ruby"},
  {id = "scala", title = "Scala"},
]

[[composables]]
id = "index-creation-method"
title = "Index Creation Method"
default = "driver"
options = [
  {id = "atlas-ui", title = "Atlas UI"},
  {id = "driver", title = "Driver"},
  {id = "atlas-cli", title = "Atlas CLI"},
]

[[composables]]
id = "vector-search-type"
title = "Vector Search"
default = "ann"
options = [
   {id = "ann", title = "Approximate Nearest Neighbor"},
   {id = "enn", title = "Exact Nearest Neighbor"}
]
