name = "vector-search"
title = "MongoDB Vector Search"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv",
                "https://www.mongodb.com/docs/drivers/objects.inv",
                "https://www.mongodb.com/docs/database-tools/objects.inv",
                "https://www.mongodb.com/docs/mongocli/current/objects.inv",
                "https://www.mongodb.com/docs/mongodb-shell/objects.inv",
                "https://www.mongodb.com/docs/atlas/app-services/objects.inv",
                "https://www.mongodb.com/docs/languages/python/pymongo-driver/objects.inv",
                "https://www.mongodb.com/docs/drivers/csharp/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/go/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/java/sync/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/kotlin/coroutine/current/objects.inv",
                "https://www.mongodb.com/docs/languages/kotlin/kotlin-sync-driver/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/node/current/objects.inv",
                "https://www.mongodb.com/docs/php-library/current/objects.inv",
                "https://www.mongodb.com/docs/drivers/rust/current/objects.inv",
                "https://www.mongodb.com/docs/languages/scala/scala-driver/current/objects.inv",
                "https://www.mongodb.com/docs/ruby-driver/current/objects.inv",
                "https://www.mongodb.com/docs/charts/objects.inv",
                "https://www.mongodb.com/docs/atlas/architecture/current/objects.inv",
                "https://www.mongodb.com/docs/relational-migrator/objects.inv",
                "https://www.mongodb.com/docs/mongosync/current/objects.inv",
                "https://www.mongodb.com/docs/mcp-server/objects.inv",
                "https://www.mongodb.com/docs/drivers/rust/current/objects.inv",
                "https://www.mongodb.com/docs/compass/current/objects.inv",
                "https://www.mongodb.com/docs/kubernetes/current/objects.inv",
                "https://www.mongodb.com/docs/voyageai/objects.inv",
                "https://www.mongodb.com/docs/sql-interface/objects.inv",
                "https://www.mongodb.com/docs/objects.inv",
                "https://www.mongodb.com/docs/atlas/cli/objects.inv",
              ]

toc_landing_pages = [
    "/about/vector-search-overview",
    "/query/aggregation-stages/vector-search-stage",
    "/benchmark/benchmark",
    "/tutorials/rag",
    "/hybrid-search/hybrid-search",
    "/about/use-cases"
]

[constants]
Atlas-Flex = "Atlas Flex"
atlas-cli = "Atlas CLI"
atlas-admin-api = "Atlas Administration API"
atlas-ui = "Atlas UI"
avs = "MongoDB Vector Search"
avs-filter-types = "boolean, date, objectId, numeric, string, and UUID values, including arrays of these types"
az-bs = "Azure Blob Storage"
Compass = "`Compass <https://www.mongodb.com/try/download/compass>`__"
Deployment = "Deployment"
database-deployment = "cluster"
Dedicated-cluster = "Dedicated cluster"
Dedicated-clusters = "Dedicated clusters"
dedicated-cluster = "dedicated cluster"
dedicated-clusters = "dedicated clusters"
deployment = "deployment"
deployments = "deployments"
Flex-cluster = "Flex cluster"
Flex-clusters = "Flex clusters"
Free-cluster = "Free cluster"
Free-clusters = "Free clusters"
fts = "MongoDB Search"
mongosh = ":binary:`~bin.mongosh`"
mql = ":abbr:`MQL (MongoDB Query Language)`"
playground = "MongoDB Search Playground"
service = "Atlas"

[substitutions]
ann = ":abbr:`ANN (Approximate Nearest Neighbor)`"
api = ":abbr:`API (Application Programming Interface)`"
aws = ":abbr:`AWS (Amazon Web Services)`"
azure = ":abbr:`Azure (Microsoft Azure)`"
bson = ":abbr:`BSON (Binary Javascript Object Notation)`"
compass = "MongoDB Compass"
enn = ":abbr:`ENN (Exact Nearest Neighbor)`"
gcp = "Google Cloud"
hnsw = "`Hierarchical Navigable Small Worlds <https://arxiv.org/abs/1603.09320>`__"
http = ":abbr:`HTTP (HyperText Transport Protocol)`"
json = ":abbr:`JSON (Javascript Object Notation)`"
kms = ":abbr:`KMS (Key Management Service)`"
llm = ":abbr:`LLM (Large Language Model)`"
mongod = ":binary:`~bin.mongod`"
rag = ":abbr:`RAG (Retrieval-Augmented Generation)`"
s3 = ":abbr:`S3 (Simple Storage Service)`"
service-fullname = "MongoDB Atlas"
service = "Atlas"
srv = ":abbr:`SRV (DNS Service Record)`"
ui-org-menu = ":icon-mms:`office` :guilabel:`Organizations` menu"
url = ":abbr:`URL (Uniform Resource Locator)`"
voyage = "Voyage AI"
vpc = ":abbr:`VPC (Virtual Private Cloud)`"

[[banners]]
# DOCSP-50503 Automated Embedding in Private Preview
targets = [
        "about/automated-embedding.txt"
        ]
variant = "warning"
value = """\
            This feature is in Private Preview. The feature and the corresponding documentation might change at any time during the Preview period. Therefore, do not use this feature in Production. To learn more, see `Preview Features <https://www.mongodb.com/docs/preview-features/>`__. To enable this feature for your M10 or higher cluster in your development or test environment, contact your account team. There are no charges for using this feature during the Preview period. However, standard charges for Atlas clusters still apply. To learn more, see the `MongoDB Pricing <https://www.mongodb.com/pricing>`__ page.\
        """

[[banners]]
# DOCSP-56098 Automated Embedding in Private Preview for Community Edition
targets = [
        "crud-embeddings/create-embeddings-automatic.txt"
        ]
variant = "warning"
value = """\
            Automated embedding is available as a Preview feature only for MongoDB Community Edition v8.2 and later. The feature and the corresponding documentation might change at anytime during the Preview period. To learn more, see `Preview Features <https://www.mongodb.com/docs/preview-features/>`__.\
        """

[[banners]]
# DOCSP-47898 Search with On-Prem deployments in Public Preview
targets = [
        "tutorials/vector-search-quick-start.txt"
        ]
variant = "warning"
value = """\
        MongoDB Search and MongoDB Vector Search with MongoDB Community is in Preview. The feature and the corresponding documentation might change at any time during the Preview period. To learn more, see `Preview Features <https://www.mongodb.com/docs/preview-features/>`__.\
        """

[[banners]]
# $scoreFusion and $rankFusion in preview
targets = [
        "hybrid-search/vector-search-with-full-text-search.txt",
        "hybrid-search/vector-search-with-rankfusion.txt"
        ]
variant = "warning"
value = """\
            The ``$rankFusion`` and ``$scoreFusion`` stages are available as Preview features. To learn more, see `Preview Features <https://www.mongodb.com/docs/preview-features/>`__.\
        """

[[composables]]
id = "deployment-type"
title = "Deployment Type"
default = "atlas"
options = [
   {id = "atlas", title = "Atlas (Cloud)"},
   {id = "local", title = "Atlas (Local)"},
   {id = "self", title = "Self-Managed (On-Premises)"},
   {id = "local-onprem", title = "Atlas (Local) or Self-Managed (On-Premises)"},
]

[[composables]]
id = "interface"
title = "Interface"
default = "mongosh"
options = [
   {id = "compass", title = "Compass"},
   {id = "mongosh", title = "MongoDB Shell"},
   {id = "atlas-ui", title = "Atlas UI"},
   {id = "driver", title = "Driver"},
   {id = "playground", title = "Search Playground"},
   {id = "atlas-cli", title = "Atlas CLI"},
   {id = "atlas-api", title = "Atlas Administration API"},
]

[[composables]]
id = "language"
title = "Language"
default = "nodejs"
dependencies = [{interface = "driver"}]
options = [
  {id = "c", title = "C"},
  {id = "csharp", title = "C#"},
  {id = "cpp", title = "C++"},
  {id = "go", title = "Go"},
  {id = "java-async", title = "Java (Async)"},
  {id = "java-sync", title = "Java (Sync)"},
  {id = "kotlin", title = "Kotlin"},
  {id = "kotlin-coroutine", title = "Kotlin (Coroutine)"},
  {id = "motor", title = "Motor"},
  {id = "nodejs", title = "Node.js"},
  {id = "php", title = "PHP"},
  {id = "python", title = "Python"},
  {id = "ruby", title = "Ruby"},
  {id = "rust", title = "Rust"},
  {id = "scala", title = "Scala"},
]

[[composables]]
id = "embedding-model"
title = "Embedding Model"
default = "voyage"
options = [
   {id = "voyage", title = "Voyage AI"},
   {id = "openai", title = "OpenAI"},
   {id = "open-source", title = "Open-source"},
]

[[composables]]
id = "embedding"
title = "Embeddings"
default = "Automated"
options = [
   {id = "auto", title = "Automatically Generate"},
   {id = "byo", title = "Use Existing"},
]

[[composables]]
id = "pipeline-stage"
title = "Pipeline Stage"
default = "rank-fusion"
options = [
   {id = "rank-fusion", title = "$rankFusion"},
   {id = "score-fusion", title = "$scoreFusion"},
]

[[composables]]
id = "llm"
title = "LLM"
default = "openai"
options = [
   {id = "openai", title = "OpenAI"},
   {id = "open-source", title = "Open-source"},
]

[[composables]]
id = "data-source"
title = "Data Source"
default = "new"
options = [
   {id = "new", title = "New Data"},
   {id = "existing", title = "Existing Data"}
]

[[composables]]
id = "language-no-interface"
title = "Language"
default = "python"
options = [
  {id = "c", title = "C"},
  {id = "csharp", title = "C#"},
  {id = "cpp", title = "C++"},
  {id = "go", title = "Go"},
  {id = "java-async", title = "Java (Async)"},
  {id = "java-sync", title = "Java (Sync)"},
  {id = "kotlin", title = "Kotlin"},
  {id = "kotlin-coroutine", title = "Kotlin (Coroutine)"},
  {id = "motor", title = "Motor"},
  {id = "nodejs", title = "Node.js"},
  {id = "php", title = "PHP"},
  {id = "python", title = "Python"},
  {id = "ruby", title = "Ruby"},
  {id = "scala", title = "Scala"},
]

[[composables]]
id = "index-creation-method"
title = "Index Creation Method"
default = "driver"
options = [
  {id = "atlas-ui", title = "Atlas UI"},
  {id = "driver", title = "Driver"},
  {id = "atlas-cli", title = "Atlas CLI"},
]

[[composables]]
id = "vector-search-type"
title = "Vector Search"
default = "ann"
options = [
   {id = "ann", title = "Approximate Nearest Neighbor"},
   {id = "enn", title = "Exact Nearest Neighbor"}
]
