name = "mcp-server"
title = "MongoDB MCP Server"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv",
                "https://www.mongodb.com/docs/vector-search/objects.inv",
                "https://www.mongodb.com/docs/mongodb-vscode/objects.inv",
                "https://www.mongodb.com/docs/objects.inv",
                "https://www.mongodb.com/docs/search/objects.inv"
              ]

toc_landing_pages = ["/security"]

[constants]
atlas-sp = "Atlas Stream Processing"
mdb-mcp = "MongoDB MCP Server"
atlas-managed-mcp = "MongoDB Atlas (Managed MCP Server)"
plugin-atlas-managed-mcp-heading = "Plugin Setup: Atlas Managed MCP Server"
connector-atlas-managed-mcp-heading = "Connector Setup: Atlas Managed MCP Server"
manual-atlas-managed-mcp-heading = "Manual Setup: Atlas Managed MCP Server"
plugin-self-managed-mcp-heading = "Plugin Setup: Local MCP Server"
connector-self-managed-mcp-heading = "Connector Setup: Local MCP Server"
manual-self-managed-mcp-heading = "Manual Setup: Local MCP Server"
self-managed-mcp = "MongoDB (Self-Managed MCP Server)"
atlas-managed-mcp-server = "MongoDB Atlas Managed MCP Server"
remote-mcp-programmatic = "MongoDB Atlas Managed MCP Server"
local-mcp = "Local MCP for MongoDB MCP Server"
local-short = "Local MCP"
mdb-atlas-ai-client-title = "MongoDB Atlas"
self-managed-mdb-title = "Self-Managed MongoDB"
atlas-mcp-plugin = "MongoDB Atlas (Managed MCP) Plugin"
mcp-plugin = "MongoDB MCP Plugin"
manual-atlas-managed-mcp-env = "mcp"
manual-atlas-managed-mongodb-env = "cloud"

[[composables]]
id = "client"
title = "Client"
default = "claude-desktop"
options = [
   {id = "claude-code", title = "Claude Code"},
   {id = "claude-desktop", title = "Claude Desktop"},
   {id = "copilot", title = "VS Code GitHub Copilot"},
   {id = "cursor", title = "Cursor"},
   {id = "windsurf", title = "Windsurf"},
   {id = "augment", title = "Augment Code"},
   {id = "gemini-cli", title = "Gemini CLI"},
   {id = "codex", title = "Codex"},
   {id = "opencode", title = "OpenCode"},
]

[[composables]]
id = "ai-client"
title = "AI Client"
default = "claude-code"
options = [
   {id = "claude-code", title = "Claude Code"},
   {id = "claude-desktop-web", title = "Claude Desktop & Web"},
   {id = "chatgpt-desktop-web", title = "ChatGPT Desktop & Web"},
   {id = "cursor", title = "Cursor"},
   {id = "codex", title = "Codex"},
   {id = "devin", title = "Devin AI"},
   {id = "grok", title = "Grok Build"},
   {id = "other", title = "Other"},
   {id = "ai-frameworks-clients", title = "AI Frameworks Clients"},
]

[[composables]]
id = "deployment-type"
title = "Deployment"
default = "atlas"
options = [
   {id = "atlas", title="Atlas"},
   {id = "self-managed", title="Self-Managed"},
]
