/**
 * Builds the set of {localPath, key} entries to upload to S3: the
 * hand-maintained master index (llms-output/llms.txt) plus every per-project
 * llms*.txt file `generate()` has already written under outputDir.
 *
 * S3 keys mirror each file's production URL path (minus the
 * https://www.mongodb.com host), matching the existing convention of
 * `s3Prefix = 'docs/offline/'` etc. in
 * platform/nextjs-extension/src/offline-docs/index.ts: e.g. the "manual"
 * project's part 1 becomes "docs/manual/manual-1-llms.txt".
 *
 * Also warns (doesn't fail) if any file about to be uploaded isn't actually
 * linked from the hand-maintained master index yet: that index is what
 * makes a project/part discoverable to an agent starting from
 * https://www.mongodb.com/docs/llms.txt, so a file that exists on disk (or
 * in S3) but isn't linked there is effectively invisible. This most often
 * happens when a project is newly split into more parts than before (e.g.
 * "manual" going from 5 to 9 parts) and the master index wasn't updated to
 * match.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { PRODUCTION_BASE_URL } from './types.js';
import { currentSourceDir } from './projectInfo.js';
import { getUrlSlugForDir, loadDirNameToPrefixMap } from './urlResolver.js';

export interface UploadEntry {
  /** Absolute local path to the generated file. */
  localPath: string;
  /** S3 object key (path within the bucket), e.g. "docs/manual/manual-1-llms.txt". */
  key: string;
}

/**
 * The root "docs/llms.txt" key is reserved for the hand-maintained master
 * index, which links out to every project's own llms.txt. The `landing`
 * project (content/landing, the docs homepage) also generates a file that
 * would resolve to that same key; it's excluded here so it can never
 * overwrite the master index. See llms-output/llms.txt itself for the
 * index's content.
 */
const MASTER_INDEX_FILENAME = 'llms.txt';
const MASTER_INDEX_KEY = 'docs/llms.txt';
const EXCLUDED_FROM_UPLOAD = new Set(['landing']);

function buildFileKey(urlSlug: string, version: string, filename: string): string {
  const parts = ['docs'];
  if (urlSlug !== '') {
    parts.push(urlSlug);
  }
  if (version !== '') {
    parts.push(version);
  }
  parts.push(filename);
  return parts.join('/');
}

async function isDirectory(candidate: string): Promise<boolean> {
  try {
    const stat = await fs.stat(candidate);
    return stat.isDirectory();
  } catch {
    return false;
  }
}

/** "docs/manual/manual-1-llms.txt" -> "https://www.mongodb.com/docs/manual/manual-1-llms.txt". */
function keyToProductionUrl(key: string): string {
  const host = new URL(PRODUCTION_BASE_URL).origin;
  return `${host}/${key}`;
}

/**
 * Warns for every entry whose production URL doesn't appear anywhere in the
 * master index's own content, i.e. every file about to be uploaded that a
 * reader of https://www.mongodb.com/docs/llms.txt has no way to discover.
 * Never throws: a missing link is worth flagging loudly, but shouldn't
 * block generation or upload the way an actual key collision does.
 */
function warnAboutFilesMissingFromMasterIndex(masterIndexContent: string, entries: UploadEntry[]): void {
  const missing = entries.filter(
    (entry) => entry.key !== MASTER_INDEX_KEY && !masterIndexContent.includes(keyToProductionUrl(entry.key)),
  );
  if (missing.length === 0) {
    return;
  }
  console.warn(
    `\nWARNING: ${missing.length} file(s) are not linked from the master index (${MASTER_INDEX_FILENAME}) and ` +
      "won't be discoverable from https://www.mongodb.com/docs/llms.txt. Add a link for each to llms-output/llms.txt:",
  );
  for (const entry of missing) {
    console.warn(`  - ${keyToProductionUrl(entry.key)}`);
  }
}

/**
 * Builds the full upload manifest. Throws if the master index file is
 * missing (generate-llms's manual/llms-output/llms.txt must exist) or if two
 * entries would resolve to the same S3 key (a routing collision that must be
 * resolved before uploading, not silently overwritten).
 */
export async function buildUploadManifest(monorepoPath: string, outputDir: string): Promise<UploadEntry[]> {
  const entries: UploadEntry[] = [];

  const masterIndexPath = path.join(outputDir, MASTER_INDEX_FILENAME);
  let masterIndexContent: string;
  try {
    masterIndexContent = await fs.readFile(masterIndexPath, 'utf-8');
  } catch {
    throw new Error(
      `Master index not found at ${masterIndexPath}. It's hand-maintained (not generated by \`pnpm generate\`) ` +
        'and must exist before uploading.',
    );
  }
  entries.push({ localPath: masterIndexPath, key: MASTER_INDEX_KEY });

  const dirNameToPrefix = await loadDirNameToPrefixMap(monorepoPath);
  const contentDir = path.join(monorepoPath, 'content');

  const outputEntries = await fs.readdir(outputDir, { withFileTypes: true });
  for (const outputEntry of outputEntries) {
    if (!outputEntry.isDirectory()) {
      continue;
    }
    const project = outputEntry.name;
    if (EXCLUDED_FROM_UPLOAD.has(project)) {
      continue;
    }

    const urlSlug = getUrlSlugForDir(dirNameToPrefix, project);
    if (urlSlug === undefined) {
      console.warn(`Skipping "${project}": no URL prefix found in dir-name-to-prefix.json`);
      continue;
    }

    const projectDir = path.join(contentDir, project);
    const found = await currentSourceDir(projectDir);
    if (!found) {
      console.warn(`Skipping "${project}": no resolvable current source directory under ${projectDir}`);
      continue;
    }

    const projectOutputDir = path.join(outputDir, project);
    if (!(await isDirectory(projectOutputDir))) {
      continue;
    }
    const filenames = (await fs.readdir(projectOutputDir)).filter((name) => name.endsWith('.txt'));
    for (const filename of filenames) {
      entries.push({
        localPath: path.join(projectOutputDir, filename),
        key: buildFileKey(urlSlug, found.version, filename),
      });
    }
  }

  const seenKeys = new Map<string, string>();
  for (const entry of entries) {
    const existing = seenKeys.get(entry.key);
    if (existing) {
      throw new Error(
        `S3 key collision: both "${existing}" and "${entry.localPath}" resolve to key "${entry.key}". ` +
          'Resolve this before uploading (do not let one silently overwrite the other).',
      );
    }
    seenKeys.set(entry.key, entry.localPath);
  }

  entries.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
  warnAboutFilesMissingFromMasterIndex(masterIndexContent, entries);
  return entries;
}
