
[build]
publish = "dist"
base = "content/django-mongodb"

[build.environment]
REPO_NAME = "docs-django"
SECRETS_SCAN_ENABLED = "false"
MUT_COMMANDS_ENABLED = "false"

[context.production.environment]
ENV = "dotcomprd"

[context.preprd.environment]
ENV = "dotcomstg"

[context.deploy-preview.environment]
ENV = "prd"

[context.branch-deploy.environment]
ENV = "prd"

[context.preview-server.environment]
ENV = "prd"

[context.dev.environment]
ENV = "stg"

##### Redirects listed in the following order.
# OFFLINE REDIRECTS
# ALIAS WILDCARD REDIRECTS
# MAJOR REDIRECTS (all versions except manual)
# WILDCARD REDIRECTS
# MANUAL REDIRECTS
# "CATCH-ALLS"

### OFFLINE REDIRECTS 
[[redirects]]
from = "/docs/languages/python/django-mongodb/v5.0/*"
to = "/docs/languages/python/django-mongodb/current/:splat"

[[redirects]]
from = "/docs/languages/python/django-mongodb/v5.1/*"
to = "/docs/languages/python/django-mongodb/current/:splat"

### ALIAS REDIRECTS
[[redirects]]
from = "/docs/languages/python/django-mongodb/v6.0/*"
to = "/docs/languages/python/django-mongodb/current/:splat"
status = 302

[[redirects]]
from = "/docs/languages/python/django-mongodb/master/*"
to = "/docs/languages/python/django-mongodb/upcoming/:splat"

### WILDCARD REDIRECTS
[[redirects]]
from = "/docs/languages/python/django-mongodb/:version/compatibility/"
to = "/docs/drivers/compatibility/?driver-language=python&python-driver-framework=django"

[[redirects]]
from = "/docs/languages/python/django-mongodb/:version/get-started/install"
to = "/docs/languages/python/django-mongodb/:version/get-started/#download-and-install"

[[redirects]]
from = "/docs/languages/python/django-mongodb/:version/get-started/create-deployment"
to = "/docs/languages/python/django-mongodb/:version/get-started/#create-a-mongodb-deployment"

[[redirects]]
from = "/docs/languages/python/django-mongodb/:version/get-started/connection-string"
to = "/docs/languages/python/django-mongodb/:version/get-started/#create-a-connection-string"

[[redirects]]
from = "/docs/languages/python/django-mongodb/:version/get-started/connect-mongodb"
to = "/docs/languages/python/django-mongodb/:version/get-started/#configure-your-mongodb-connection"

[[redirects]]
from = "/docs/languages/python/django-mongodb/:version/get-started/create-app"
to = "/docs/languages/python/django-mongodb/:version/get-started/#create-an-application"

[[redirects]]
from = "/docs/languages/python/django-mongodb/:version/get-started/write-data"
to = "/docs/languages/python/django-mongodb/:version/get-started/#write-data-to-mongodb"

[[redirects]]
from = "/docs/languages/python/django-mongodb/:version/get-started/query-data"
to = "/docs/languages/python/django-mongodb/:version/get-started/#query-mongodb-data"

[[redirects]]
from = "/docs/languages/python/django-mongodb/:version/get-started/create-admin"
to = "/docs/languages/python/django-mongodb/:version/get-started/#create-an-admin-site"

[[redirects]]
from = "/docs/languages/python/django-mongodb/:version/get-started/next-steps"
to = "/docs/languages/python/django-mongodb/:version/get-started/#next-steps"

#Online versions: ['upcoming', 'current']
### CATCH ALLS (Redirects any /docs/languages/python/django-mongodb/ page that would've 404ed to the version's landing page)
[[redirects]]
from = "/docs/languages/python/django-mongodb/upcoming/*"
to = "/docs/languages/python/django-mongodb/intermediary/upcoming/:splat"
status = 302

[[redirects]]
from = "/docs/languages/python/django-mongodb/intermediary/upcoming/*"
to = "/docs/languages/python/django-mongodb/upcoming"
status = 302

[[redirects]]
from = "/docs/languages/python/django-mongodb/current/*"
to = "/docs/languages/python/django-mongodb/intermediary/current/:splat"
status = 302

[[redirects]]
from = "/docs/languages/python/django-mongodb/intermediary/current/*"
to = "/docs/languages/python/django-mongodb/current"
status = 302

### CATCH ALLS (add slug to paths without slug)
[[redirects]]
from = "/docs/languages/python/django-mongodb/upcoming/*"
to = "/docs/languages/python/django-mongodb/upcoming/:splat"
status = 200

[[redirects]]
from = "/docs/languages/python/django-mongodb/current/*"
to = "/docs/languages/python/django-mongodb/current/:splat"
status = 200

[[redirects]]
from = "/docs/languages/python/django-mongodb/v5.2/*"
to = "/docs/languages/python/django-mongodb/v5.2/:splat"
status = 200

[[redirects]]
from = "/docs/languages/python/django-mongodb/*"
to = "/docs/languages/python/django-mongodb/current/:splat"

[[redirects]]
from = "/docs/languages/python/django-mongodb/:version/atlas-search/"
to = "/docs/languages/python/django-mongodb/:version/mongodb-search/"

[[redirects]]
from = "/docs/languages/python/django-mongodb/:version/atlas-vector-search/"
to = "/docs/languages/python/django-mongodb/:version/mongodb-vector-search/"
