export enum ENVIRONMENT_VARS {
  FRONTEND_VERSION = 'FRONTEND_VERSION',
  GATSBY_USE_UNIFIED_TOC = 'GATSBY_USE_UNIFIED_TOC',
  POPULATE_METADATA_ENABLED = 'POPULATE_METADATA_ENABLED'
}

export enum PROD_PREPROD_BRANCH_NAMES {
  PREPRD = 'preprd',
  MAIN = 'main'
}
