name: Java Driver - Sync - Code Examples - Check Formatting

on:
  pull_request:
    paths:
      - "code-example-tests/java/**/src/**"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21.0.11'
      - name: Check code example formatting
        run: |
          cd code-example-tests/java/
          mvn spotless:check
