name: CI (platform)

on:
  pull_request:
    paths:
      - '.github/workflows/platform-ci.yml'
      - 'platform/**'
  workflow_dispatch:

jobs:
  test:
    name: Run Tests in platform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform
    env:
      NPM_BASE_64_AUTH: ${{ secrets.NPM_BASE_64_AUTH }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm@10.27.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: platform/pnpm-lock.yaml

      - name: Install dependencies
        # Remove --no-frozen-lockfile as soon as possible
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Unit tests
        run: pnpm run test
